// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.textures.internal;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import whiteout.common.internal.NativeCommon;

/** FFM MethodHandle registry for this module. Internal — for codegen use. */
public final class Native {
    private Native() {}

    public static final MemoryLayout BYTES_LAYOUT = NativeCommon.BYTES_LAYOUT;
    public static final MemoryLayout CSTRING_LAYOUT = NativeCommon.CSTRING_LAYOUT;
    public static final MethodHandle whiteout_Bytes_free = NativeCommon.whiteout_Bytes_free;
    public static final MethodHandle whiteout_CString_free = NativeCommon.whiteout_CString_free;

    static MethodHandle find(String name, FunctionDescriptor fd) {
        return NativeCommon.find(name, fd);
    }

    // -- Texture --
    public static final MethodHandle whiteout_textures_Texture_new = find(
        "whiteout_textures_Texture_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_delete = find(
        "whiteout_textures_Texture_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_format = find(
        "whiteout_textures_Texture_format", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_Texture_format_overload2 = find(
        "whiteout_textures_Texture_format_overload2", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_copyAsFormat = find(
        "whiteout_textures_Texture_copyAsFormat", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_copyFromNormalToRGBA = find(
        "whiteout_textures_Texture_copyFromNormalToRGBA", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_generateMipmaps = find(
        "whiteout_textures_Texture_generateMipmaps", FunctionDescriptor.of(CSTRING_LAYOUT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_generateMipmaps_pool = find(
        "whiteout_textures_Texture_generateMipmaps_pool", FunctionDescriptor.of(CSTRING_LAYOUT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_downscale = find(
        "whiteout_textures_Texture_downscale", FunctionDescriptor.of(CSTRING_LAYOUT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_create2D = find(
        "whiteout_textures_Texture_create2D", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_Texture_create3D = find(
        "whiteout_textures_Texture_create3D", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_Texture_createCube = find(
        "whiteout_textures_Texture_createCube", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_Texture_create2DArray = find(
        "whiteout_textures_Texture_create2DArray", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_Texture_createCubeArray = find(
        "whiteout_textures_Texture_createCubeArray", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_Texture_type = find(
        "whiteout_textures_Texture_type", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_isSrgb = find(
        "whiteout_textures_Texture_isSrgb", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_setSrgb = find(
        "whiteout_textures_Texture_setSrgb", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_Texture_width = find(
        "whiteout_textures_Texture_width", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_height = find(
        "whiteout_textures_Texture_height", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_depth = find(
        "whiteout_textures_Texture_depth", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_layerCount = find(
        "whiteout_textures_Texture_layerCount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_arraySize = find(
        "whiteout_textures_Texture_arraySize", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_mipCount = find(
        "whiteout_textures_Texture_mipCount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_dataSize = find(
        "whiteout_textures_Texture_dataSize", FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_data = find(
        "whiteout_textures_Texture_data", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_mipData = find(
        "whiteout_textures_Texture_mipData", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_Texture_takeData = find(
        "whiteout_textures_Texture_takeData", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_Texture_setData = find(
        "whiteout_textures_Texture_setData", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));

    // -- BlpParser --
    public static final MethodHandle whiteout_textures_BlpParser_new = find(
        "whiteout_textures_BlpParser_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_BlpParser_delete = find(
        "whiteout_textures_BlpParser_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_BlpParser_parse = find(
        "whiteout_textures_BlpParser_parse", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    public static final MethodHandle whiteout_textures_BlpParser_hasIssues = find(
        "whiteout_textures_BlpParser_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    // -- BlpWriter --
    public static final MethodHandle whiteout_textures_BlpWriter_new = find(
        "whiteout_textures_BlpWriter_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_BlpWriter_new_pool = find(
        "whiteout_textures_BlpWriter_new_pool", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_BlpWriter_delete = find(
        "whiteout_textures_BlpWriter_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_BlpWriter_write = find(
        "whiteout_textures_BlpWriter_write", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_BlpWriter_hasIssues = find(
        "whiteout_textures_BlpWriter_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    // -- PngApngFrameInfo --
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_new = find(
        "whiteout_textures_PngApngFrameInfo_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_delete = find(
        "whiteout_textures_PngApngFrameInfo_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_get_width = find("whiteout_textures_PngApngFrameInfo_get_width", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_set_width = find("whiteout_textures_PngApngFrameInfo_set_width", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_get_height = find("whiteout_textures_PngApngFrameInfo_get_height", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_set_height = find("whiteout_textures_PngApngFrameInfo_set_height", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_get_xOffset = find("whiteout_textures_PngApngFrameInfo_get_xOffset", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_set_xOffset = find("whiteout_textures_PngApngFrameInfo_set_xOffset", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_get_yOffset = find("whiteout_textures_PngApngFrameInfo_get_yOffset", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_set_yOffset = find("whiteout_textures_PngApngFrameInfo_set_yOffset", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_get_delayMs = find("whiteout_textures_PngApngFrameInfo_get_delayMs", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_set_delayMs = find("whiteout_textures_PngApngFrameInfo_set_delayMs", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_get_disposeOp = find("whiteout_textures_PngApngFrameInfo_get_disposeOp", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_set_disposeOp = find("whiteout_textures_PngApngFrameInfo_set_disposeOp", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_get_blendOp = find("whiteout_textures_PngApngFrameInfo_get_blendOp", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrameInfo_set_blendOp = find("whiteout_textures_PngApngFrameInfo_set_blendOp", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    // -- PngParser --
    public static final MethodHandle whiteout_textures_PngParser_new = find(
        "whiteout_textures_PngParser_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngParser_delete = find(
        "whiteout_textures_PngParser_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngParser_parse = find(
        "whiteout_textures_PngParser_parse", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    public static final MethodHandle whiteout_textures_PngParser_hasIssues = find(
        "whiteout_textures_PngParser_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngParser_isAnimated = find(
        "whiteout_textures_PngParser_isAnimated", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngParser_frameCount = find(
        "whiteout_textures_PngParser_frameCount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngParser_loopCount = find(
        "whiteout_textures_PngParser_loopCount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngParser_frame = find(
        "whiteout_textures_PngParser_frame", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_PngParser_frameDelayMs = find(
        "whiteout_textures_PngParser_frameDelayMs", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_PngParser_frameInfo = find(
        "whiteout_textures_PngParser_frameInfo", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    // -- PngApngFrame --
    public static final MethodHandle whiteout_textures_PngApngFrame_new = find(
        "whiteout_textures_PngApngFrame_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrame_delete = find(
        "whiteout_textures_PngApngFrame_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrame_get_image = find("whiteout_textures_PngApngFrame_get_image", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrame_set_image = find("whiteout_textures_PngApngFrame_set_image", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrame_get_delayMs = find("whiteout_textures_PngApngFrame_get_delayMs", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngFrame_set_delayMs = find("whiteout_textures_PngApngFrame_set_delayMs", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    // -- PngApngSaveOptions --
    public static final MethodHandle whiteout_textures_PngApngSaveOptions_new = find(
        "whiteout_textures_PngApngSaveOptions_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngSaveOptions_delete = find(
        "whiteout_textures_PngApngSaveOptions_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngSaveOptions_get_loopCount = find("whiteout_textures_PngApngSaveOptions_get_loopCount", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngApngSaveOptions_set_loopCount = find("whiteout_textures_PngApngSaveOptions_set_loopCount", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    // -- PngWriter --
    public static final MethodHandle whiteout_textures_PngWriter_new = find(
        "whiteout_textures_PngWriter_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngWriter_delete = find(
        "whiteout_textures_PngWriter_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngWriter_write = find(
        "whiteout_textures_PngWriter_write", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngWriter_writeAnimated = find(
        "whiteout_textures_PngWriter_writeAnimated", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_PngWriter_hasIssues = find(
        "whiteout_textures_PngWriter_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    // -- JpegParser --
    public static final MethodHandle whiteout_textures_JpegParser_new = find(
        "whiteout_textures_JpegParser_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_JpegParser_new_pool = find(
        "whiteout_textures_JpegParser_new_pool", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_JpegParser_delete = find(
        "whiteout_textures_JpegParser_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_JpegParser_parse = find(
        "whiteout_textures_JpegParser_parse", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    public static final MethodHandle whiteout_textures_JpegParser_hasIssues = find(
        "whiteout_textures_JpegParser_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    // -- JpegWriter --
    public static final MethodHandle whiteout_textures_JpegWriter_new = find(
        "whiteout_textures_JpegWriter_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_JpegWriter_new_quality_pool_progressive = find(
        "whiteout_textures_JpegWriter_new_quality_pool_progressive", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_BYTE));
    public static final MethodHandle whiteout_textures_JpegWriter_delete = find(
        "whiteout_textures_JpegWriter_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_JpegWriter_write = find(
        "whiteout_textures_JpegWriter_write", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_JpegWriter_hasIssues = find(
        "whiteout_textures_JpegWriter_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    // -- DdsParser --
    public static final MethodHandle whiteout_textures_DdsParser_new = find(
        "whiteout_textures_DdsParser_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_DdsParser_delete = find(
        "whiteout_textures_DdsParser_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_DdsParser_parse = find(
        "whiteout_textures_DdsParser_parse", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    public static final MethodHandle whiteout_textures_DdsParser_hasIssues = find(
        "whiteout_textures_DdsParser_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    // -- DdsWriter --
    public static final MethodHandle whiteout_textures_DdsWriter_new = find(
        "whiteout_textures_DdsWriter_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_DdsWriter_delete = find(
        "whiteout_textures_DdsWriter_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_DdsWriter_write = find(
        "whiteout_textures_DdsWriter_write", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_DdsWriter_hasIssues = find(
        "whiteout_textures_DdsWriter_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    // -- BmpParser --
    public static final MethodHandle whiteout_textures_BmpParser_new = find(
        "whiteout_textures_BmpParser_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_BmpParser_delete = find(
        "whiteout_textures_BmpParser_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_BmpParser_parse = find(
        "whiteout_textures_BmpParser_parse", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    public static final MethodHandle whiteout_textures_BmpParser_hasIssues = find(
        "whiteout_textures_BmpParser_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    // -- BmpWriter --
    public static final MethodHandle whiteout_textures_BmpWriter_new = find(
        "whiteout_textures_BmpWriter_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_BmpWriter_delete = find(
        "whiteout_textures_BmpWriter_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_BmpWriter_write = find(
        "whiteout_textures_BmpWriter_write", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_BmpWriter_hasIssues = find(
        "whiteout_textures_BmpWriter_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    // -- TgaParser --
    public static final MethodHandle whiteout_textures_TgaParser_new = find(
        "whiteout_textures_TgaParser_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_TgaParser_delete = find(
        "whiteout_textures_TgaParser_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_TgaParser_parse = find(
        "whiteout_textures_TgaParser_parse", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    public static final MethodHandle whiteout_textures_TgaParser_hasIssues = find(
        "whiteout_textures_TgaParser_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    // -- TgaWriter --
    public static final MethodHandle whiteout_textures_TgaWriter_new = find(
        "whiteout_textures_TgaWriter_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_TgaWriter_delete = find(
        "whiteout_textures_TgaWriter_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_TgaWriter_write = find(
        "whiteout_textures_TgaWriter_write", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_TgaWriter_hasIssues = find(
        "whiteout_textures_TgaWriter_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

    // -- GifSaveOptions --
    public static final MethodHandle whiteout_textures_GifSaveOptions_new = find(
        "whiteout_textures_GifSaveOptions_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_GifSaveOptions_delete = find(
        "whiteout_textures_GifSaveOptions_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_GifSaveOptions_get_delayCs = find("whiteout_textures_GifSaveOptions_get_delayCs", FunctionDescriptor.of(ValueLayout.JAVA_SHORT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_GifSaveOptions_set_delayCs = find("whiteout_textures_GifSaveOptions_set_delayCs", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_SHORT));
    public static final MethodHandle whiteout_textures_GifSaveOptions_get_loopCount = find("whiteout_textures_GifSaveOptions_get_loopCount", FunctionDescriptor.of(ValueLayout.JAVA_SHORT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_GifSaveOptions_set_loopCount = find("whiteout_textures_GifSaveOptions_set_loopCount", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_SHORT));
    public static final MethodHandle whiteout_textures_GifSaveOptions_get_dither = find("whiteout_textures_GifSaveOptions_get_dither", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_GifSaveOptions_set_dither = find("whiteout_textures_GifSaveOptions_set_dither", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_textures_GifSaveOptions_get_ditherStrength = find("whiteout_textures_GifSaveOptions_get_ditherStrength", FunctionDescriptor.of(ValueLayout.JAVA_FLOAT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_GifSaveOptions_set_ditherStrength = find("whiteout_textures_GifSaveOptions_set_ditherStrength", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_FLOAT));
    public static final MethodHandle whiteout_textures_GifSaveOptions_get_transparent = find("whiteout_textures_GifSaveOptions_get_transparent", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_GifSaveOptions_set_transparent = find("whiteout_textures_GifSaveOptions_set_transparent", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    // -- GifWriter --
    public static final MethodHandle whiteout_textures_GifWriter_new = find(
        "whiteout_textures_GifWriter_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_GifWriter_new_pool = find(
        "whiteout_textures_GifWriter_new_pool", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_GifWriter_delete = find(
        "whiteout_textures_GifWriter_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_GifWriter_write = find(
        "whiteout_textures_GifWriter_write", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    public static final MethodHandle whiteout_textures_GifWriter_write_frames = find(
        "whiteout_textures_GifWriter_write_frames", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    public static final MethodHandle whiteout_textures_GifWriter_write_filePath_frames_opts = find(
        "whiteout_textures_GifWriter_write_filePath_frames_opts", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_GifWriter_write_frames_opts = find(
        "whiteout_textures_GifWriter_write_frames_opts", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_textures_GifWriter_hasIssues = find(
        "whiteout_textures_GifWriter_hasIssues", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));

}
