// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.utils;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.host.internal.Native;

/**
 * abstract opaque base. Concrete impl: utils::SimpleThreadPool.
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * WorkerPool allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (WorkerPool obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class WorkerPool implements AutoCloseable, whiteout.interfaces.WorkerPool, whiteout.host.NativeHandled {
    private static final long BYTES = 8L;

    final MemorySegment handle;
    final boolean owned;

    WorkerPool(MemorySegment seg, boolean owned) {
        this.handle = (seg == null || seg.equals(MemorySegment.NULL))
            ? seg : seg.reinterpret(BYTES);
        this.owned = owned;
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                Native.whiteout_host_WorkerPool_delete.invoke(handle);
            } catch (Throwable __ex) { throw new RuntimeException(__ex); }
        }
    }

    /**
     * Block until every submitted task has completed.
     */
    public void waitIdle() {
        try {
        Native.whiteout_host_WorkerPool_waitIdle.invoke(handle);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    /**
     * Number of worker threads in this pool.
     * @return long result.
     */
    public long threadCount() {
        try {
        return (long) Native.whiteout_host_WorkerPool_threadCount.invoke(handle);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    /** {@inheritDoc} */
    @Override
    public MemorySegment nativeHandle() { return handle; }

    @Override
    public void submit(whiteout.interfaces.WorkerTask task) {
        throw new UnsupportedOperationException(
            "WorkerPool.submit cannot be invoked from Java on a native-backed "
            + "wrapper — the C ABI does not marshal callback / std::function params. "
            + "Either (a) pass this instance to a native consumer that takes WorkerPool "
            + "(the consumer's C++ side will call this directly), or "
            + "(b) implement WorkerPool in pure Java if you need Java-controlled dispatch.");
    }

    @Override public String toString() {
        return "WorkerPool@" + Long.toHexString(handle == null ? 0 : handle.address());
    }

}
