// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Fernando Sahmkow
// AUTOGENERATED by tools/codegen/emit_csharp.py — DO NOT EDIT.

using System.Runtime.InteropServices;
using Whiteout.Common;
using Whiteout.M2.Internal;

namespace Whiteout.M2;

/// <summary>One collision shape reference — SHAP/SHP2. Points at an entry of the box/capsule/sphere/polytope array named by @ref shapeType.</summary>
public sealed class PhysicsShape : WhiteoutHandle
{
    public PhysicsShape() : base(NativeMethods.whiteout_m2_M2PhysicsShape_new()) { }

    internal PhysicsShape(IntPtr handle, bool owned = true) : base(handle, owned) { }

    protected override bool ReleaseHandle()
    {
        NativeMethods.whiteout_m2_M2PhysicsShape_delete(handle);
        return true;
    }

    public PhysicsShapeType ShapeType
    {
        get => (PhysicsShapeType)NativeMethods.whiteout_m2_M2PhysicsShape_get_shapeType(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsShape_set_shapeType(DangerousGet(), (int)value);
    }


    public short ShapeIndex
    {
        get => NativeMethods.whiteout_m2_M2PhysicsShape_get_shapeIndex(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsShape_set_shapeIndex(DangerousGet(), value);
    }


    /// <summary>`dmFixtureDef.gameFlags`. Zero in every corpus shape.</summary>
    public ushort GameFlags
    {
        get => NativeMethods.whiteout_m2_M2PhysicsShape_get_gameFlags(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsShape_set_gameFlags(DangerousGet(), value);
    }


    public ushort Padding06
    {
        get => NativeMethods.whiteout_m2_M2PhysicsShape_get_padding06(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsShape_set_padding06(DangerousGet(), value);
    }


    public float Friction
    {
        get => NativeMethods.whiteout_m2_M2PhysicsShape_get_friction(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsShape_set_friction(DangerousGet(), value);
    }


    public float Restitution
    {
        get => NativeMethods.whiteout_m2_M2PhysicsShape_get_restitution(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsShape_set_restitution(DangerousGet(), value);
    }


    /// <summary>Rescaled by the client for capsules in files of version 4 and below (`PHYS_FORMAT.md` §4.2).</summary>
    public float Density
    {
        get => NativeMethods.whiteout_m2_M2PhysicsShape_get_density(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsShape_set_density(DangerousGet(), value);
    }


    /// <summary>@name SHP2+, parsed and never read The client copies these onto its shape def and no `CreateInstance` reads them (`PHYS_FORMAT.md` §4.5). SHAP's upgrade gives 0, 1.0 and 0. @{</summary>
    public float Unused14
    {
        get => NativeMethods.whiteout_m2_M2PhysicsShape_get_unused14(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsShape_set_unused14(DangerousGet(), value);
    }


    /// <summary>1.0 in 3229 of 3230 shapes, and still not the fixture scale.</summary>
    public float Unused18
    {
        get => NativeMethods.whiteout_m2_M2PhysicsShape_get_unused18(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsShape_set_unused18(DangerousGet(), value);
    }


    public ushort Unused1c
    {
        get => NativeMethods.whiteout_m2_M2PhysicsShape_get_unused1c(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsShape_set_unused1c(DangerousGet(), value);
    }


    /// <summary>SHP2+. Uninitialised on disk; kept so writes match.</summary>
    public ushort Padding1e
    {
        get => NativeMethods.whiteout_m2_M2PhysicsShape_get_padding1e(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsShape_set_padding1e(DangerousGet(), value);
    }

}
