// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Fernando Sahmkow
// AUTOGENERATED by tools/codegen/emit_csharp.py — DO NOT EDIT.

using System.Runtime.InteropServices;
using Whiteout.Common;
using Whiteout.M2.Internal;

namespace Whiteout.M2;

/// <summary>PHYV — the per-model vegetation push: the six `physVeg*` console variables in registration order (`PHYS_FORMAT.md` §3.9).</summary>
public sealed class PhysicsTuning : WhiteoutHandle
{
    public PhysicsTuning() : base(NativeMethods.whiteout_m2_M2PhysicsTuning_new()) { }

    internal PhysicsTuning(IntPtr handle, bool owned = true) : base(handle, owned) { }

    protected override bool ReleaseHandle()
    {
        NativeMethods.whiteout_m2_M2PhysicsTuning_delete(handle);
        return true;
    }

    /// <summary>Yards a bone may be pushed from its base before it is clamped.</summary>
    public float PosMaxPush
    {
        get => NativeMethods.whiteout_m2_M2PhysicsTuning_get_posMaxPush(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsTuning_set_posMaxPush(DangerousGet(), value);
    }


    /// <summary>The fraction of its target a bone is pushed each frame while a unit moves along it; 12.1 does not scale it by dt.</summary>
    public float PosPushAmt
    {
        get => NativeMethods.whiteout_m2_M2PhysicsTuning_get_posPushAmt(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsTuning_set_posPushAmt(DangerousGet(), value);
    }


    /// <summary>How fast the bone returns to rest once the unit leaves.</summary>
    public float PosRelaxSpeed
    {
        get => NativeMethods.whiteout_m2_M2PhysicsTuning_get_posRelaxSpeed(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsTuning_set_posRelaxSpeed(DangerousGet(), value);
    }


    /// <summary>Extra push along a moving unit's velocity.</summary>
    public float VelMaxPush
    {
        get => NativeMethods.whiteout_m2_M2PhysicsTuning_get_velMaxPush(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsTuning_set_velMaxPush(DangerousGet(), value);
    }


    /// <summary>How fast the bone sways along that velocity.</summary>
    public float VelSpeed
    {
        get => NativeMethods.whiteout_m2_M2PhysicsTuning_get_velSpeed(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsTuning_set_velSpeed(DangerousGet(), value);
    }


    /// <summary>**Squared** distance inside which a unit starts pushing. The client uses 8.0 for a model with no PHYV.</summary>
    public float MinPushDist
    {
        get => NativeMethods.whiteout_m2_M2PhysicsTuning_get_minPushDist(DangerousGet());
        set => NativeMethods.whiteout_m2_M2PhysicsTuning_set_minPushDist(DangerousGet(), value);
    }

}
