// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Fernando Sahmkow
//
// GENERATED by tools/codegen (--backend wem-native) from the m2 parser
// headers. Do not edit: re-run the generator and commit the diff.
//
// A block whose shape changes here must have its version bumped in
// tools/codegen/wem_schema.lock — see WEM design §15.2.

#pragma once

#include <optional>
#include <string>
#include <vector>

#include <whiteout/common_types.h>
#include <whiteout/models/wem/chunk_traits.h>
#include <whiteout/models/wem/native/flag_ops.h>
#include <whiteout/vector_types.h>

namespace whiteout {
namespace models {
namespace wem {
namespace native {

/// Mirror of `whiteout::m2::MaterialFlag`.
enum class M2MaterialFlag : u16 {
    None = 0,
    Unlit = 0x1,
    Unfogged = 0x2,
    TwoSided = 0x4,
    DepthTest = 0x8,
    DepthWrite = 0x10,
    NoAlphaComposite = 0x800,
};
WHITEOUT_WEM_DEFINE_FLAG_OPERATORS(M2MaterialFlag)

inline const char* ToString(M2MaterialFlag value) {
    switch (value) {
    case M2MaterialFlag::None:
        return "None";
    case M2MaterialFlag::Unlit:
        return "Unlit";
    case M2MaterialFlag::Unfogged:
        return "Unfogged";
    case M2MaterialFlag::TwoSided:
        return "TwoSided";
    case M2MaterialFlag::DepthTest:
        return "DepthTest";
    case M2MaterialFlag::DepthWrite:
        return "DepthWrite";
    case M2MaterialFlag::NoAlphaComposite:
        return "NoAlphaComposite";
    default:
        return "?";
    }
}

/// Mirror of `whiteout::m2::Batch`.
struct M2Batch {
    u8 flags{};
    i8 priorityPlane{};
    u16 shaderId{};
    u16 skinSectionIndex{};
    u16 geosetIndex{};
    i16 colorIndex{};
    u16 materialIndex{};
    u16 materialLayer{};
    u16 textureCount{};
    u16 textureComboIndex{};
    u16 textureCoordComboIndex{};
    u16 textureWeightComboIndex{};
    u16 textureTransformComboIndex{};

    template <class V>
    void reflect(V& v) {
        v.field("flags", flags);
        v.field("priorityPlane", priorityPlane);
        v.field("shaderId", shaderId);
        v.field("skinSectionIndex", skinSectionIndex);
        v.field("geosetIndex", geosetIndex);
        v.field("colorIndex", colorIndex);
        v.field("materialIndex", materialIndex);
        v.field("materialLayer", materialLayer);
        v.field("textureCount", textureCount);
        v.field("textureComboIndex", textureComboIndex);
        v.field("textureCoordComboIndex", textureCoordComboIndex);
        v.field("textureWeightComboIndex", textureWeightComboIndex);
        v.field("textureTransformComboIndex", textureTransformComboIndex);
    }
};

/// Mirror of `whiteout::m2::Texture`.
struct M2Texture {
    u32 type{};
    u32 flags{};
    std::string filename;

    template <class V>
    void reflect(V& v) {
        v.field("type", type);
        v.field("flags", flags);
        v.field("filename", filename);
    }
};

/// Mirror of `whiteout::m2::Material`.
struct M2RenderRecord {
    u16 flags{};
    u16 blendingMode{};

    template <class V>
    void reflect(V& v) {
        v.field("flags", flags);
        v.field("blendingMode", blendingMode);
    }
};

/// Fields carrying `@wem manual`: mirrored, but the copy halves leave them
/// to the converter. Named here so a field newly added to a parser header
/// cannot end up silently half-copied — it either copies, or a test names it.
inline constexpr const char* const* kM2ManualFields = nullptr;
inline constexpr std::size_t kM2ManualFieldCount = 0;

} // namespace native

} // namespace wem
} // namespace models
} // namespace whiteout
