// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Fernando Sahmkow
//
// GENERATED by tools/codegen (--backend wem-native) from the mdx parser
// headers. Do not edit: re-run the generator and commit the diff.
//
// A block whose shape changes here must have its version bumped in
// tools/codegen/wem_schema.lock — see WEM design §15.2.

#pragma once

#include <optional>
#include <string>
#include <vector>

#include <whiteout/common_types.h>
#include <whiteout/models/wem/chunk_traits.h>
#include <whiteout/models/wem/native/flag_ops.h>
#include <whiteout/vector_types.h>

namespace whiteout {
namespace models {
namespace wem {
namespace native {

/// Material-level flags
enum class MdxMaterialFlag : u32 {
    None = 0,
    ConstantColor = 0x1,   ///< Use constant color (no per-vertex tinting)
    TwoSided = 0x2,        ///< Render both sides of polygons
    Unfogged = 0x4,        ///< Not affected by fog
    SortPrimsNearZ = 0x8,  ///< Sort by near-Z
    SortPrimsFarZ = 0x10,  ///< Sort by far-Z; alias: SortPrimitives
    FullResolution = 0x20, ///< Force full-resolution textures
};
WHITEOUT_WEM_DEFINE_FLAG_OPERATORS(MdxMaterialFlag)

inline const char* ToString(MdxMaterialFlag value) {
    switch (value) {
    case MdxMaterialFlag::None:
        return "None";
    case MdxMaterialFlag::ConstantColor:
        return "ConstantColor";
    case MdxMaterialFlag::TwoSided:
        return "TwoSided";
    case MdxMaterialFlag::Unfogged:
        return "Unfogged";
    case MdxMaterialFlag::SortPrimsNearZ:
        return "SortPrimsNearZ";
    case MdxMaterialFlag::SortPrimsFarZ:
        return "SortPrimsFarZ";
    case MdxMaterialFlag::FullResolution:
        return "FullResolution";
    default:
        return "?";
    }
}

/// Blending/filter mode for the layer
enum class MdxFilterMode : u32 {
    None = 0,        ///< No blending
    Transparent = 1, ///< Alpha test transparency
    Blend = 2,       ///< Alpha blending
    Additive = 3,    ///< Additive blending
    AddAlpha = 4,    ///< Additive alpha blending
    Modulate = 5,    ///< Modulate (multiply) blending
    Modulate2x = 6,  ///< Modulate 2x (brighten)
    Count = 7,
};

inline const char* ToString(MdxFilterMode value) {
    switch (value) {
    case MdxFilterMode::None:
        return "None";
    case MdxFilterMode::Transparent:
        return "Transparent";
    case MdxFilterMode::Blend:
        return "Blend";
    case MdxFilterMode::Additive:
        return "Additive";
    case MdxFilterMode::AddAlpha:
        return "AddAlpha";
    case MdxFilterMode::Modulate:
        return "Modulate";
    case MdxFilterMode::Modulate2x:
        return "Modulate2x";
    case MdxFilterMode::Count:
        return "Count";
    default:
        return "?";
    }
}

/// Shader and rendering flags
enum class MdxShadingFlag : u32 {
    None = 0,
    Unshaded = 0x1,     ///< Not affected by lighting
    SphereEnvMap = 0x2, ///< Spherical environment mapping
    WrapWidth = 0x4,    ///< Texture U-wrap
    WrapHeight = 0x8,   ///< Texture V-wrap
    TwoSided = 0x10,    ///< Render both sides of polygons
    Unfogged = 0x20,    ///< Not affected by fog
    NoDepthTest = 0x40, ///< Disable depth testing
    NoDepthSet = 0x80,  ///< Don't write to depth buffer
    Unlit = 0x100,      ///< Reforged: bypass lighting pipeline
};
WHITEOUT_WEM_DEFINE_FLAG_OPERATORS(MdxShadingFlag)

inline const char* ToString(MdxShadingFlag value) {
    switch (value) {
    case MdxShadingFlag::None:
        return "None";
    case MdxShadingFlag::Unshaded:
        return "Unshaded";
    case MdxShadingFlag::SphereEnvMap:
        return "SphereEnvMap";
    case MdxShadingFlag::WrapWidth:
        return "WrapWidth";
    case MdxShadingFlag::WrapHeight:
        return "WrapHeight";
    case MdxShadingFlag::TwoSided:
        return "TwoSided";
    case MdxShadingFlag::Unfogged:
        return "Unfogged";
    case MdxShadingFlag::NoDepthTest:
        return "NoDepthTest";
    case MdxShadingFlag::NoDepthSet:
        return "NoDepthSet";
    case MdxShadingFlag::Unlit:
        return "Unlit";
    default:
        return "?";
    }
}

/// Mirror of `whiteout::mdx::Layer::ShaderType`.
enum class MdxShaderType : u32 {
    SD = 0,
    HD = 1,
    SDOnHD = 2,
    Terrain = 3,
    Water = 4,
    Fog = 5,
    Foliage = 6,
    FoliagePush = 7,
    Sprite = 8,
    DebugTexture = 9,
    DepthOfField = 10,
    BloomCombine = 11,
    BloomExtract = 12,
    GaussianBlur = 13,
    Tonemap = 14,
    Movie = 15,
    FFXCMAAEdge0 = 16,
    FFXCMAAEdge1 = 17,
    FFXCMAAEdgeCombine = 18,
    FFXCMAAProcessAndApply = 19,
    PopcornFX = 20,
    ConeIndicator = 21,
    CliffBlightMiscTerrain = 22,
    Distortion = 23,
    Crystal = 24,
    Imgui = 25,
};

inline const char* ToString(MdxShaderType value) {
    switch (value) {
    case MdxShaderType::SD:
        return "SD";
    case MdxShaderType::HD:
        return "HD";
    case MdxShaderType::SDOnHD:
        return "SDOnHD";
    case MdxShaderType::Terrain:
        return "Terrain";
    case MdxShaderType::Water:
        return "Water";
    case MdxShaderType::Fog:
        return "Fog";
    case MdxShaderType::Foliage:
        return "Foliage";
    case MdxShaderType::FoliagePush:
        return "FoliagePush";
    case MdxShaderType::Sprite:
        return "Sprite";
    case MdxShaderType::DebugTexture:
        return "DebugTexture";
    case MdxShaderType::DepthOfField:
        return "DepthOfField";
    case MdxShaderType::BloomCombine:
        return "BloomCombine";
    case MdxShaderType::BloomExtract:
        return "BloomExtract";
    case MdxShaderType::GaussianBlur:
        return "GaussianBlur";
    case MdxShaderType::Tonemap:
        return "Tonemap";
    case MdxShaderType::Movie:
        return "Movie";
    case MdxShaderType::FFXCMAAEdge0:
        return "FFXCMAAEdge0";
    case MdxShaderType::FFXCMAAEdge1:
        return "FFXCMAAEdge1";
    case MdxShaderType::FFXCMAAEdgeCombine:
        return "FFXCMAAEdgeCombine";
    case MdxShaderType::FFXCMAAProcessAndApply:
        return "FFXCMAAProcessAndApply";
    case MdxShaderType::PopcornFX:
        return "PopcornFX";
    case MdxShaderType::ConeIndicator:
        return "ConeIndicator";
    case MdxShaderType::CliffBlightMiscTerrain:
        return "CliffBlightMiscTerrain";
    case MdxShaderType::Distortion:
        return "Distortion";
    case MdxShaderType::Crystal:
        return "Crystal";
    case MdxShaderType::Imgui:
        return "Imgui";
    default:
        return "?";
    }
}

/// Mirror of `whiteout::mdx::Layer::SlotType`.
enum class MdxSlotType : u32 {
    DiffuseMap = 0,
    NormalMap = 1,
    ORMMap = 2,
    EmissiveMap = 3,
    TeamColor = 4,
    EnvironmentMap = 5,
    Unknown = 6,
};

inline const char* ToString(MdxSlotType value) {
    switch (value) {
    case MdxSlotType::DiffuseMap:
        return "DiffuseMap";
    case MdxSlotType::NormalMap:
        return "NormalMap";
    case MdxSlotType::ORMMap:
        return "ORMMap";
    case MdxSlotType::EmissiveMap:
        return "EmissiveMap";
    case MdxSlotType::TeamColor:
        return "TeamColor";
    case MdxSlotType::EnvironmentMap:
        return "EnvironmentMap";
    case MdxSlotType::Unknown:
        return "Unknown";
    default:
        return "?";
    }
}

/// Sub-texture definition (Reforged multi-texture)
struct MdxSubTexture {
    /// Index into texture array
    u32 textureId{};
    /// Texture slot number
    MdxSlotType slot{};

    template <class V>
    void reflect(V& v) {
        v.field("textureId", textureId);
        v.field("slot", slot);
    }
};

/// Material rendering layer
///
/// Materials can have multiple layers, each with its own texture and blending mode.
/// Layers control how textures are combined and rendered.
struct MdxLayer {
    /// Blending mode
    MdxFilterMode filterMode{};
    /// Rendering flags
    MdxShadingFlag shadingFlags{};
    /// Texture index (versions 800-1100)
    u32 textureId{};
    /// Texture animation index
    u32 textureAnimationId{};
    /// Texture coordinate set index
    u32 coordId{};
    /// Layer opacity
    f32 alpha{};
    /// Emissive light intensity (default 1.0)
    f32 emissiveGain{};
    /// Fresnel effect color
    Vector3f fresnelColor{};
    /// Fresnel effect opacity
    f32 fresnelOpacity{};
    /// Fresnel team color factor
    f32 fresnelTeamColor{};
    /// Shader to use for this layer
    MdxShaderType shaderType{};
    /// True if using Reforged HD shading
    bool isHd = false;
    /// Multi-texture support (version 1200+)
    std::vector<MdxSubTexture> subTextures;

    template <class V>
    void reflect(V& v) {
        v.field("filterMode", filterMode);
        v.field("shadingFlags", shadingFlags);
        v.field("textureId", textureId);
        v.field("textureAnimationId", textureAnimationId);
        v.field("coordId", coordId);
        v.field("alpha", alpha);
        v.field("emissiveGain", emissiveGain);
        v.field("fresnelColor", fresnelColor);
        v.field("fresnelOpacity", fresnelOpacity);
        v.field("fresnelTeamColor", fresnelTeamColor);
        v.field("shaderType", shaderType);
        v.field("isHd", isHd);
        v.inlineList("subTextures", subTextures);
    }
};

/// Material definition with rendering properties
///
/// Materials define how surfaces are rendered. Each material contains one or more
/// layers that specify textures and blending modes.
struct MdxMaterial {
    /// The format version this record was read from. No parser struct
    /// carries it, and a converter cannot read the record without it.
    u32 sourceVersion{};

    /// Rendering priority (higher = render last); signed
    i32 priorityPlane{};
    /// Material flags
    MdxMaterialFlag flags{};
    /// Shader name (Reforged)
    std::string shader;
    /// Rendering layers
    std::vector<MdxLayer> layers;

    template <class V>
    void reflect(V& v) {
        v.field("sourceVersion", sourceVersion);
        v.field("priorityPlane", priorityPlane);
        v.field("flags", flags);
        v.field("shader", shader);
        v.inlineList("layers", layers);
    }
};

/// Fields carrying `@wem manual`: mirrored, but the copy halves leave them
/// to the converter. Named here so a field newly added to a parser header
/// cannot end up silently half-copied — it either copies, or a test names it.
inline constexpr const char* const* kMdxManualFields = nullptr;
inline constexpr std::size_t kMdxManualFieldCount = 0;

} // namespace native

// Chunk identity for the mirrors that are chunks of their own. A mirror
// with no tag here is inline data inside its parent's chunk.
template <>
struct ChunkTagTraits<native::MdxMaterial> {
    static constexpr u32 value = kTag("NMDX");
    static constexpr u32 max_version = 1;
    static constexpr bool is_trivial = false;
};

} // namespace wem
} // namespace models
} // namespace whiteout
