// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.mdx;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.mdx.internal.Native;

/**
 * Collision volume for physics
 * 
 * Collision shapes define simplified geometry for collision detection.
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * CollisionShape allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (CollisionShape obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class CollisionShape implements AutoCloseable {
    private static final long BYTES = 312L;

    final MemorySegment handle;
    final boolean owned;

    CollisionShape(MemorySegment seg, boolean owned) {
        this.handle = (seg == null || seg.equals(MemorySegment.NULL))
            ? seg : seg.reinterpret(BYTES);
        this.owned = owned;
    }

    public CollisionShape() {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_mdx_MdxCollisionShape_new.invoke();
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("CollisionShape allocation failed");
            this.handle = __raw.reinterpret(BYTES);
            this.owned = true;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                Native.whiteout_mdx_MdxCollisionShape_delete.invoke(handle);
            } catch (Throwable __ex) { throw new RuntimeException(__ex); }
        }
    }

    /**
     * Base node data
     * @return the node field of this MdxCollisionShape.
     */
    public Node getNode() {
        return new Node(handle.asSlice(0L, 272L), false);
    }
    public void setNode(Node value) {
        try { Native.whiteout_mdx_MdxCollisionShape_set_node.invoke(handle, value == null ? MemorySegment.NULL : value.handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Shape type
     * @return the type field of this MdxCollisionShape.
     */
    public CollisionShapeShapeType getType() {
        return CollisionShapeShapeType.fromInt(handle.get(ValueLayout.JAVA_INT, 272L));
    }
    public void setType(CollisionShapeShapeType value) {
        handle.set(ValueLayout.JAVA_INT, 272L, value.value);
    }
    /**
     * Shape vertices (box only)
     * @return the vertices field of this MdxCollisionShape.
     */
    public int getVerticesCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxCollisionShape_get_vertices_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public float[] getVertices() {
        try {
            long __count = (long) Native.whiteout_mdx_MdxCollisionShape_get_vertices_count.invoke(handle);
            MemorySegment __ptr = (MemorySegment) Native.whiteout_mdx_MdxCollisionShape_get_vertices_data.invoke(handle);
            if (__count == 0 || __ptr == null || __ptr.equals(MemorySegment.NULL)) return new float[0];
            long __scalars = __count * 3L;
            return __ptr.reinterpret(__scalars * 4L).toArray(ValueLayout.JAVA_FLOAT);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setVertices(float[] values) {
        try (Arena arena = Arena.ofConfined()) {
            long __count = (long) values.length / 3;
            MemorySegment __seg = arena.allocate((long) values.length * 4L);
            if (values.length > 0) MemorySegment.copy(values, 0, __seg, ValueLayout.JAVA_FLOAT, 0, values.length);
            Native.whiteout_mdx_MdxCollisionShape_assign_vertices.invoke(handle, __seg, __count);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeVertices(int count) {
        try { Native.whiteout_mdx_MdxCollisionShape_resize_vertices.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Radius (sphere/cylinder only)
     * @return the radius field of this MdxCollisionShape.
     */
    public float getRadius() {
        return handle.get(ValueLayout.JAVA_FLOAT, 304L);
    }
    public void setRadius(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 304L, value);
    }
    @Override public String toString() {
        return "CollisionShape(" + "type=" + getType() + ", " + "radius=" + getRadius() + ")";
    }

}
