// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.mdx;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.mdx.internal.Native;

/**
 * Complete MDX model file structure
 * 
 * This structure represents an entire MDX model, including all geometry, materials, animations, and metadata. It can represent models from Warcraft III Classic (version 800) through Reforged (version 1200).
 * 
 * The structure is organized into chunks, each containing a specific type of data. Not all chunks are required - optional chunks can have empty vectors.
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * Model allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (Model obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class Model implements AutoCloseable {
    private static final long BYTES = 656L;

    final MemorySegment handle;
    final boolean owned;

    Model(MemorySegment seg, boolean owned) {
        this.handle = (seg == null || seg.equals(MemorySegment.NULL))
            ? seg : seg.reinterpret(BYTES);
        this.owned = owned;
    }

    public Model() {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_mdx_MdxModel_new.invoke();
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("Model allocation failed");
            this.handle = __raw.reinterpret(BYTES);
            this.owned = true;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                Native.whiteout_mdx_MdxModel_delete.invoke(handle);
            } catch (Throwable __ex) { throw new RuntimeException(__ex); }
        }
    }

    /**
     * MDX version: 800 (Classic), 900, 1000, 1100, 1200 (Reforged)
     * @return the version field of this MdxModel.
     */
    public int getVersion() {
        return handle.get(ValueLayout.JAVA_INT, 0L);
    }
    public void setVersion(int value) {
        handle.set(ValueLayout.JAVA_INT, 0L, value);
    }
    /**
     * Name of the model
     * @return the modelName field of this MdxModel.
     */
    public String getModelName() {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment __s = (MemorySegment) Native.whiteout_mdx_MdxModel_get_modelName.invoke(arena, handle);
            MemorySegment __chars = __s.get(ValueLayout.ADDRESS, 0);
            long __len = __s.get(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS.byteSize());
            if (__chars == null || __chars.equals(MemorySegment.NULL)) return "";
            byte[] __bytes = __chars.reinterpret(__len).toArray(ValueLayout.JAVA_BYTE);
            Native.whiteout_CString_free.invoke(__s);
            return new String(__bytes, StandardCharsets.UTF_8);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setModelName(String value) {
        try (Arena arena = Arena.ofConfined()) {
            byte[] __utf = value == null ? new byte[0] : value.getBytes(StandardCharsets.UTF_8);
            MemorySegment __seg = arena.allocate(__utf.length + 1);
            MemorySegment.copy(__utf, 0, __seg, ValueLayout.JAVA_BYTE, 0, __utf.length);
            __seg.set(ValueLayout.JAVA_BYTE, __utf.length, (byte) 0);
            Native.whiteout_mdx_MdxModel_set_modelName.invoke(handle, __seg);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Path to external animation file (rarely used)
     * @return the animationFileName field of this MdxModel.
     */
    public String getAnimationFileName() {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment __s = (MemorySegment) Native.whiteout_mdx_MdxModel_get_animationFileName.invoke(arena, handle);
            MemorySegment __chars = __s.get(ValueLayout.ADDRESS, 0);
            long __len = __s.get(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS.byteSize());
            if (__chars == null || __chars.equals(MemorySegment.NULL)) return "";
            byte[] __bytes = __chars.reinterpret(__len).toArray(ValueLayout.JAVA_BYTE);
            Native.whiteout_CString_free.invoke(__s);
            return new String(__bytes, StandardCharsets.UTF_8);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setAnimationFileName(String value) {
        try (Arena arena = Arena.ofConfined()) {
            byte[] __utf = value == null ? new byte[0] : value.getBytes(StandardCharsets.UTF_8);
            MemorySegment __seg = arena.allocate(__utf.length + 1);
            MemorySegment.copy(__utf, 0, __seg, ValueLayout.JAVA_BYTE, 0, __utf.length);
            __seg.set(ValueLayout.JAVA_BYTE, __utf.length, (byte) 0);
            Native.whiteout_mdx_MdxModel_set_animationFileName.invoke(handle, __seg);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Bounding volume for the entire model
     * @return the modelExtent field of this MdxModel.
     */
    public Extent getModelExtent() {
        return new Extent(handle.asSlice(72L, 28L), false);
    }
    public void setModelExtent(Extent value) {
        if (value == null) {
            try { Native.whiteout_mdx_MdxModel_set_modelExtent.invoke(handle, MemorySegment.NULL); }
            catch (Throwable __ex) { throw new RuntimeException(__ex); }
            return;
        }
        MemorySegment.copy(value.handle, 0L, handle, 72L, 28L);
    }
    /**
     * Time in milliseconds to blend between animations
     * @return the blendTime field of this MdxModel.
     */
    public int getBlendTime() {
        return handle.get(ValueLayout.JAVA_INT, 100L);
    }
    public void setBlendTime(int value) {
        handle.set(ValueLayout.JAVA_INT, 100L, value);
    }
    /**
     * Global looping animation durations
     * @return the globalSequences field of this MdxModel.
     */
    public int getGlobalSequencesCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_globalSequences_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public int[] getGlobalSequences() {
        try {
            long __count = (long) Native.whiteout_mdx_MdxModel_get_globalSequences_count.invoke(handle);
            MemorySegment __ptr = (MemorySegment) Native.whiteout_mdx_MdxModel_get_globalSequences_data.invoke(handle);
            if (__count == 0 || __ptr == null || __ptr.equals(MemorySegment.NULL)) return new int[0];
            long __scalars = __count * 1L;
            return __ptr.reinterpret(__scalars * 4L).toArray(ValueLayout.JAVA_INT);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setGlobalSequences(int[] values) {
        try (Arena arena = Arena.ofConfined()) {
            long __count = (long) values.length / 1;
            MemorySegment __seg = arena.allocate((long) values.length * 4L);
            if (values.length > 0) MemorySegment.copy(values, 0, __seg, ValueLayout.JAVA_INT, 0, values.length);
            Native.whiteout_mdx_MdxModel_assign_globalSequences.invoke(handle, __seg, __count);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeGlobalSequences(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_globalSequences.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Named animation sequences
     * @return the sequences field of this MdxModel.
     */
    public int getSequencesCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_sequences_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public Sequence getSequencesAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_sequences_at.invoke(handle, (long) index);
            return new Sequence(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeSequences(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_sequences.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<Sequence> sequencesView() {
        return new java.util.AbstractList<Sequence>() {
            @Override public int size() { return getSequencesCount(); }
            @Override public Sequence get(int index) { return getSequencesAt(index); }
        };
    }
    /**
     * Texture paths and settings
     * @return the textures field of this MdxModel.
     */
    public int getTexturesCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_textures_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public Texture getTexturesAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_textures_at.invoke(handle, (long) index);
            return new Texture(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeTextures(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_textures.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<Texture> texturesView() {
        return new java.util.AbstractList<Texture>() {
            @Override public int size() { return getTexturesCount(); }
            @Override public Texture get(int index) { return getTexturesAt(index); }
        };
    }
    /**
     * Sounds (deprecated)
     * @return the sounds field of this MdxModel.
     */
    public int getSoundsCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_sounds_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public Sound getSoundsAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_sounds_at.invoke(handle, (long) index);
            return new Sound(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeSounds(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_sounds.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<Sound> soundsView() {
        return new java.util.AbstractList<Sound>() {
            @Override public int size() { return getSoundsCount(); }
            @Override public Sound get(int index) { return getSoundsAt(index); }
        };
    }
    /**
     * Sound emitters (deprecated)
     * @return the soundEmitters field of this MdxModel.
     */
    public int getSoundEmittersCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_soundEmitters_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public SoundEmitter getSoundEmittersAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_soundEmitters_at.invoke(handle, (long) index);
            return new SoundEmitter(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeSoundEmitters(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_soundEmitters.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<SoundEmitter> soundEmittersView() {
        return new java.util.AbstractList<SoundEmitter>() {
            @Override public int size() { return getSoundEmittersCount(); }
            @Override public SoundEmitter get(int index) { return getSoundEmittersAt(index); }
        };
    }
    /**
     * Material definitions
     * @return the materials field of this MdxModel.
     */
    public int getMaterialsCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_materials_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public Material getMaterialsAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_materials_at.invoke(handle, (long) index);
            return new Material(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeMaterials(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_materials.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<Material> materialsView() {
        return new java.util.AbstractList<Material>() {
            @Override public int size() { return getMaterialsCount(); }
            @Override public Material get(int index) { return getMaterialsAt(index); }
        };
    }
    /**
     * UV animation data
     * @return the textureAnimations field of this MdxModel.
     */
    public int getTextureAnimationsCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_textureAnimations_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public TextureAnimation getTextureAnimationsAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_textureAnimations_at.invoke(handle, (long) index);
            return new TextureAnimation(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeTextureAnimations(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_textureAnimations.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<TextureAnimation> textureAnimationsView() {
        return new java.util.AbstractList<TextureAnimation>() {
            @Override public int size() { return getTextureAnimationsCount(); }
            @Override public TextureAnimation get(int index) { return getTextureAnimationsAt(index); }
        };
    }
    /**
     * Mesh geometry
     * @return the geosets field of this MdxModel.
     */
    public int getGeosetsCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_geosets_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public Geoset getGeosetsAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_geosets_at.invoke(handle, (long) index);
            return new Geoset(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeGeosets(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_geosets.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<Geoset> geosetsView() {
        return new java.util.AbstractList<Geoset>() {
            @Override public int size() { return getGeosetsCount(); }
            @Override public Geoset get(int index) { return getGeosetsAt(index); }
        };
    }
    /**
     * Mesh visibility/color animation
     * @return the geosetAnimations field of this MdxModel.
     */
    public int getGeosetAnimationsCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_geosetAnimations_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public GeosetAnimation getGeosetAnimationsAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_geosetAnimations_at.invoke(handle, (long) index);
            return new GeosetAnimation(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeGeosetAnimations(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_geosetAnimations.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<GeosetAnimation> geosetAnimationsView() {
        return new java.util.AbstractList<GeosetAnimation>() {
            @Override public int size() { return getGeosetAnimationsCount(); }
            @Override public GeosetAnimation get(int index) { return getGeosetAnimationsAt(index); }
        };
    }
    /**
     * Skeleton bones
     * @return the bones field of this MdxModel.
     */
    public int getBonesCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_bones_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public Bone getBonesAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_bones_at.invoke(handle, (long) index);
            return new Bone(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeBones(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_bones.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<Bone> bonesView() {
        return new java.util.AbstractList<Bone>() {
            @Override public int size() { return getBonesCount(); }
            @Override public Bone get(int index) { return getBonesAt(index); }
        };
    }
    /**
     * Helper/attachment nodes
     * @return the helpers field of this MdxModel.
     */
    public int getHelpersCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_helpers_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public Helper getHelpersAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_helpers_at.invoke(handle, (long) index);
            return new Helper(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeHelpers(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_helpers.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<Helper> helpersView() {
        return new java.util.AbstractList<Helper>() {
            @Override public int size() { return getHelpersCount(); }
            @Override public Helper get(int index) { return getHelpersAt(index); }
        };
    }
    /**
     * Equipment attachment points
     * @return the attachments field of this MdxModel.
     */
    public int getAttachmentsCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_attachments_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public Attachment getAttachmentsAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_attachments_at.invoke(handle, (long) index);
            return new Attachment(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeAttachments(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_attachments.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<Attachment> attachmentsView() {
        return new java.util.AbstractList<Attachment>() {
            @Override public int size() { return getAttachmentsCount(); }
            @Override public Attachment get(int index) { return getAttachmentsAt(index); }
        };
    }
    /**
     * Pivot points for nodes
     * @return the pivotPoints field of this MdxModel.
     */
    public int getPivotPointsCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_pivotPoints_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public float[] getPivotPoints() {
        try {
            long __count = (long) Native.whiteout_mdx_MdxModel_get_pivotPoints_count.invoke(handle);
            MemorySegment __ptr = (MemorySegment) Native.whiteout_mdx_MdxModel_get_pivotPoints_data.invoke(handle);
            if (__count == 0 || __ptr == null || __ptr.equals(MemorySegment.NULL)) return new float[0];
            long __scalars = __count * 3L;
            return __ptr.reinterpret(__scalars * 4L).toArray(ValueLayout.JAVA_FLOAT);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setPivotPoints(float[] values) {
        try (Arena arena = Arena.ofConfined()) {
            long __count = (long) values.length / 3;
            MemorySegment __seg = arena.allocate((long) values.length * 4L);
            if (values.length > 0) MemorySegment.copy(values, 0, __seg, ValueLayout.JAVA_FLOAT, 0, values.length);
            Native.whiteout_mdx_MdxModel_assign_pivotPoints.invoke(handle, __seg, __count);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizePivotPoints(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_pivotPoints.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Light sources
     * @return the lights field of this MdxModel.
     */
    public int getLightsCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_lights_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public Light getLightsAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_lights_at.invoke(handle, (long) index);
            return new Light(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeLights(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_lights.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<Light> lightsView() {
        return new java.util.AbstractList<Light>() {
            @Override public int size() { return getLightsCount(); }
            @Override public Light get(int index) { return getLightsAt(index); }
        };
    }
    /**
     * Particle emitters v1
     * @return the particleEmitters field of this MdxModel.
     */
    public int getParticleEmittersCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_particleEmitters_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public ParticleEmitter getParticleEmittersAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_particleEmitters_at.invoke(handle, (long) index);
            return new ParticleEmitter(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeParticleEmitters(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_particleEmitters.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<ParticleEmitter> particleEmittersView() {
        return new java.util.AbstractList<ParticleEmitter>() {
            @Override public int size() { return getParticleEmittersCount(); }
            @Override public ParticleEmitter get(int index) { return getParticleEmittersAt(index); }
        };
    }
    /**
     * Particle emitters v2
     * @return the particleEmitters2 field of this MdxModel.
     */
    public int getParticleEmitters2Count() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_particleEmitters2_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public ParticleEmitter2 getParticleEmitters2At(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_particleEmitters2_at.invoke(handle, (long) index);
            return new ParticleEmitter2(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeParticleEmitters2(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_particleEmitters2.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<ParticleEmitter2> particleEmitters2View() {
        return new java.util.AbstractList<ParticleEmitter2>() {
            @Override public int size() { return getParticleEmitters2Count(); }
            @Override public ParticleEmitter2 get(int index) { return getParticleEmitters2At(index); }
        };
    }
    /**
     * Ribbon trail effects
     * @return the ribbonEmitters field of this MdxModel.
     */
    public int getRibbonEmittersCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_ribbonEmitters_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public RibbonEmitter getRibbonEmittersAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_ribbonEmitters_at.invoke(handle, (long) index);
            return new RibbonEmitter(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeRibbonEmitters(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_ribbonEmitters.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<RibbonEmitter> ribbonEmittersView() {
        return new java.util.AbstractList<RibbonEmitter>() {
            @Override public int size() { return getRibbonEmittersCount(); }
            @Override public RibbonEmitter get(int index) { return getRibbonEmittersAt(index); }
        };
    }
    /**
     * PopcornFX emitters (Reforged)
     * @return the cornEmitters field of this MdxModel.
     */
    public int getCornEmittersCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_cornEmitters_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public CornEmitter getCornEmittersAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_cornEmitters_at.invoke(handle, (long) index);
            return new CornEmitter(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeCornEmitters(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_cornEmitters.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<CornEmitter> cornEmittersView() {
        return new java.util.AbstractList<CornEmitter>() {
            @Override public int size() { return getCornEmittersCount(); }
            @Override public CornEmitter get(int index) { return getCornEmittersAt(index); }
        };
    }
    /**
     * Animation event triggers
     * @return the eventObjects field of this MdxModel.
     */
    public int getEventObjectsCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_eventObjects_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public EventObject getEventObjectsAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_eventObjects_at.invoke(handle, (long) index);
            return new EventObject(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeEventObjects(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_eventObjects.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<EventObject> eventObjectsView() {
        return new java.util.AbstractList<EventObject>() {
            @Override public int size() { return getEventObjectsCount(); }
            @Override public EventObject get(int index) { return getEventObjectsAt(index); }
        };
    }
    /**
     * Camera definitions
     * @return the cameras field of this MdxModel.
     */
    public int getCamerasCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_cameras_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public Camera getCamerasAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_cameras_at.invoke(handle, (long) index);
            return new Camera(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeCameras(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_cameras.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<Camera> camerasView() {
        return new java.util.AbstractList<Camera>() {
            @Override public int size() { return getCamerasCount(); }
            @Override public Camera get(int index) { return getCamerasAt(index); }
        };
    }
    /**
     * Collision geometry
     * @return the collisionShapes field of this MdxModel.
     */
    public int getCollisionShapesCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_collisionShapes_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public CollisionShape getCollisionShapesAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_collisionShapes_at.invoke(handle, (long) index);
            return new CollisionShape(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeCollisionShapes(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_collisionShapes.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<CollisionShape> collisionShapesView() {
        return new java.util.AbstractList<CollisionShape>() {
            @Override public int size() { return getCollisionShapesCount(); }
            @Override public CollisionShape get(int index) { return getCollisionShapesAt(index); }
        };
    }
    /**
     * Facial effects (Reforged)
     * @return the faceEffects field of this MdxModel.
     */
    public int getFaceEffectsCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxModel_get_faceEffects_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public FaceEffect getFaceEffectsAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxModel_get_faceEffects_at.invoke(handle, (long) index);
            return new FaceEffect(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeFaceEffects(int count) {
        try { Native.whiteout_mdx_MdxModel_resize_faceEffects.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<FaceEffect> faceEffectsView() {
        return new java.util.AbstractList<FaceEffect>() {
            @Override public int size() { return getFaceEffectsCount(); }
            @Override public FaceEffect get(int index) { return getFaceEffectsAt(index); }
        };
    }
    @Override public String toString() {
        return "Model(" + "version=" + getVersion() + ", " + "modelName=" + getModelName() + ", " + "animationFileName=" + getAnimationFileName() + ", " + "blendTime=" + getBlendTime() + ")";
    }

}
