// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.mdx;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.mdx.internal.Native;

/**
 * Parser for MDX model files
 * 
 * The Parser reads binary MDX files and converts them into the Model structure. It supports multiple parsing modes and can handle version differences.
 * 
 * Uses the PImpl (Pointer to Implementation) idiom to hide implementation details.
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * Parser allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (Parser obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class Parser implements AutoCloseable {
    private static final long BYTES = 8L;

    final MemorySegment handle;
    final boolean owned;

    Parser(MemorySegment seg, boolean owned) {
        this.handle = (seg == null || seg.equals(MemorySegment.NULL))
            ? seg : seg.reinterpret(BYTES);
        this.owned = owned;
    }

    public Parser() {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_mdx_MdxParser_new.invoke();
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("Parser allocation failed");
            this.handle = __raw.reinterpret(BYTES);
            this.owned = true;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    public static Parser createParseModeUpgradeMode(ParseMode parseMode, UpgradeMode upgradeMode) {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_mdx_MdxParser_new_parseMode_upgradeMode.invoke(parseMode.value, upgradeMode.value);
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("Parser allocation failed");
            return new Parser(__raw, true);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                Native.whiteout_mdx_MdxParser_delete.invoke(handle);
            } catch (Throwable __ex) { throw new RuntimeException(__ex); }
        }
    }

    /**
     * Parse an MDX file from disk
     * 
     * The format is detected from the file extension: `.mdl` for text MDL format, `.mdx` (or any other extension) for binary MDX format.
     * 
     * @param filePath Path to the MDX/MDL file @return Parsed MDX file data @throws std::runtime_error If file cannot be opened or parsing fails in strict mode
     */
    public Model parse(String filePath) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment filePath_seg = filePath == null
                ? MemorySegment.NULL
                : arena.allocateFrom(filePath, StandardCharsets.UTF_8);
            MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxParser_parse.invoke(handle, filePath_seg);
            return new Model(__h, true);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    /**
     * Parse an MDX/MDL file from memory buffer @param buffer Memory buffer containing MDX/MDL data @param format Source format (MDX binary or MDL text) @return Parsed MDX file data @throws std::runtime_error If parsing fails in strict mode
     *
     * @param buffer byte[] input.
     * @param format MDLXFormat input.
     */
    public Model parse(byte[] buffer, MDLXFormat format) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment buffer_seg = arena.allocate(buffer.length * 1L);
            MemorySegment.copy(buffer, 0, buffer_seg, ValueLayout.JAVA_BYTE, 0, buffer.length);
            MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxParser_parse_buffer_format.invoke(handle, buffer_seg, (long) buffer.length, format.value);
            return new Model(__h, true);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    /**
     * Check if parsing encountered any issues @return True if there were warnings or recoverable errors
     */
    public boolean hasIssues() {
        try {
        return ((int) Native.whiteout_mdx_MdxParser_hasIssues.invoke(handle)) != 0;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override public String toString() {
        return "Parser@" + Long.toHexString(handle == null ? 0 : handle.address());
    }

}
