// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.mdx;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.mdx.internal.Native;

/**
 * Particle emitter version 1 (uses external model)
 * 
 * Legacy particle emitter that spawns copies of an external model file. Used for effects like footprints, blood splatter, etc.
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * ParticleEmitter allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (ParticleEmitter obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class ParticleEmitter implements AutoCloseable {
    private static final long BYTES = 832L;

    final MemorySegment handle;
    final boolean owned;

    ParticleEmitter(MemorySegment seg, boolean owned) {
        this.handle = (seg == null || seg.equals(MemorySegment.NULL))
            ? seg : seg.reinterpret(BYTES);
        this.owned = owned;
    }

    public ParticleEmitter() {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_mdx_MdxParticleEmitter_new.invoke();
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("ParticleEmitter allocation failed");
            this.handle = __raw.reinterpret(BYTES);
            this.owned = true;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                Native.whiteout_mdx_MdxParticleEmitter_delete.invoke(handle);
            } catch (Throwable __ex) { throw new RuntimeException(__ex); }
        }
    }

    /**
     * Base node data
     * @return the node field of this MdxParticleEmitter.
     */
    public Node getNode() {
        return new Node(handle.asSlice(0L, 272L), false);
    }
    public void setNode(Node value) {
        try { Native.whiteout_mdx_MdxParticleEmitter_set_node.invoke(handle, value == null ? MemorySegment.NULL : value.handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Particles per second
     * @return the emissionRate field of this MdxParticleEmitter.
     */
    public float getEmissionRate() {
        return handle.get(ValueLayout.JAVA_FLOAT, 272L);
    }
    public void setEmissionRate(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 272L, value);
    }
    /**
     * Gravity force
     * @return the gravity field of this MdxParticleEmitter.
     */
    public float getGravity() {
        return handle.get(ValueLayout.JAVA_FLOAT, 276L);
    }
    public void setGravity(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 276L, value);
    }
    /**
     * Emission longitude angle
     * @return the longitude field of this MdxParticleEmitter.
     */
    public float getLongitude() {
        return handle.get(ValueLayout.JAVA_FLOAT, 280L);
    }
    public void setLongitude(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 280L, value);
    }
    /**
     * Emission latitude angle
     * @return the latitude field of this MdxParticleEmitter.
     */
    public float getLatitude() {
        return handle.get(ValueLayout.JAVA_FLOAT, 284L);
    }
    public void setLatitude(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 284L, value);
    }
    /**
     * Model to spawn as particles
     * @return the spawnModelFileName field of this MdxParticleEmitter.
     */
    public String getSpawnModelFileName() {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment __s = (MemorySegment) Native.whiteout_mdx_MdxParticleEmitter_get_spawnModelFileName.invoke(arena, handle);
            MemorySegment __chars = __s.get(ValueLayout.ADDRESS, 0);
            long __len = __s.get(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS.byteSize());
            if (__chars == null || __chars.equals(MemorySegment.NULL)) return "";
            byte[] __bytes = __chars.reinterpret(__len).toArray(ValueLayout.JAVA_BYTE);
            Native.whiteout_CString_free.invoke(__s);
            return new String(__bytes, StandardCharsets.UTF_8);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setSpawnModelFileName(String value) {
        try (Arena arena = Arena.ofConfined()) {
            byte[] __utf = value == null ? new byte[0] : value.getBytes(StandardCharsets.UTF_8);
            MemorySegment __seg = arena.allocate(__utf.length + 1);
            MemorySegment.copy(__utf, 0, __seg, ValueLayout.JAVA_BYTE, 0, __utf.length);
            __seg.set(ValueLayout.JAVA_BYTE, __utf.length, (byte) 0);
            Native.whiteout_mdx_MdxParticleEmitter_set_spawnModelFileName.invoke(handle, __seg);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Particle lifetime in seconds
     * @return the lifespan field of this MdxParticleEmitter.
     */
    public float getLifespan() {
        return handle.get(ValueLayout.JAVA_FLOAT, 320L);
    }
    public void setLifespan(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 320L, value);
    }
    /**
     * Initial particle speed
     * @return the initialVelocity field of this MdxParticleEmitter.
     */
    public float getInitialVelocity() {
        return handle.get(ValueLayout.JAVA_FLOAT, 324L);
    }
    public void setInitialVelocity(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 324L, value);
    }
    /**
     * Emission rate animation
     * @return the emissionRateTracks field of this MdxParticleEmitter.
     */
    public TrackF32 getEmissionRateTracks() {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxParticleEmitter_get_emissionRateTracks.invoke(handle);
            return new TrackF32(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setEmissionRateTracks(TrackF32 value) {
        try { Native.whiteout_mdx_MdxParticleEmitter_set_emissionRateTracks.invoke(handle, value == null ? MemorySegment.NULL : value.handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Gravity animation
     * @return the gravityTracks field of this MdxParticleEmitter.
     */
    public TrackF32 getGravityTracks() {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxParticleEmitter_get_gravityTracks.invoke(handle);
            return new TrackF32(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setGravityTracks(TrackF32 value) {
        try { Native.whiteout_mdx_MdxParticleEmitter_set_gravityTracks.invoke(handle, value == null ? MemorySegment.NULL : value.handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Longitude animation
     * @return the longitudeTracks field of this MdxParticleEmitter.
     */
    public TrackF32 getLongitudeTracks() {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxParticleEmitter_get_longitudeTracks.invoke(handle);
            return new TrackF32(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setLongitudeTracks(TrackF32 value) {
        try { Native.whiteout_mdx_MdxParticleEmitter_set_longitudeTracks.invoke(handle, value == null ? MemorySegment.NULL : value.handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Latitude animation
     * @return the latitudeTracks field of this MdxParticleEmitter.
     */
    public TrackF32 getLatitudeTracks() {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxParticleEmitter_get_latitudeTracks.invoke(handle);
            return new TrackF32(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setLatitudeTracks(TrackF32 value) {
        try { Native.whiteout_mdx_MdxParticleEmitter_set_latitudeTracks.invoke(handle, value == null ? MemorySegment.NULL : value.handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Lifespan animation
     * @return the lifespanTracks field of this MdxParticleEmitter.
     */
    public TrackF32 getLifespanTracks() {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxParticleEmitter_get_lifespanTracks.invoke(handle);
            return new TrackF32(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setLifespanTracks(TrackF32 value) {
        try { Native.whiteout_mdx_MdxParticleEmitter_set_lifespanTracks.invoke(handle, value == null ? MemorySegment.NULL : value.handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Speed animation
     * @return the speedTracks field of this MdxParticleEmitter.
     */
    public TrackF32 getSpeedTracks() {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxParticleEmitter_get_speedTracks.invoke(handle);
            return new TrackF32(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setSpeedTracks(TrackF32 value) {
        try { Native.whiteout_mdx_MdxParticleEmitter_set_speedTracks.invoke(handle, value == null ? MemorySegment.NULL : value.handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Visibility animation
     * @return the visibilityTracks field of this MdxParticleEmitter.
     */
    public TrackF32 getVisibilityTracks() {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_mdx_MdxParticleEmitter_get_visibilityTracks.invoke(handle);
            return new TrackF32(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setVisibilityTracks(TrackF32 value) {
        try { Native.whiteout_mdx_MdxParticleEmitter_set_visibilityTracks.invoke(handle, value == null ? MemorySegment.NULL : value.handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    @Override public String toString() {
        return "ParticleEmitter(" + "emissionRate=" + getEmissionRate() + ", " + "gravity=" + getGravity() + ", " + "longitude=" + getLongitude() + ", " + "latitude=" + getLatitude() + ", " + "spawnModelFileName=" + getSpawnModelFileName() + ", " + "lifespan=" + getLifespan() + ", " + "initialVelocity=" + getInitialVelocity() + ")";
    }

}
