// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.mdx;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.mdx.internal.Native;

/**
 * Generic animation track with keyframe data
 * 
 * Tracks store animation data as a series of keyframes. The interpolation type determines how values between keyframes are calculated.
 * 
 * @tparam T The value type (f32, Vector3f, Vector4f, u32, etc.)
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * Track<whiteout::Vector3f> allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (TrackVector3f obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class TrackVector3f implements AutoCloseable {
    final MemorySegment handle;
    final boolean owned;

    TrackVector3f(MemorySegment seg, boolean owned) {
        this.handle = seg;
        this.owned = owned;
    }

    public TrackVector3f() {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_mdx_MdxTrackVector3f_new.invoke();
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("TrackVector3f allocation failed");
            this.handle = __raw;
            this.owned = true;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                Native.whiteout_mdx_MdxTrackVector3f_delete.invoke(handle);
            } catch (Throwable __ex) { throw new RuntimeException(__ex); }
        }
    }

    /**
     * Whether this track contains animation data
     * @return the isUsed field of this MdxTrackVector3f.
     */
    public boolean getIsUsed() {
        try { return ((int) Native.whiteout_mdx_MdxTrackVector3f_get_isUsed.invoke(handle)) != 0; }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setIsUsed(boolean value) {
        try { Native.whiteout_mdx_MdxTrackVector3f_set_isUsed.invoke(handle, (value ? 1 : 0)); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Interpolation type
     * @return the interpolationType field of this MdxTrackVector3f.
     */
    public InterpolationType getInterpolationType() {
        try { return InterpolationType.fromInt((int) Native.whiteout_mdx_MdxTrackVector3f_get_interpolationType.invoke(handle)); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setInterpolationType(InterpolationType value) {
        try { Native.whiteout_mdx_MdxTrackVector3f_set_interpolationType.invoke(handle, value.value); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Global sequence ID if applicable
     * @return the globalSequenceId field of this MdxTrackVector3f.
     */
    public int getGlobalSequenceId() {
        try { return (int) Native.whiteout_mdx_MdxTrackVector3f_get_globalSequenceId.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setGlobalSequenceId(int value) {
        try { Native.whiteout_mdx_MdxTrackVector3f_set_globalSequenceId.invoke(handle, value); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Number of keyframes
     * @return the keyCount field of this MdxTrackVector3f.
     */
    public int getKeyCount() {
        try { return (int) Native.whiteout_mdx_MdxTrackVector3f_get_keyCount.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setKeyCount(int value) {
        try { Native.whiteout_mdx_MdxTrackVector3f_set_keyCount.invoke(handle, value); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Keyframe timestamps (in frames)
     * @return the timestamps field of this MdxTrackVector3f.
     */
    public int getTimestampsCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxTrackVector3f_get_timestamps_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public int[] getTimestamps() {
        try {
            long __count = (long) Native.whiteout_mdx_MdxTrackVector3f_get_timestamps_count.invoke(handle);
            MemorySegment __ptr = (MemorySegment) Native.whiteout_mdx_MdxTrackVector3f_get_timestamps_data.invoke(handle);
            if (__count == 0 || __ptr == null || __ptr.equals(MemorySegment.NULL)) return new int[0];
            long __scalars = __count * 1L;
            return __ptr.reinterpret(__scalars * 4L).toArray(ValueLayout.JAVA_INT);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setTimestamps(int[] values) {
        try (Arena arena = Arena.ofConfined()) {
            long __count = (long) values.length / 1;
            MemorySegment __seg = arena.allocate((long) values.length * 4L);
            if (values.length > 0) MemorySegment.copy(values, 0, __seg, ValueLayout.JAVA_INT, 0, values.length);
            Native.whiteout_mdx_MdxTrackVector3f_assign_timestamps.invoke(handle, __seg, __count);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeTimestamps(int count) {
        try { Native.whiteout_mdx_MdxTrackVector3f_resize_timestamps.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Raw keyframe data
     * @return the keys field of this MdxTrackVector3f.
     */
    public int getKeysCount() {
        try { return (int) (long) Native.whiteout_mdx_MdxTrackVector3f_get_keys_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public float[] getKeys() {
        try {
            long __count = (long) Native.whiteout_mdx_MdxTrackVector3f_get_keys_count.invoke(handle);
            MemorySegment __ptr = (MemorySegment) Native.whiteout_mdx_MdxTrackVector3f_get_keys_data.invoke(handle);
            if (__count == 0 || __ptr == null || __ptr.equals(MemorySegment.NULL)) return new float[0];
            long __scalars = __count * 3L;
            return __ptr.reinterpret(__scalars * 4L).toArray(ValueLayout.JAVA_FLOAT);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setKeys(float[] values) {
        try (Arena arena = Arena.ofConfined()) {
            long __count = (long) values.length / 3;
            MemorySegment __seg = arena.allocate((long) values.length * 4L);
            if (values.length > 0) MemorySegment.copy(values, 0, __seg, ValueLayout.JAVA_FLOAT, 0, values.length);
            Native.whiteout_mdx_MdxTrackVector3f_assign_keys.invoke(handle, __seg, __count);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeKeys(int count) {
        try { Native.whiteout_mdx_MdxTrackVector3f_resize_keys.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    @Override public String toString() {
        return "TrackVector3f(" + "isUsed=" + getIsUsed() + ", " + "interpolationType=" + getInterpolationType() + ", " + "globalSequenceId=" + getGlobalSequenceId() + ", " + "keyCount=" + getKeyCount() + ")";
    }

}
