// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Fernando Sahmkow
//
// AUTOGENERATED by tools/codegen — do not edit by hand.
// Regenerate via:  python -m tools.codegen.codegen wem --backend pybind11
//
// Source headers and `@bind` annotations live under include/whiteout/.
//
// Include order matters here:
//   1. pybind11/pybind11.h   sets up the base library
//   2. project headers       define whiteout::u32 et al used inside MAKE_OPAQUE
//   3. PYBIND11_MAKE_OPAQUE  opts out of stl.h's auto-conversion for our vectors
//   4. pybind11/stl.h, stl_bind.h   honor the opaque declarations

#include <pybind11/pybind11.h>

#include <array>
#include <cstdint>
#include <optional>
#include <sstream>
#include <string>
#include <vector>

#include <whiteout/vector_types.h>
#include <whiteout/models/wem/profile.h>
#include <whiteout/models/wem/diagnostics.h>
#include <whiteout/models/wem/bounds.h>
#include <whiteout/models/wem/asset_key.h>
#include <whiteout/models/wem/native_bag.h>
#include <whiteout/models/wem/materials/texture.h>
#include <whiteout/models/wem/materials/common.h>
#include <whiteout/models/wem/materials/features.h>
#include <whiteout/models/wem/materials/looks.h>
#include <whiteout/models/wem/materials/material.h>
#include <whiteout/models/wem/geometry/attributes.h>
#include <whiteout/models/wem/geometry/skin.h>
#include <whiteout/models/wem/geometry/mesh.h>
#include <whiteout/models/wem/nodes/emitters.h>
#include <whiteout/models/wem/nodes/node.h>
#include <whiteout/models/wem/nodes/tree.h>
#include <whiteout/models/wem/anim/channel.h>
#include <whiteout/models/wem/anim/clip.h>
#include <whiteout/models/wem/model.h>
#include <whiteout/models/wem/document.h>
#include <whiteout/models/wem/parser.h>
#include <whiteout/models/wem/writer.h>
#include <whiteout/models/wem/validate.h>
#include <whiteout/interfaces.h>

PYBIND11_MAKE_OPAQUE(std::vector<whiteout::f32>);
PYBIND11_MAKE_OPAQUE(std::vector<std::string>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::u8>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::u32>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::AnimChannel>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::AnimSet>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::AnimTag>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::AssetKey>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::Clip>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::ClipEvent>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::CombinerStage>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::CompositeLayer>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::Diagnostic>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::Diagnostics::CodeCount>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::Look>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::Material>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::MaterialFeature>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::Mesh>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::MeshSection>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::Model>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::NativeKind>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::Node>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::PoseSchema>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::ProfileId>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::ProfileMaterialSet>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::Sc2Property<whiteout::Vector3f>>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::Sc2RibbonSplinePoint>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::SlotBinding>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::SubTrack>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::SubTrackContainer>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::TextureRef>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::Transform>);
PYBIND11_MAKE_OPAQUE(std::vector<whiteout::models::wem::UnknownChunk>);

#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <pybind11/operators.h>
#include <pybind11/numpy.h>

namespace py = pybind11;

// Part 1 of bind_wem(), which calls the parts in order.
void bind_wem_1(py::module_& m) {
    py::class_<whiteout::models::wem::Wc3RibbonEmitterPayload>(m, "Wc3RibbonEmitterPayload", R"doc(`RIBB`: a strip swept between `heightAbove` and `heightBelow` of the node.

Its colour, alpha and flipbook cell key on the shared `Color`, `Alpha` and `TextureIndex` channels and rest here.)doc")
        .def(py::init<>())
        .def_readwrite("height_above", &whiteout::models::wem::Wc3RibbonEmitterPayload::heightAbove)
        .def_readwrite("height_below", &whiteout::models::wem::Wc3RibbonEmitterPayload::heightBelow)
        .def_readwrite("alpha", &whiteout::models::wem::Wc3RibbonEmitterPayload::alpha)
        .def_readwrite("color", &whiteout::models::wem::Wc3RibbonEmitterPayload::color, R"doc(RGB, red first.)doc")
        .def_readwrite("lifespan", &whiteout::models::wem::Wc3RibbonEmitterPayload::lifespan, R"doc(Seconds a segment lives.)doc")
        .def_readwrite("texture_slot", &whiteout::models::wem::Wc3RibbonEmitterPayload::textureSlot, R"doc(The flipbook cell.)doc")
        .def_readwrite("emission_rate", &whiteout::models::wem::Wc3RibbonEmitterPayload::emissionRate, R"doc(Segments a second.)doc")
        .def_readwrite("rows", &whiteout::models::wem::Wc3RibbonEmitterPayload::rows)
        .def_readwrite("columns", &whiteout::models::wem::Wc3RibbonEmitterPayload::columns)
        .def_readwrite("material_slot", &whiteout::models::wem::Wc3RibbonEmitterPayload::materialSlot, R"doc(-> `Model::materialSlots`.)doc")
        .def_readwrite("gravity", &whiteout::models::wem::Wc3RibbonEmitterPayload::gravity)
    ;

    py::class_<whiteout::models::wem::Wc3CornEmitterPayload>(m, "Wc3CornEmitterPayload", R"doc(`CORN`: a PopcornFX effect run at the node (Reforged).

The effect itself is a `.pkb` WEM does not hold, named by `effect`; what the model owns is the five numbers the game hands the effect every frame. They are MULTIPLIERS on the effect's own values (the game's reader names each track so: "lifespan multiplier keys", ...), which is why they rest at 1.

Its colour, alpha and visibility key on the shared `Color`, `Alpha` and `Visibility` channels and rest here; lifespan, emission rate and speed are `Wc3CornProperty` channels. A keyed colour is blue first in the file, like every other Warcraft III colour key (`ReadBinParticleEmitterPopcorn` keeps the keys as read and reverses only the static colour); the channel is RGB.)doc")
        .def(py::init<>())
        .def_readwrite("lifespan", &whiteout::models::wem::Wc3CornEmitterPayload::lifespan, R"doc(Multiplies the effect's particle lifespan.)doc")
        .def_readwrite("emission_rate", &whiteout::models::wem::Wc3CornEmitterPayload::emissionRate, R"doc(Multiplies its emission rate.)doc")
        .def_readwrite("speed", &whiteout::models::wem::Wc3CornEmitterPayload::speed, R"doc(Multiplies its particle speed.)doc")
        .def_readwrite("color", &whiteout::models::wem::Wc3CornEmitterPayload::color, R"doc(Multiplies its colour. RGB, red first.)doc")
        .def_readwrite("alpha", &whiteout::models::wem::Wc3CornEmitterPayload::alpha, R"doc(Multiplies its alpha.)doc")
        .def_readwrite("replaceable_id", &whiteout::models::wem::Wc3CornEmitterPayload::replaceableId, R"doc(The team colour/glow the effect's textures take.)doc")
        .def_readwrite("effect", &whiteout::models::wem::Wc3CornEmitterPayload::effect, R"doc(The PopcornFX effect, by path — a `.pkb`.)doc")
        .def_readwrite("anim_visibility_guide", &whiteout::models::wem::Wc3CornEmitterPayload::animVisibilityGuide, R"doc(The effect's animation-visibility guide, by name. Opaque here: the engine resolves it against the effect.)doc")
        .def_readwrite("unshaded", &whiteout::models::wem::Wc3CornEmitterPayload::unshaded, R"doc(0x8000.)doc")
        .def_readwrite("sort_prims_far_z", &whiteout::models::wem::Wc3CornEmitterPayload::sortPrimsFarZ, R"doc(0x10000.)doc")
        .def_readwrite("unfogged", &whiteout::models::wem::Wc3CornEmitterPayload::unfogged, R"doc(0x20000.)doc")
        .def_readwrite("popcorn_scaling", &whiteout::models::wem::Wc3CornEmitterPayload::popcornScaling, R"doc(0x40000: the node's scale reaches the effect.)doc")
    ;

    py::class_<whiteout::models::wem::Sc2Variation>(m, "Sc2Variation", R"doc(One of the per-particle variation channels: a curve type, and the amplitude and frequency it runs at.)doc")
        .def(py::init<>())
        .def_readwrite("type", &whiteout::models::wem::Sc2Variation::type, R"doc(0 = none.)doc")
        .def_readwrite("amplitude", &whiteout::models::wem::Sc2Variation::amplitude)
        .def_readwrite("frequency", &whiteout::models::wem::Sc2Variation::frequency)
    ;

    py::class_<whiteout::models::wem::Sc2ParticleEmitterPayload>(m, "Sc2ParticleEmitterPayload", R"doc(`PAR_` — the StarCraft II particle system — or one `PARC` copy of it.

Field names are the M3 record's. The bit words keep the file's own bits: `flags` is `m3::ParticleFlag`, `additionalFlags` `m3::ParticleAdditionalFlag`, `rotationFlags` `m3::ParticleRotationFlag`.

**A copy is a node too.** A `PARC` is another emission point of one system — its own bone, emission rate and squirt, the source's everything else — so it imports as a `Sc2ParticleEmitter` node under that bone whose `copyOf` names the source, and reads nothing of its payload but `emissionRate` and `squirtAmount`. The engine numbers copies as slots 1..n in node order.)doc")
        .def(py::init<>())
        .def_readwrite("copy_of", &whiteout::models::wem::Sc2ParticleEmitterPayload::copyOf, R"doc(Set on a `PARC`: the emitter it copies.)doc")
        .def_readwrite("material_slot", &whiteout::models::wem::Sc2ParticleEmitterPayload::materialSlot, R"doc(-> `Model::materialSlots`.)doc")
        .def_readwrite("additional_flags", &whiteout::models::wem::Sc2ParticleEmitterPayload::additionalFlags)
        .def_readwrite("initial_speed", &whiteout::models::wem::Sc2ParticleEmitterPayload::initialSpeed)
        .def_readwrite("initial_speed_random", &whiteout::models::wem::Sc2ParticleEmitterPayload::initialSpeedRandom)
        .def_readwrite("initial_yaw", &whiteout::models::wem::Sc2ParticleEmitterPayload::initialYaw)
        .def_readwrite("initial_pitch", &whiteout::models::wem::Sc2ParticleEmitterPayload::initialPitch)
        .def_readwrite("initial_horizontal", &whiteout::models::wem::Sc2ParticleEmitterPayload::initialHorizontal)
        .def_readwrite("initial_vertical", &whiteout::models::wem::Sc2ParticleEmitterPayload::initialVertical)
        .def_readwrite("lifetime", &whiteout::models::wem::Sc2ParticleEmitterPayload::lifetime)
        .def_readwrite("lifetime_random", &whiteout::models::wem::Sc2ParticleEmitterPayload::lifetimeRandom)
        .def_readwrite("kill_radius", &whiteout::models::wem::Sc2ParticleEmitterPayload::killRadius)
        .def_readwrite("gravity_x", &whiteout::models::wem::Sc2ParticleEmitterPayload::gravityX, R"doc(Stored as the file does; 0 everywhere shipped.)doc")
        .def_readwrite("gravity_y", &whiteout::models::wem::Sc2ParticleEmitterPayload::gravityY)
        .def_readwrite("gravity", &whiteout::models::wem::Sc2ParticleEmitterPayload::gravity)
        .def_readwrite("size_mid_time", &whiteout::models::wem::Sc2ParticleEmitterPayload::sizeMidTime)
        .def_readwrite("color_mid_time", &whiteout::models::wem::Sc2ParticleEmitterPayload::colorMidTime)
        .def_readwrite("alpha_mid_time", &whiteout::models::wem::Sc2ParticleEmitterPayload::alphaMidTime)
        .def_readwrite("rotation_mid_time", &whiteout::models::wem::Sc2ParticleEmitterPayload::rotationMidTime)
        .def_readwrite("size_mid_hold_time", &whiteout::models::wem::Sc2ParticleEmitterPayload::sizeMidHoldTime)
        .def_readwrite("color_mid_hold_time", &whiteout::models::wem::Sc2ParticleEmitterPayload::colorMidHoldTime)
        .def_readwrite("alpha_mid_hold_time", &whiteout::models::wem::Sc2ParticleEmitterPayload::alphaMidHoldTime)
        .def_readwrite("rotation_mid_hold_time", &whiteout::models::wem::Sc2ParticleEmitterPayload::rotationMidHoldTime)
        .def_readwrite("size_animation", &whiteout::models::wem::Sc2ParticleEmitterPayload::sizeAnimation, R"doc(Birth, middle, death.)doc")
        .def_readwrite("rotation_animation", &whiteout::models::wem::Sc2ParticleEmitterPayload::rotationAnimation, R"doc(Birth, middle, death.)doc")
        .def_readwrite("color_start", &whiteout::models::wem::Sc2ParticleEmitterPayload::colorStart)
        .def_readwrite("color_mid", &whiteout::models::wem::Sc2ParticleEmitterPayload::colorMid)
        .def_readwrite("color_end", &whiteout::models::wem::Sc2ParticleEmitterPayload::colorEnd)
        .def_readwrite("drag", &whiteout::models::wem::Sc2ParticleEmitterPayload::drag)
        .def_readwrite("mass", &whiteout::models::wem::Sc2ParticleEmitterPayload::mass)
        .def_readwrite("mass_random", &whiteout::models::wem::Sc2ParticleEmitterPayload::massRandom)
        .def_readwrite("mass_size_multiplier", &whiteout::models::wem::Sc2ParticleEmitterPayload::massSizeMultiplier)
        .def_readwrite("local_forces", &whiteout::models::wem::Sc2ParticleEmitterPayload::localForces, R"doc(Force channel masks.)doc")
        .def_readwrite("world_forces", &whiteout::models::wem::Sc2ParticleEmitterPayload::worldForces)
        .def_readwrite("local_forces_fallback", &whiteout::models::wem::Sc2ParticleEmitterPayload::localForcesFallback)
        .def_readwrite("world_forces_fallback", &whiteout::models::wem::Sc2ParticleEmitterPayload::worldForcesFallback)
        .def_readwrite("world_forces_mass_multiplier", &whiteout::models::wem::Sc2ParticleEmitterPayload::worldForcesMassMultiplier)
        .def_readwrite("noise_amplitude", &whiteout::models::wem::Sc2ParticleEmitterPayload::noiseAmplitude)
        .def_readwrite("noise_frequency", &whiteout::models::wem::Sc2ParticleEmitterPayload::noiseFrequency)
        .def_readwrite("noise_coherence", &whiteout::models::wem::Sc2ParticleEmitterPayload::noiseCoherence)
        .def_readwrite("noise_edge", &whiteout::models::wem::Sc2ParticleEmitterPayload::noiseEdge)
        .def_readwrite("index_plus_length", &whiteout::models::wem::Sc2ParticleEmitterPayload::indexPlusLength)
        .def_readwrite("max_particles", &whiteout::models::wem::Sc2ParticleEmitterPayload::maxParticles)
        .def_readwrite("emission_rate", &whiteout::models::wem::Sc2ParticleEmitterPayload::emissionRate)
        .def_readwrite("emitter_shape", &whiteout::models::wem::Sc2ParticleEmitterPayload::emitterShape)
        .def_readwrite("shape_outer", &whiteout::models::wem::Sc2ParticleEmitterPayload::shapeOuter)
        .def_readwrite("shape_inner", &whiteout::models::wem::Sc2ParticleEmitterPayload::shapeInner)
        .def_readwrite("outer_radius", &whiteout::models::wem::Sc2ParticleEmitterPayload::outerRadius)
        .def_readwrite("inner_radius", &whiteout::models::wem::Sc2ParticleEmitterPayload::innerRadius)
        .def_readwrite("shape_sections", &whiteout::models::wem::Sc2ParticleEmitterPayload::shapeSections, R"doc(The mesh sections a `Mesh` shape emits from: sections of `Model::meshes[0]`, which is the one division StarCraft II draws, so a section index is the region index the file stores.)doc")
        .def_readwrite("velocity_type", &whiteout::models::wem::Sc2ParticleEmitterPayload::velocityType)
        .def_readwrite("size_random_enable", &whiteout::models::wem::Sc2ParticleEmitterPayload::sizeRandomEnable)
        .def_readwrite("size_random_animation", &whiteout::models::wem::Sc2ParticleEmitterPayload::sizeRandomAnimation)
        .def_readwrite("rotation_random_enable", &whiteout::models::wem::Sc2ParticleEmitterPayload::rotationRandomEnable)
        .def_readwrite("rotation_random_animation", &whiteout::models::wem::Sc2ParticleEmitterPayload::rotationRandomAnimation)
        .def_readwrite("color_random_enable", &whiteout::models::wem::Sc2ParticleEmitterPayload::colorRandomEnable)
        .def_readwrite("color_start_random", &whiteout::models::wem::Sc2ParticleEmitterPayload::colorStartRandom)
        .def_readwrite("color_mid_random", &whiteout::models::wem::Sc2ParticleEmitterPayload::colorMidRandom)
        .def_readwrite("color_end_random", &whiteout::models::wem::Sc2ParticleEmitterPayload::colorEndRandom)
        .def_readwrite("alpha_random_enable", &whiteout::models::wem::Sc2ParticleEmitterPayload::alphaRandomEnable)
        .def_readwrite("squirt_amount", &whiteout::models::wem::Sc2ParticleEmitterPayload::squirtAmount, R"doc(A burst count, keyed as a step.)doc")
        .def_readwrite("flipbook_start_init_index", &whiteout::models::wem::Sc2ParticleEmitterPayload::flipbookStartInitIndex)
        .def_readwrite("flipbook_start_stop_index", &whiteout::models::wem::Sc2ParticleEmitterPayload::flipbookStartStopIndex)
        .def_readwrite("flipbook_end_init_index", &whiteout::models::wem::Sc2ParticleEmitterPayload::flipbookEndInitIndex)
        .def_readwrite("flipbook_end_stop_index", &whiteout::models::wem::Sc2ParticleEmitterPayload::flipbookEndStopIndex)
        .def_readwrite("flipbook_mid_time", &whiteout::models::wem::Sc2ParticleEmitterPayload::flipbookMidTime)
        .def_readwrite("flipbook_columns", &whiteout::models::wem::Sc2ParticleEmitterPayload::flipbookColumns)
        .def_readwrite("flipbook_rows", &whiteout::models::wem::Sc2ParticleEmitterPayload::flipbookRows)
        .def_readwrite("flipbook_column_fraction", &whiteout::models::wem::Sc2ParticleEmitterPayload::flipbookColumnFraction)
        .def_readwrite("flipbook_row_fraction", &whiteout::models::wem::Sc2ParticleEmitterPayload::flipbookRowFraction)
        .def_readwrite("bounce", &whiteout::models::wem::Sc2ParticleEmitterPayload::bounce)
        .def_readwrite("friction", &whiteout::models::wem::Sc2ParticleEmitterPayload::friction)
        .def_readwrite("collision_spawn", &whiteout::models::wem::Sc2ParticleEmitterPayload::collisionSpawn, R"doc(The emitter a collision spawns from.)doc")
        .def_readwrite("collision_spawn_min", &whiteout::models::wem::Sc2ParticleEmitterPayload::collisionSpawnMin)
        .def_readwrite("collision_spawn_max", &whiteout::models::wem::Sc2ParticleEmitterPayload::collisionSpawnMax)
        .def_readwrite("collision_spawn_chance", &whiteout::models::wem::Sc2ParticleEmitterPayload::collisionSpawnChance)
        .def_readwrite("collision_spawn_energy", &whiteout::models::wem::Sc2ParticleEmitterPayload::collisionSpawnEnergy)
        .def_readwrite("collision_die_bounce", &whiteout::models::wem::Sc2ParticleEmitterPayload::collisionDieBounce)
        .def_readwrite("instance_type", &whiteout::models::wem::Sc2ParticleEmitterPayload::instanceType)
        .def_readwrite("tail_length", &whiteout::models::wem::Sc2ParticleEmitterPayload::tailLength)
        .def_readwrite("instance_angle", &whiteout::models::wem::Sc2ParticleEmitterPayload::instanceAngle)
        .def_readwrite("instance_distance", &whiteout::models::wem::Sc2ParticleEmitterPayload::instanceDistance)
        .def_readwrite("pitch", &whiteout::models::wem::Sc2ParticleEmitterPayload::pitch)
        .def_readwrite("yaw", &whiteout::models::wem::Sc2ParticleEmitterPayload::yaw)
        .def_readwrite("speed", &whiteout::models::wem::Sc2ParticleEmitterPayload::speed)
        .def_readwrite("size", &whiteout::models::wem::Sc2ParticleEmitterPayload::size)
        .def_readwrite("alpha", &whiteout::models::wem::Sc2ParticleEmitterPayload::alpha)
        .def_readwrite("color", &whiteout::models::wem::Sc2ParticleEmitterPayload::color)
        .def_readwrite("rotation", &whiteout::models::wem::Sc2ParticleEmitterPayload::rotation)
        .def_readwrite("horizontal", &whiteout::models::wem::Sc2ParticleEmitterPayload::horizontal)
        .def_readwrite("vertical", &whiteout::models::wem::Sc2ParticleEmitterPayload::vertical)
        .def_readwrite("particle_velocity", &whiteout::models::wem::Sc2ParticleEmitterPayload::particleVelocity)
        .def_readwrite("phase_shift", &whiteout::models::wem::Sc2ParticleEmitterPayload::phaseShift)
        .def_readwrite("flags", &whiteout::models::wem::Sc2ParticleEmitterPayload::flags)
        .def_readwrite("rotation_flags", &whiteout::models::wem::Sc2ParticleEmitterPayload::rotationFlags)
        .def_readwrite("color_smoothing", &whiteout::models::wem::Sc2ParticleEmitterPayload::colorSmoothing)
        .def_readwrite("size_smoothing", &whiteout::models::wem::Sc2ParticleEmitterPayload::sizeSmoothing)
        .def_readwrite("rotation_smoothing", &whiteout::models::wem::Sc2ParticleEmitterPayload::rotationSmoothing)
        .def_readwrite("alpha_threshold", &whiteout::models::wem::Sc2ParticleEmitterPayload::alphaThreshold)
        .def_readwrite("uv_offset", &whiteout::models::wem::Sc2ParticleEmitterPayload::uvOffset)
        .def_readwrite("uv_angle", &whiteout::models::wem::Sc2ParticleEmitterPayload::uvAngle)
        .def_readwrite("uv_tiling", &whiteout::models::wem::Sc2ParticleEmitterPayload::uvTiling)
        .def_readwrite("spline_points", &whiteout::models::wem::Sc2ParticleEmitterPayload::splinePoints, R"doc(A `Spline` shape's path.)doc")
        .def_readwrite("wind_multiplier", &whiteout::models::wem::Sc2ParticleEmitterPayload::windMultiplier)
        .def_readwrite("lod_reduce", &whiteout::models::wem::Sc2ParticleEmitterPayload::lodReduce)
        .def_readwrite("lod_cut", &whiteout::models::wem::Sc2ParticleEmitterPayload::lodCut)
        .def_readwrite("lower_bound", &whiteout::models::wem::Sc2ParticleEmitterPayload::lowerBound)
        .def_readwrite("upper_bound", &whiteout::models::wem::Sc2ParticleEmitterPayload::upperBound)
        .def_readwrite("trail_link", &whiteout::models::wem::Sc2ParticleEmitterPayload::trailLink, R"doc(The emitter this one leaves trails with.)doc")
        .def_readwrite("trail_chance", &whiteout::models::wem::Sc2ParticleEmitterPayload::trailChance)
        .def_readwrite("trail_emission_rate", &whiteout::models::wem::Sc2ParticleEmitterPayload::trailEmissionRate)
        .def_readwrite("splat_projection_index", &whiteout::models::wem::Sc2ParticleEmitterPayload::splatProjectionIndex, R"doc(A `PROJ` index. WEM holds no projectors, so the number is carried as the file had it; -1 is none, which is every shipped emitter measured.)doc")
        .def_readwrite("splat_chance", &whiteout::models::wem::Sc2ParticleEmitterPayload::splatChance)
        .def_readwrite("models", &whiteout::models::wem::Sc2ParticleEmitterPayload::models, R"doc(Model particles, by path (`SCHR`).)doc")
        .def_readwrite("spawn_ribbon_on_bounce_chance", &whiteout::models::wem::Sc2ParticleEmitterPayload::spawnRibbonOnBounceChance)
        .def_readwrite("ribbon_link", &whiteout::models::wem::Sc2ParticleEmitterPayload::ribbonLink, R"doc(The ribbon a bounce spawns.)doc")
        .def_readwrite("noise_smoothness", &whiteout::models::wem::Sc2ParticleEmitterPayload::noiseSmoothness, R"doc(Pre-v12 only; the upgrade has nowhere to put it.)doc")
    ;

    py::class_<whiteout::models::wem::Sc2RibbonSplinePoint>(m, "Sc2RibbonSplinePoint", R"doc(`SRIB`: one control point of a `RIB_`'s spline, riding a bone of its own.)doc")
        .def(py::init<>())
        .def_readwrite("node", &whiteout::models::wem::Sc2RibbonSplinePoint::node, R"doc(The bone it rides.)doc")
        .def_readwrite("emission_offset", &whiteout::models::wem::Sc2RibbonSplinePoint::emissionOffset)
        .def_readwrite("emission_vector", &whiteout::models::wem::Sc2RibbonSplinePoint::emissionVector)
        .def_readwrite("velocity", &whiteout::models::wem::Sc2RibbonSplinePoint::velocity)
        .def_readwrite("reserved", &whiteout::models::wem::Sc2RibbonSplinePoint::reserved)
        .def_readwrite("velocity_base_factor", &whiteout::models::wem::Sc2RibbonSplinePoint::velocityBaseFactor)
        .def_readwrite("velocity_end_factor", &whiteout::models::wem::Sc2RibbonSplinePoint::velocityEndFactor)
        .def_readwrite("yaw_variation", &whiteout::models::wem::Sc2RibbonSplinePoint::yawVariation)
        .def_readwrite("pitch_variation", &whiteout::models::wem::Sc2RibbonSplinePoint::pitchVariation)
        .def_readwrite("velocity_variation", &whiteout::models::wem::Sc2RibbonSplinePoint::velocityVariation)
        .def_readwrite("yaw", &whiteout::models::wem::Sc2RibbonSplinePoint::yaw)
        .def_readwrite("pitch", &whiteout::models::wem::Sc2RibbonSplinePoint::pitch)
        .def_readwrite("emission_vector_norm_factor", &whiteout::models::wem::Sc2RibbonSplinePoint::emissionVectorNormFactor, R"doc(Shipped as ~0.01 / |emissionVector|.)doc")
        .def_readwrite("velocity_norm_factor", &whiteout::models::wem::Sc2RibbonSplinePoint::velocityNormFactor, R"doc(Shipped as ~0.01 / velocity.)doc")
    ;

    py::class_<whiteout::models::wem::Sc2RibbonEmitterPayload>(m, "Sc2RibbonEmitterPayload", R"doc(`RIB_` — the StarCraft II ribbon.

Its bone is the node's parent. The record's second `u16` beside the bone is the high half of one `u32` bone index to the editor, zero on every shipped ribbon, and is written as zero rather than carried. `flags` is `m3::RibbonFlag`, `additionalFlags` `m3::RibbonAdditionalFlag`.)doc")
        .def(py::init<>())
        .def_readwrite("material_slot", &whiteout::models::wem::Sc2RibbonEmitterPayload::materialSlot, R"doc(-> `Model::materialSlots`.)doc")
        .def_readwrite("additional_flags", &whiteout::models::wem::Sc2RibbonEmitterPayload::additionalFlags)
        .def_readwrite("initial_speed", &whiteout::models::wem::Sc2RibbonEmitterPayload::initialSpeed)
        .def_readwrite("initial_speed_random", &whiteout::models::wem::Sc2RibbonEmitterPayload::initialSpeedRandom)
        .def_readwrite("initial_yaw", &whiteout::models::wem::Sc2RibbonEmitterPayload::initialYaw)
        .def_readwrite("initial_pitch", &whiteout::models::wem::Sc2RibbonEmitterPayload::initialPitch)
        .def_readwrite("initial_horizontal", &whiteout::models::wem::Sc2RibbonEmitterPayload::initialHorizontal)
        .def_readwrite("initial_vertical", &whiteout::models::wem::Sc2RibbonEmitterPayload::initialVertical)
        .def_readwrite("lifetime", &whiteout::models::wem::Sc2RibbonEmitterPayload::lifetime)
        .def_readwrite("lifetime_random", &whiteout::models::wem::Sc2RibbonEmitterPayload::lifetimeRandom)
        .def_readwrite("kill_radius", &whiteout::models::wem::Sc2RibbonEmitterPayload::killRadius, R"doc(A `u32` in the ribbon record, unlike the particle's.)doc")
        .def_readwrite("gravity_x", &whiteout::models::wem::Sc2RibbonEmitterPayload::gravityX)
        .def_readwrite("gravity_y", &whiteout::models::wem::Sc2RibbonEmitterPayload::gravityY)
        .def_readwrite("gravity", &whiteout::models::wem::Sc2RibbonEmitterPayload::gravity)
        .def_readwrite("size_mid_time", &whiteout::models::wem::Sc2RibbonEmitterPayload::sizeMidTime)
        .def_readwrite("color_mid_time", &whiteout::models::wem::Sc2RibbonEmitterPayload::colorMidTime)
        .def_readwrite("alpha_mid_time", &whiteout::models::wem::Sc2RibbonEmitterPayload::alphaMidTime)
        .def_readwrite("rotation_mid_time", &whiteout::models::wem::Sc2RibbonEmitterPayload::rotationMidTime)
        .def_readwrite("size_mid_hold_time", &whiteout::models::wem::Sc2RibbonEmitterPayload::sizeMidHoldTime)
        .def_readwrite("color_mid_hold_time", &whiteout::models::wem::Sc2RibbonEmitterPayload::colorMidHoldTime)
        .def_readwrite("alpha_mid_hold_time", &whiteout::models::wem::Sc2RibbonEmitterPayload::alphaMidHoldTime)
        .def_readwrite("rotation_mid_hold_time", &whiteout::models::wem::Sc2RibbonEmitterPayload::rotationMidHoldTime)
        .def_readwrite("size_animation", &whiteout::models::wem::Sc2RibbonEmitterPayload::sizeAnimation)
        .def_readwrite("rotation_animation", &whiteout::models::wem::Sc2RibbonEmitterPayload::rotationAnimation)
        .def_readwrite("color_start", &whiteout::models::wem::Sc2RibbonEmitterPayload::colorStart)
        .def_readwrite("color_mid", &whiteout::models::wem::Sc2RibbonEmitterPayload::colorMid)
        .def_readwrite("color_end", &whiteout::models::wem::Sc2RibbonEmitterPayload::colorEnd)
        .def_readwrite("drag", &whiteout::models::wem::Sc2RibbonEmitterPayload::drag)
        .def_readwrite("mass", &whiteout::models::wem::Sc2RibbonEmitterPayload::mass)
        .def_readwrite("mass_random", &whiteout::models::wem::Sc2RibbonEmitterPayload::massRandom)
        .def_readwrite("mass_size_multiplier", &whiteout::models::wem::Sc2RibbonEmitterPayload::massSizeMultiplier)
        .def_readwrite("local_forces", &whiteout::models::wem::Sc2RibbonEmitterPayload::localForces)
        .def_readwrite("world_forces", &whiteout::models::wem::Sc2RibbonEmitterPayload::worldForces)
        .def_readwrite("local_forces_fallback", &whiteout::models::wem::Sc2RibbonEmitterPayload::localForcesFallback)
        .def_readwrite("world_forces_fallback", &whiteout::models::wem::Sc2RibbonEmitterPayload::worldForcesFallback)
        .def_readwrite("world_forces_mass_multiplier", &whiteout::models::wem::Sc2RibbonEmitterPayload::worldForcesMassMultiplier)
        .def_readwrite("noise_amplitude", &whiteout::models::wem::Sc2RibbonEmitterPayload::noiseAmplitude)
        .def_readwrite("noise_frequency", &whiteout::models::wem::Sc2RibbonEmitterPayload::noiseFrequency)
        .def_readwrite("noise_coherence", &whiteout::models::wem::Sc2RibbonEmitterPayload::noiseCoherence)
        .def_readwrite("noise_edge", &whiteout::models::wem::Sc2RibbonEmitterPayload::noiseEdge)
        .def_readwrite("index_plus_length", &whiteout::models::wem::Sc2RibbonEmitterPayload::indexPlusLength)
        .def_readwrite("emitter_shape", &whiteout::models::wem::Sc2RibbonEmitterPayload::emitterShape)
        .def_readwrite("ribbon_type", &whiteout::models::wem::Sc2RibbonEmitterPayload::ribbonType)
        .def_readwrite("divisions", &whiteout::models::wem::Sc2RibbonEmitterPayload::divisions)
        .def_readwrite("edges", &whiteout::models::wem::Sc2RibbonEmitterPayload::edges)
        .def_readwrite("inner_radius", &whiteout::models::wem::Sc2RibbonEmitterPayload::innerRadius)
        .def_readwrite("max_length", &whiteout::models::wem::Sc2RibbonEmitterPayload::maxLength)
        .def_readwrite("spline_points", &whiteout::models::wem::Sc2RibbonEmitterPayload::splinePoints, R"doc(`SRIB`.)doc")
        .def_readwrite("active", &whiteout::models::wem::Sc2RibbonEmitterPayload::active, R"doc(A flag, keyed as one. Rests at null 0 on every shipped ribbon.)doc")
        .def_readwrite("flags", &whiteout::models::wem::Sc2RibbonEmitterPayload::flags)
        .def_readwrite("size_smoothing", &whiteout::models::wem::Sc2RibbonEmitterPayload::sizeSmoothing)
        .def_readwrite("color_smoothing", &whiteout::models::wem::Sc2RibbonEmitterPayload::colorSmoothing)
        .def_readwrite("friction", &whiteout::models::wem::Sc2RibbonEmitterPayload::friction)
        .def_readwrite("bounce", &whiteout::models::wem::Sc2RibbonEmitterPayload::bounce)
        .def_readwrite("lod_reduce", &whiteout::models::wem::Sc2RibbonEmitterPayload::lodReduce)
        .def_readwrite("lod_cut", &whiteout::models::wem::Sc2RibbonEmitterPayload::lodCut)
        .def_readwrite("yaw", &whiteout::models::wem::Sc2RibbonEmitterPayload::yaw)
        .def_readwrite("pitch", &whiteout::models::wem::Sc2RibbonEmitterPayload::pitch)
        .def_readwrite("speed", &whiteout::models::wem::Sc2RibbonEmitterPayload::speed)
        .def_readwrite("size", &whiteout::models::wem::Sc2RibbonEmitterPayload::size)
        .def_readwrite("alpha", &whiteout::models::wem::Sc2RibbonEmitterPayload::alpha)
        .def_readwrite("particle_velocity", &whiteout::models::wem::Sc2RibbonEmitterPayload::particleVelocity)
        .def_readwrite("overlay", &whiteout::models::wem::Sc2RibbonEmitterPayload::overlay)
        .def_readwrite("deprecated_unknown", &whiteout::models::wem::Sc2RibbonEmitterPayload::deprecatedUnknown, R"doc(Pre-v7 only (`unknown3fbae7d6`).)doc")
    ;

    py::class_<whiteout::models::wem::Transform>(m, "Transform", R"doc(TRS everywhere in WEM. Nothing stores a matrix that a TRS can express.)doc")
        .def(py::init<>())
        .def_readwrite("translation", &whiteout::models::wem::Transform::translation)
        .def_readwrite("rotation", &whiteout::models::wem::Transform::rotation)
        .def_readwrite("scale", &whiteout::models::wem::Transform::scale)
    ;

    py::class_<whiteout::models::wem::Sphere>(m, "Sphere")
        .def(py::init<>())
        .def_readwrite("center", &whiteout::models::wem::Sphere::center)
        .def_readwrite("radius", &whiteout::models::wem::Sphere::radius)
    ;

    py::class_<whiteout::models::wem::HelperPayload>(m, "HelperPayload", R"doc(Empty for a Helper; the alternatives below are one per kind. Both empty payloads still reflect: an empty body writes nothing, and having one keeps every alternative visitable without the payload switch special-casing two.)doc")
        .def(py::init<>())
    ;

    py::class_<whiteout::models::wem::BonePayload>(m, "BonePayload")
        .def(py::init<>())
        .def_readwrite("bounds", &whiteout::models::wem::BonePayload::bounds, R"doc(D3 ships both a box and a sphere, per bone.)doc")
        .def_readwrite("sphere", &whiteout::models::wem::BonePayload::sphere)
        .def_readwrite("gate_mesh", &whiteout::models::wem::BonePayload::gateMesh, R"doc(MDX's bone -> geoset link: the mesh whose geoset animation gates this bone (its subtree is hidden while the mesh's alpha is 0) and, when that mesh is `SectionFlags::ProjectedShadow`, places it as a drop shadow. `kInvalidIndex`: none. `NODE` v5; an older chunk's link is migrated on read (`Node::migrateBoneGate`).)doc")
    ;

    py::class_<whiteout::models::wem::AttachmentPayload>(m, "AttachmentPayload", R"doc(An attach point, and what is riding it.

The placement is the node — that is the whole of an MDX or `.m2` attachment, and of a D3 hardpoint, which is skeleton-relative data shipped with the skeleton. The equip-slot key (M2's attachment `id`, the hardpoint's own name) lives in `native`.

What rides it is the other half, and it is here rather than in a parallel list for §10.2's reason: removing or reparenting the node has to move everything that is *about* it, and a side table of `{node, child}` pairs would be one more referencer §10.6 has to invalidate.

Both halves are optional and independent. `asset` is what the source named — an effect WEM does not contain (§18), or a model it does. `model` is filled when that name resolved to something the document now holds, which is how a D3 child actor arrives: it converts to a `Model` of its own and the attach point points at it.)doc")
        .def(py::init<>())
        .def_readwrite("asset", &whiteout::models::wem::AttachmentPayload::asset, R"doc(What the source named, resolved or not.)doc")
        .def_readwrite("model", &whiteout::models::wem::AttachmentPayload::model, R"doc(-> `Document::models[]` once it resolved.)doc")
    ;

    py::class_<whiteout::models::wem::LightPayload>(m, "LightPayload")
        .def(py::init<>())
        .def_readwrite("kind", &whiteout::models::wem::LightPayload::kind)
        .def_readwrite("color", &whiteout::models::wem::LightPayload::color)
        .def_readwrite("intensity", &whiteout::models::wem::LightPayload::intensity)
        .def_readwrite("attenuation_start", &whiteout::models::wem::LightPayload::attenuationStart)
        .def_readwrite("attenuation_end", &whiteout::models::wem::LightPayload::attenuationEnd)
        .def_readwrite("hot_spot", &whiteout::models::wem::LightPayload::hotSpot, R"doc(Spot cone inner angle.)doc")
        .def_readwrite("falloff", &whiteout::models::wem::LightPayload::falloff, R"doc(Spot cone outer angle.)doc")
        .def_readwrite("shadow_casting", &whiteout::models::wem::LightPayload::shadowCasting, R"doc(MDX v1300: the light casts shadows, over `shadowCastingStart` .. `shadowCastingEnd` from it — its shadow cube's near and far.)doc")
        .def_readwrite("shadow_casting_start", &whiteout::models::wem::LightPayload::shadowCastingStart)
        .def_readwrite("shadow_casting_end", &whiteout::models::wem::LightPayload::shadowCastingEnd)
        .def_readwrite("quadratic_falloff", &whiteout::models::wem::LightPayload::quadraticFalloff, R"doc(MDX v1600: the distance falloff, a factor of `exp(-damping d²) / (1 + linearFalloff d + quadraticFalloff d²)` — unrelated to the spot cone's `falloff`.)doc")
        .def_readwrite("linear_falloff", &whiteout::models::wem::LightPayload::linearFalloff)
        .def_readwrite("damping", &whiteout::models::wem::LightPayload::damping)
    ;

    py::class_<whiteout::models::wem::CameraPayload>(m, "CameraPayload")
        .def(py::init<>())
        .def_readwrite("fov", &whiteout::models::wem::CameraPayload::fov)
        .def_readwrite("near_clip", &whiteout::models::wem::CameraPayload::nearClip)
        .def_readwrite("far_clip", &whiteout::models::wem::CameraPayload::farClip)
        .def_readwrite("target", &whiteout::models::wem::CameraPayload::target, R"doc(Where the camera looks, in model space. MDX and M2 store one; M3 and glTF aim a camera by its node's orientation instead, and leave this at the origin — which is also what a v3 `NODE` reads as.)doc")
    ;

    py::class_<whiteout::models::wem::ParticlePayload>(m, "ParticlePayload")
        .def(py::init<>())
        .def_readwrite("system", &whiteout::models::wem::ParticlePayload::system, R"doc(WHAT runs here, never how (§18).)doc")
    ;

    py::class_<whiteout::models::wem::RibbonPayload>(m, "RibbonPayload")
        .def(py::init<>())
        .def_readwrite("system", &whiteout::models::wem::RibbonPayload::system)
    ;

    py::class_<whiteout::models::wem::EventPayload>(m, "EventPayload")
        .def(py::init<>())
        .def_readwrite("id", &whiteout::models::wem::EventPayload::id)
    ;

    py::class_<whiteout::models::wem::CollisionShapeDesc>(m, "CollisionShapeDesc")
        .def(py::init<>())
        .def_readwrite("kind", &whiteout::models::wem::CollisionShapeDesc::kind)
        .def_readwrite("box", &whiteout::models::wem::CollisionShapeDesc::box)
        .def_readwrite("sphere", &whiteout::models::wem::CollisionShapeDesc::sphere)
        .def_readwrite("height", &whiteout::models::wem::CollisionShapeDesc::height, R"doc(Capsule / cylinder length along the shape's local axis.)doc")
    ;

    py::class_<whiteout::models::wem::CollisionPayload>(m, "CollisionPayload")
        .def(py::init<>())
        .def_readwrite("shape", &whiteout::models::wem::CollisionPayload::shape)
    ;

    py::class_<whiteout::models::wem::Node>(m, "Node")
        .def(py::init<>())
        .def_readwrite("name", &whiteout::models::wem::Node::name)
        .def_readwrite("parent", &whiteout::models::wem::Node::parent, R"doc(Index into `NodeTree::nodes`; invalid = a root.)doc")
        .def_readwrite("kind", &whiteout::models::wem::Node::kind)
        .def_readwrite("flags", &whiteout::models::wem::Node::flags)
        .def_readwrite("pivot", &whiteout::models::wem::Node::pivot, R"doc(MDX `PIVT`; zero for the other three formats — a D3 `PRSTransform` is complete with no separate pivot.)doc")
        .def_readwrite("local", &whiteout::models::wem::Node::local, R"doc(Bind-time local TRS.)doc")
        .def_readwrite("uniform_scale_only", &whiteout::models::wem::Node::uniformScaleOnly, R"doc(D3 stores ONE scale float per bone; export asserts on this rather than silently writing the x component of a non-uniform scale.)doc")
        .def_readwrite("poses", &whiteout::models::wem::Node::poses, R"doc(Values for `NodeTree::poseSchema` — sized to it for Bone nodes, empty for kinds that carry none (§10.5).)doc")
        .def_readwrite("native", &whiteout::models::wem::Node::native)
        .def_readwrite("removed", &whiteout::models::wem::Node::removed, R"doc(Transient removal marker (§10.6).

`RemoveNode` marks; `CompactNodes` collects. It lives on the node rather than in a parallel status array for the same reason the poses do: removing or copying a node has to move everything that is about it. Never serialized — a written document is always compacted first.)doc")
    ;

    py::class_<whiteout::models::wem::PoseSchema>(m, "PoseSchema")
        .def(py::init<>())
        .def_readwrite("name", &whiteout::models::wem::PoseSchema::name, R"doc("bind", "bindA", "bindAInverse", …)doc")
        .def_readwrite("space", &whiteout::models::wem::PoseSchema::space)
        .def_readwrite("inverse", &whiteout::models::wem::PoseSchema::inverse)
        .def_readwrite("storage", &whiteout::models::wem::PoseSchema::storage)
    ;

    py::class_<whiteout::models::wem::NodeTree>(m, "NodeTree")
        .def(py::init<>())
        .def_readwrite("nodes", &whiteout::models::wem::NodeTree::nodes, R"doc(Parents precede children.)doc")
        .def_readwrite("pose_schema", &whiteout::models::wem::NodeTree::poseSchema)
        .def_readwrite("authoritative_pose", &whiteout::models::wem::NodeTree::authoritativePose, R"doc(Which schema entry a profile treats as *the* bind pose.)doc")
        .def_readwrite("rig", &whiteout::models::wem::NodeTree::rig, R"doc(What convention the values above are in — the fact that decides whether a `.mdx` exporter may write `pivot` and an `.m3` one may write `IREF` straight through.

Set by every importer, read by `RetargetSkeleton` and by the four exporters. It is a property of what the tree *holds*, and `ProfileDesc::rig` is the property of what a format *wants*; a retarget is the operation between them.)doc")
        .def("size", &whiteout::models::wem::NodeTree::size)
        .def("empty", &whiteout::models::wem::NodeTree::empty)
        .def("add", &whiteout::models::wem::NodeTree::add, py::arg("node"), R"doc(Appends a node and returns its index. The caller is responsible for the parents-precede-children invariant; `Validate` checks it.)doc")
        .def("clear", &whiteout::models::wem::NodeTree::clear)
        .def("parents_precede_children", &whiteout::models::wem::NodeTree::parentsPrecedeChildren, R"doc(True when every node's parent index precedes it (or is invalid).)doc")
        .def("sort_parents_first", &whiteout::models::wem::NodeTree::sortParentsFirst, R"doc(Reorders `nodes` so parents precede children and returns the remap (`remap[old] == new`). A cycle leaves the tree untouched and returns an empty remap.)doc")
        .def("ensure_hierarchy", &whiteout::models::wem::NodeTree::ensureHierarchy, R"doc(Builds the child lists and the depth-first pre-order from `parent`.

Children come out in index order, so the build is deterministic and golden tests can compare traversal orders. Dropped by any structural mutation.

The pre-order is stored as one flat array with a per-node (offset, size), the Euler-tour layout: that makes `subtree()` a contiguous slice rather than a walk, so it can be a real range and two callers can hold two subtree ranges at once.)doc")
        .def("invalidate_hierarchy", &whiteout::models::wem::NodeTree::invalidateHierarchy)
        .def("has_hierarchy", &whiteout::models::wem::NodeTree::hasHierarchy)
        .def("depth", &whiteout::models::wem::NodeTree::depth, py::arg("node"))
        .def("world_bind", &whiteout::models::wem::NodeTree::worldBind, py::arg("node"), R"doc(Composes locals up the chain, honouring the inherit flags.

The same composition D3's `Skeleton_ComposeWorldPose` performs. A node flagged `ModelSpace` stops the walk: its local *is* its world.)doc")
        .def("pose_of", &whiteout::models::wem::NodeTree::poseOf, py::arg("node"), py::arg("pose"), R"doc(The pose value for @p node under schema entry @p pose, or its `local` (composed to the schema's space) when the node carries no pose array.

A `PoseStorage::Matrix` entry answers with the *decomposition* of the stored matrix, which is what `poses` holds — use @ref poseMatrixOf when the exact value is what matters.)doc")
        .def("pose_matrix_of", &whiteout::models::wem::NodeTree::poseMatrixOf, py::arg("node"), py::arg("pose"), R"doc(The same value as a matrix, and the authoritative one: a `PoseStorage::Matrix` entry with a stored matrix answers with it unchanged, and everything else composes @ref poseOf.)doc")
        .def("conform_poses", &whiteout::models::wem::NodeTree::conformPoses, R"doc(Resizes every Bone node's `poses` to `poseSchema.size()`, filling new entries from `worldBind`/`local` as the schema's space asks.)doc")
        .def("inverse_bind_matrix", &whiteout::models::wem::NodeTree::inverseBindMatrix, py::arg("node"), R"doc(The matrix a skinning palette multiplies @p node's animated frame by — `skin = inverseBindMatrix(b) * world(b)`.

The one question every exporter and every evaluator actually has, and the only place `rig` needs to be read to answer it: an `ExplicitBind` tree answers with the shipped `IREF`/`tTransform4`, and a `PivotRelative` one with the inverse of the composed rest chain — identity in the animation's own terms, but the pivot chain is what `local` holds there, so the inverse of `worldBind` is what makes the two agree at the bind pose.)doc")
        .def("inferred_rig", &whiteout::models::wem::NodeTree::inferredRig, R"doc(The convention `poseSchema` implies, for a tree that never recorded one: an inverse or matrix pose entry exists only to carry an explicit bind.)doc")
    ;

    py::class_<whiteout::models::wem::MaterialChannelRef>(m, "MaterialChannelRef", R"doc(Which material a channel drives, along the profile and look axes.

A material *index* alone is ambiguous the moment a model carries several sets (§6.3) and several looks (§8), so the reference is spelled the way `Resolve` is: profile, slot, look. It is deliberately not the resolved index — a look removal renumbers those, and a slot name does not.)doc")
        .def(py::init<>())
        .def_readwrite("profile", &whiteout::models::wem::MaterialChannelRef::profile)
        .def_readwrite("slot", &whiteout::models::wem::MaterialChannelRef::slot, R"doc(-> `Model::materialSlots`.)doc")
        .def_readwrite("look", &whiteout::models::wem::MaterialChannelRef::look, R"doc(-> the set's `LookTable`.)doc")
    ;

    py::class_<whiteout::models::wem::TrackTarget>(m, "TrackTarget")
        .def(py::init<>())
        .def_readwrite("node", &whiteout::models::wem::TrackTarget::node, R"doc(`Kind::Node`: -> `Model::nodes`.)doc")
        .def_readwrite("mesh", &whiteout::models::wem::TrackTarget::mesh, R"doc(`Kind::Section`: -> `Model::meshes`.)doc")
        .def_readwrite("material", &whiteout::models::wem::TrackTarget::material)
        .def_readwrite("sub", &whiteout::models::wem::TrackTarget::sub, R"doc(What `kind` says it is. For a node it separates same-named properties of one node — an `.m2` light keys an ambient colour beside its diffuse one — and is 0 for everything with only one.)doc")
        .def_readwrite("channel", &whiteout::models::wem::TrackTarget::channel)
    ;

    py::class_<whiteout::models::wem::AnimChannel>(m, "AnimChannel", R"doc(One animatable property, declared once. M3's AnimRef, hoisted out of the owner structs into a per-model table.)doc")
        .def(py::init<>())
        .def_readwrite("id", &whiteout::models::wem::AnimChannel::id, R"doc(The join key, stable for the model's life and **never reused**. M3's animId arrives here unchanged, which is what makes an `.m3a` merge a concatenation rather than a re-resolution; the other three importers allocate ids and the value is theirs to choose.)doc")
        .def_readwrite("target", &whiteout::models::wem::AnimChannel::target)
        .def_readwrite("init_value", &whiteout::models::wem::AnimChannel::initValue, R"doc(One element of `valueType`, or empty. What an **opaque** container contributes for this channel when it holds no sub-track for it — the asymmetry M3's split-body playback is built on (§10.8.1). Empty means the source declared no rest value, not "zero".)doc")
    ;

    py::class_<whiteout::models::wem::AnimChannelTable>(m, "AnimChannelTable", R"doc(The animatable properties of one model (§10.8).

Empty is a normal state — a model with no animation carries no channels.)doc")
        .def(py::init<>())
        .def_readwrite("channels", &whiteout::models::wem::AnimChannelTable::channels)
    ;

    py::class_<whiteout::models::wem::SubTrack>(m, "SubTrack", R"doc(One channel's keyframe stream. M3's SD entry.

`times` are **seconds**, converted at import from whatever ticks the source counts in, and are **not clamped or padded to `Clip::duration`**: M3 wraps the playhead modulo the *track's* own length, so a sub-track outlasting or undershooting its clip is data, not an error (§10.8.2).)doc")
        .def(py::init<>())
        .def_readwrite("channel", &whiteout::models::wem::SubTrack::channel, R"doc(An `AnimChannel::id`, never an index into the table.)doc")
        .def_readwrite("interp", &whiteout::models::wem::SubTrack::interp)
        .def_readwrite("times", &whiteout::models::wem::SubTrack::times)
        .def_readwrite("values", &whiteout::models::wem::SubTrack::values, R"doc(`times.size() * ValuesPerKey(interp) * AttrTypeSize(channel's valueType)` bytes. The type is on the channel because every sub-track that drives one must agree about it, and storing it here would let two disagree.)doc")
        .def_readwrite("tcb", &whiteout::models::wem::SubTrack::tcb, R"doc(TCB parameters, three per key (tension, continuity, bias), or empty. Only meaningful on a `Hermite` sub-track: the tangents in `values` are the ones these produce, so a consumer that ignores this field plays the same curve. An editor keeps them to derive the tangents again when a key changes; a format without TCB drops them and keeps the curve.)doc")
    ;

    py::class_<whiteout::models::wem::SubTrackContainer>(m, "SubTrackContainer", R"doc(One layer of a clip. M3's STC_.

`concurrent` is the asymmetry: a **transparent** container (true) holding no sub-track for a channel is skipped and lower layers show through; an **opaque** one contributes the channel's `initValue` at full weight, forcing un-keyed channels back to rest. Every non-M3 importer writes one opaque container at priority 0, which is the degenerate case of the same rule.)doc")
        .def(py::init<>())
        .def_readwrite("name", &whiteout::models::wem::SubTrackContainer::name)
        .def_readwrite("priority", &whiteout::models::wem::SubTrackContainer::priority, R"doc(STC `animPriority`.)doc")
        .def_readwrite("concurrent", &whiteout::models::wem::SubTrackContainer::concurrent, R"doc(STC `runsConcurrent`.)doc")
        .def_readwrite("sub_tracks", &whiteout::models::wem::SubTrackContainer::subTracks)
        .def_readwrite("native", &whiteout::models::wem::SubTrackContainer::native)
    ;

    py::class_<whiteout::models::wem::ClipEvent>(m, "ClipEvent", R"doc(A discrete key firing at a node — the node is the *where*, the key is the *when*.

MDX's `EventObject` plus its KEVT timestamps, M3's SDEV keys, D3's `flEventFrame`. What the event *means* is the host's: WEM carries the name and one integer because that is all three formats agree on.

The node's **kind is not fixed**: MDX and `.m2` name a dedicated `Event` node, `.m3` names the bone the SDEV key sits on, and D3 names the attachment its hardpoint resolves to. All three are the place the event happens.)doc")
        .def(py::init<>())
        .def_readwrite("time", &whiteout::models::wem::ClipEvent::time, R"doc(Seconds from the clip's start.)doc")
        .def_readwrite("node", &whiteout::models::wem::ClipEvent::node, R"doc(The node it fires at, of any kind; a §10.6 referencer.)doc")
        .def_readwrite("name", &whiteout::models::wem::ClipEvent::name)
        .def_readwrite("value", &whiteout::models::wem::ClipEvent::value)
    ;

    py::class_<whiteout::models::wem::Clip>(m, "Clip", R"doc(One playable animation. M3's SEQS plus its STG_.

`model` exists because a document holds several models (§9.1) and a channel id is only meaningful within one model's table — a clip that did not say whose nodes its sub-tracks name would be ambiguous the moment a D3 actor brought a second model along on a hardpoint.)doc")
        .def(py::init<>())
        .def_readwrite("name", &whiteout::models::wem::Clip::name)
        .def_readwrite("model", &whiteout::models::wem::Clip::model, R"doc(-> `Document::models[]`. Whose channel table this drives.)doc")
        .def_readwrite("duration", &whiteout::models::wem::Clip::duration, R"doc(Seconds.)doc")
        .def_readwrite("looping", &whiteout::models::wem::Clip::looping)
        .def_readwrite("flags", &whiteout::models::wem::Clip::flags)
        .def_readwrite("containers", &whiteout::models::wem::Clip::containers, R"doc(>= 1; one is the common case.)doc")
        .def_readwrite("events", &whiteout::models::wem::Clip::events)
        .def_readwrite("native", &whiteout::models::wem::Clip::native)
        .def_readwrite("bounds", &whiteout::models::wem::Clip::bounds, R"doc(What the model occupies while this clip plays, when the source said so. All zeros when it did not — which `valid()` calls well-formed, so test the extent for volume, not validity.

The one place WEM stores a bound it does not recompute. All four formats ship one per sequence — MDX's `Sequence::extent`, M2's `bounds`, M3's SEQS extents — and it is not derivable from the geometry: it is the union over the *posed* mesh across the clip, so recovering it means evaluating the whole skeleton at a sampling the source never recorded. A host reads it to frame a camera, and a conservative substitute (the model's own bounds) frames every clip as though it were the widest.)doc")
    ;

    py::class_<whiteout::models::wem::AnimTag>(m, "AnimTag", R"doc(One (tag -> clip) row. A struct rather than a `std::pair` because a pair has no `reflect()` and naming the halves is worth more than the two lines.)doc")
        .def(py::init<>())
        .def_readwrite("tag_id", &whiteout::models::wem::AnimTag::tagId, R"doc(The source's own tag id; D3 hashes a name into it.)doc")
        .def_readwrite("clip", &whiteout::models::wem::AnimTag::clip, R"doc(-> `Document::clips[]`.)doc")
    ;

    py::class_<whiteout::models::wem::AnimSet>(m, "AnimSet", R"doc(A named (tag -> clip) map, with a fallback.

D3's `.ans` is the shape this exists for: 30 tag maps in one asset, one core and 29 keyed by what the character is holding, and the runtime falls back to core when the weapon's map has no row for a tag. That is **one `AnimSet` per map**, with `baseAnimSet` pointing at the core one — the fallback field spelling the fallback, rather than a 30-wide struct nothing else could use. The same field carries `.ans`'s own `snoBaseAnimSet` link on the core set, because it means the same thing one level up.)doc")
        .def(py::init<>())
        .def_readwrite("name", &whiteout::models::wem::AnimSet::name)
        .def_readwrite("by_tag", &whiteout::models::wem::AnimSet::byTag)
        .def_readwrite("base_anim_set", &whiteout::models::wem::AnimSet::baseAnimSet, R"doc(-> `Document::animSets[]`.)doc")
    ;

    py::class_<whiteout::models::wem::SlotBinding>(m, "SlotBinding", R"doc(Which material each look picks, for one slot.

Sized to the set's `LookTable`. An entry of `kInvalidIndex` is a hole the coverage rule reports — §7.5's removal operations leave one rather than silently repointing at a neighbour, because "which material did you mean" is not a question this layer can answer.)doc")
        .def(py::init<>())
        .def_readwrite("by_look", &whiteout::models::wem::SlotBinding::byLook)
    ;

    py::class_<whiteout::models::wem::ProfileMaterialSet>(m, "ProfileMaterialSet")
        .def(py::init<>())
        .def_readwrite("profile", &whiteout::models::wem::ProfileMaterialSet::profile)
        .def_readwrite("looks", &whiteout::models::wem::ProfileMaterialSet::looks, R"doc(Sized 1 for profiles without looks (§8).)doc")
        .def_readwrite("default_look", &whiteout::models::wem::ProfileMaterialSet::defaultLook, R"doc(Which look this set draws when nobody says otherwise.

On the set rather than the `Model` because the look axis is per set: D3's looks and WoW's texture variations are different vocabularies and share no index space. An importer that was *told* which look to build records it here, so the document says what it is rather than leaving the answer in the caller's arguments.)doc")
        .def_readwrite("materials", &whiteout::models::wem::ProfileMaterialSet::materials, R"doc(Set-local array.)doc")
        .def_readwrite("slot_bindings", &whiteout::models::wem::ProfileMaterialSet::slotBindings, R"doc(Parallel to `Model::materialSlots`.)doc")
        .def_readwrite("native", &whiteout::models::wem::ProfileMaterialSet::native)
    ;

    py::class_<whiteout::models::wem::Model>(m, "Model")
        .def(py::init<>())
        .def_readwrite("name", &whiteout::models::wem::Model::name)
        .def_readwrite("meshes", &whiteout::models::wem::Model::meshes, R"doc(Shared across profiles.)doc")
        .def_readwrite("nodes", &whiteout::models::wem::Model::nodes, R"doc(Shared: bones, lights, attachments, emitters.)doc")
        .def_readwrite("material_slots", &whiteout::models::wem::Model::materialSlots, R"doc(Shared: the join key.)doc")
        .def_readwrite("anim_channels", &whiteout::models::wem::Model::animChannels, R"doc(Shared: the animatable properties (§10.8).)doc")
        .def_readwrite("anim_set", &whiteout::models::wem::Model::animSet, R"doc(The `Document::animSets[]` a host plays this model through by default, or `kInvalidIndex`.

On the `Model` because that is what a D3 actor's `snoAnimSet` names once the actor has become one (§9.1) — there is no `Actor` to hang it on, and a document-level pairing would be a side table with the model index in it, which is the shape §10.2 exists to avoid. Two actors sharing an appearance but not an animset are therefore two models, the same way two that equip differently are.)doc")
        .def_readwrite("profile_sets", &whiteout::models::wem::Model::profileSets)
        .def_readwrite("bounds", &whiteout::models::wem::Model::bounds)
        .def("slot_index", &whiteout::models::wem::Model::slotIndex, py::arg("name"), R"doc(The index of the slot named @p name, or `kInvalidIndex`.)doc")
        .def("add_slot", &whiteout::models::wem::Model::addSlot, py::arg("name"), R"doc(Appends a slot if it is not already there and returns its index.)doc")
        .def("drawn_profiles", &whiteout::models::wem::Model::drawnProfiles, R"doc(The mask of profiles at least one section draws in. Cheap, and what a UI wants when it asks "what is actually in this file".)doc")
    ;

    py::class_<whiteout::models::wem::UnknownChunk>(m, "UnknownChunk", R"doc(A chunk this build did not recognise, carried through unchanged (§11.4).

Forward compatibility is the point: a newer writer's chunk survives a round-trip through an older reader instead of being silently dropped.)doc")
        .def(py::init<>())
        .def_readwrite("tag", &whiteout::models::wem::UnknownChunk::tag)
        .def_readwrite("version", &whiteout::models::wem::UnknownChunk::version)
        .def_readwrite("count", &whiteout::models::wem::UnknownChunk::count, R"doc(The element count from the source index entry. The reader cannot derive it -- it does not know the element type -- and a reader that *does* know the type needs it, so it is carried rather than recomputed.)doc")
        .def_readwrite("index", &whiteout::models::wem::UnknownChunk::index, R"doc(The index-table slot the chunk occupied. **Load-bearing.** A preserved chunk's bytes contain `Reference`s of their own, and a `Reference` names an index-table *slot*; renumbering the table would silently break every one of them. The writer holds these slots open so the numbering survives.)doc")
        .def_readwrite("data", &whiteout::models::wem::UnknownChunk::data)
    ;

    py::class_<whiteout::models::wem::Document>(m, "Document")
        .def(py::init<>())
        .def_readwrite("profiles", &whiteout::models::wem::Document::profiles, R"doc(The declared set. A `ProfileMaterialSet` for an undeclared profile is a structural error, as is a `defaultProfile` outside this list.)doc")
        .def_readwrite("default_profile", &whiteout::models::wem::Document::defaultProfile)
        .def_readwrite("space", &whiteout::models::wem::Document::space, R"doc(Canonical, always (§6.4). The per-profile source space lives in the registry, so an exporter knows how to rebase back.)doc")
        .def_readwrite("unit_scale", &whiteout::models::wem::Document::unitScale, R"doc(What one WEM unit is, if the caller knows. Scale is **not** normalised — geometry stays in the units it was authored in.)doc")
        .def_readwrite("name", &whiteout::models::wem::Document::name)
        .def_readwrite("bounds", &whiteout::models::wem::Document::bounds)
        .def_readwrite("models", &whiteout::models::wem::Document::models, R"doc(One per drawable. A D3 actor converts to `models[0]` and everything its attach points reach follows it (§9.1); every other importer produces one.)doc")
        .def_readwrite("textures", &whiteout::models::wem::Document::textures)
        .def_readwrite("clips", &whiteout::models::wem::Document::clips, R"doc(Every clip in the document, each naming the model it drives (§10.8).

Document-level rather than per model because an `.m3a` merge and a D3 anim set both address clips across models, and because a clip index in an `AnimSet` would otherwise have to carry a model index beside it.)doc")
        .def_readwrite("anim_sets", &whiteout::models::wem::Document::animSets, R"doc(The named (tag -> clip) maps. D3 is the only importer that fills this today; `Model::animSet` is how a model says which one is its default.)doc")
        .def_readwrite("unknown_chunks", &whiteout::models::wem::Document::unknownChunks, R"doc(Chunks this build did not understand, carried through unchanged (§11.4).

The parser fills it and the writer reads it, so a read-edit-write round trip preserves them by doing nothing. Clearing it is how a caller drops them -- an act, not an omission.)doc")
        .def("carries", &whiteout::models::wem::Document::carries, py::arg("profile"))
        .def("declare", &whiteout::models::wem::Document::declare, py::arg("profile"), R"doc(Declares @p profile if it is not already declared. Does not create material sets — that is `AddProfileFromImport` or `DeriveProfile` (§6.6).)doc")
        .def("declared_mask", &whiteout::models::wem::Document::declaredMask, R"doc(Every declared profile as a mask.)doc")
    ;

    py::class_<whiteout::models::wem::ReadOptions>(m, "ReadOptions", R"doc(Which formats this reader is willing to parse the native block of.

§11.3's wasm-build-without-D3 property, as a runtime option rather than a build one: a skipped block's chunk is preserved whole and its reference is re-emitted, so a document read this way can be edited and written back with the skipped sets intact. Empty means parse everything.)doc")
        .def(py::init<>())
        .def_readwrite("skip_native_kinds", &whiteout::models::wem::ReadOptions::skipNativeKinds)
    ;

    py::class_<whiteout::models::wem::Parser>(m, "Parser")
        .def(py::init<>())
        .def("parse",
            [](whiteout::models::wem::Parser& self, const std::string& filePath, const whiteout::models::wem::ReadOptions& options) {
                return self.parse(filePath, options);
            }, py::arg("filePath"), py::arg("options") = whiteout::models::wem::ReadOptions{})
        .def("parse",
            [](whiteout::models::wem::Parser& self, py::bytes __py_bytes_0, const whiteout::models::wem::ReadOptions& options) {
                std::string __s_0 = __py_bytes_0;
                std::span<const whiteout::u8> bytes(reinterpret_cast<const whiteout::u8*>(__s_0.data()), __s_0.size());
                return self.parse(bytes, options);
            }, py::arg("bytes"), py::arg("options") = whiteout::models::wem::ReadOptions{})
        .def("unknown_chunks", &whiteout::models::wem::Parser::unknownChunks, R"doc(Chunks the read preserved rather than parsed — unknown tags, and the native blocks `ReadOptions` asked to skip. Hand these back to `Writer` or they are dropped on the next write.)doc")
        .def("diagnostics", &whiteout::models::wem::Parser::diagnostics)
    ;

    py::class_<whiteout::models::wem::Writer>(m, "Writer")
        .def(py::init<>())
        .def("write", py::overload_cast<const std::string&, const whiteout::models::wem::Document&>(&whiteout::models::wem::Writer::write), py::arg("filePath"), py::arg("document"))
        .def("write",
            [](whiteout::models::wem::Writer& self, const whiteout::models::wem::Document& document) {
                auto __v = self.write(document);
                return py::bytes(
                    reinterpret_cast<const char*>(__v.data()), __v.size());
            }, py::arg("document"))
        .def("diagnostics", &whiteout::models::wem::Writer::diagnostics)
    ;

    py::class_<whiteout::models::wem::Sc2Property<whiteout::f32>>(m, "Sc2PropertyF32", R"doc(One animatable property of a StarCraft II emitter, at rest.

An M3 AnimRef without its link. `initValue` is what plays while no clip keys the property; the link — the animId and the keys — is the node's `Channel::EmitterProperty` channel, whose id is the AnimRef's own (§10.8.1).

`nullValue` is live, not padding: the engine retires an unkeyed `PAR_` whose rate and squirt, or a `RIB_` whose `active`, sit at their nulls before it emits anything. Shipped emitters rest every null at zero.

Colours are RGBA in 0..1, the channel convention; a `u16` squirt count widens to `u32`.)doc")
        .def(py::init<>())
        .def_readwrite("init_value", &whiteout::models::wem::Sc2Property<whiteout::f32>::initValue)
        .def_readwrite("null_value", &whiteout::models::wem::Sc2Property<whiteout::f32>::nullValue)
    ;

    py::class_<whiteout::models::wem::Sc2Property<whiteout::Vector3f>>(m, "Sc2PropertyVector3f", R"doc(One animatable property of a StarCraft II emitter, at rest.

An M3 AnimRef without its link. `initValue` is what plays while no clip keys the property; the link — the animId and the keys — is the node's `Channel::EmitterProperty` channel, whose id is the AnimRef's own (§10.8.1).

`nullValue` is live, not padding: the engine retires an unkeyed `PAR_` whose rate and squirt, or a `RIB_` whose `active`, sit at their nulls before it emits anything. Shipped emitters rest every null at zero.

Colours are RGBA in 0..1, the channel convention; a `u16` squirt count widens to `u32`.)doc")
        .def(py::init<>())
        .def_readwrite("init_value", &whiteout::models::wem::Sc2Property<whiteout::Vector3f>::initValue)
        .def_readwrite("null_value", &whiteout::models::wem::Sc2Property<whiteout::Vector3f>::nullValue)
    ;

    py::class_<whiteout::models::wem::Sc2Property<whiteout::Vector4f>>(m, "Sc2PropertyVector4f", R"doc(One animatable property of a StarCraft II emitter, at rest.

An M3 AnimRef without its link. `initValue` is what plays while no clip keys the property; the link — the animId and the keys — is the node's `Channel::EmitterProperty` channel, whose id is the AnimRef's own (§10.8.1).

`nullValue` is live, not padding: the engine retires an unkeyed `PAR_` whose rate and squirt, or a `RIB_` whose `active`, sit at their nulls before it emits anything. Shipped emitters rest every null at zero.

Colours are RGBA in 0..1, the channel convention; a `u16` squirt count widens to `u32`.)doc")
        .def(py::init<>())
        .def_readwrite("init_value", &whiteout::models::wem::Sc2Property<whiteout::Vector4f>::initValue)
        .def_readwrite("null_value", &whiteout::models::wem::Sc2Property<whiteout::Vector4f>::nullValue)
    ;

    py::class_<whiteout::models::wem::Sc2Property<whiteout::u32>>(m, "Sc2PropertyU32", R"doc(One animatable property of a StarCraft II emitter, at rest.

An M3 AnimRef without its link. `initValue` is what plays while no clip keys the property; the link — the animId and the keys — is the node's `Channel::EmitterProperty` channel, whose id is the AnimRef's own (§10.8.1).

`nullValue` is live, not padding: the engine retires an unkeyed `PAR_` whose rate and squirt, or a `RIB_` whose `active`, sit at their nulls before it emits anything. Shipped emitters rest every null at zero.

Colours are RGBA in 0..1, the channel convention; a `u16` squirt count widens to `u32`.)doc")
        .def(py::init<>())
        .def_readwrite("init_value", &whiteout::models::wem::Sc2Property<whiteout::u32>::initValue)
        .def_readwrite("null_value", &whiteout::models::wem::Sc2Property<whiteout::u32>::nullValue)
    ;

    py::class_<whiteout::models::wem::Sc2Property<whiteout::Vector2f>>(m, "Sc2PropertyVector2f", R"doc(One animatable property of a StarCraft II emitter, at rest.

An M3 AnimRef without its link. `initValue` is what plays while no clip keys the property; the link — the animId and the keys — is the node's `Channel::EmitterProperty` channel, whose id is the AnimRef's own (§10.8.1).

`nullValue` is live, not padding: the engine retires an unkeyed `PAR_` whose rate and squirt, or a `RIB_` whose `active`, sit at their nulls before it emits anything. Shipped emitters rest every null at zero.

Colours are RGBA in 0..1, the channel convention; a `u16` squirt count widens to `u32`.)doc")
        .def(py::init<>())
        .def_readwrite("init_value", &whiteout::models::wem::Sc2Property<whiteout::Vector2f>::initValue)
        .def_readwrite("null_value", &whiteout::models::wem::Sc2Property<whiteout::Vector2f>::nullValue)
    ;

    py::bind_vector<std::vector<whiteout::models::wem::AnimChannel>>(m, "VectorWemAnimChannel");
    py::bind_vector<std::vector<whiteout::models::wem::AnimSet>>(m, "VectorWemAnimSet");
    py::bind_vector<std::vector<whiteout::models::wem::AnimTag>>(m, "VectorWemAnimTag");
    py::bind_vector<std::vector<whiteout::models::wem::AssetKey>>(m, "VectorWemAssetKey");
    py::bind_vector<std::vector<whiteout::models::wem::Clip>>(m, "VectorWemClip");
    py::bind_vector<std::vector<whiteout::models::wem::ClipEvent>>(m, "VectorWemClipEvent");
}
