// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.textures;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.textures.internal.Native;

/**
 * Reads a TGA file or byte buffer and decodes it into a Texture.
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * Parser allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (TgaParser obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class TgaParser implements AutoCloseable {
    private static final long BYTES = 16L;

    final MemorySegment handle;
    final boolean owned;

    TgaParser(MemorySegment seg, boolean owned) {
        this.handle = (seg == null || seg.equals(MemorySegment.NULL))
            ? seg : seg.reinterpret(BYTES);
        this.owned = owned;
    }

    public TgaParser() {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_textures_TgaParser_new.invoke();
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("TgaParser allocation failed");
            this.handle = __raw.reinterpret(BYTES);
            this.owned = true;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    public static TgaParser createParseMode(TgaParseMode parseMode) {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_textures_TgaParser_new_parseMode.invoke(parseMode.value);
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("TgaParser allocation failed");
            return new TgaParser(__raw, true);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                Native.whiteout_textures_TgaParser_delete.invoke(handle);
            } catch (Throwable __ex) { throw new RuntimeException(__ex); }
        }
    }

    /**
     * Parse a TGA byte buffer.
     *
     * @param buffer byte[] input.
     * @return a fresh java.util.Optional<Texture> owning a native allocation.
     */
    public java.util.Optional<Texture> parse(byte[] buffer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment buffer_seg = arena.allocate(buffer.length * 1L);
            MemorySegment.copy(buffer, 0, buffer_seg, ValueLayout.JAVA_BYTE, 0, buffer.length);
            MemorySegment __h = (MemorySegment) Native.whiteout_textures_TgaParser_parse.invoke(handle, buffer_seg, (long) buffer.length);
            if (__h == null || __h.equals(MemorySegment.NULL)) return java.util.Optional.empty();
            return java.util.Optional.of(new Texture(__h, true));
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    /**
     * @return true if the last parse produced any issues.
     */
    public boolean hasIssues() {
        try {
        return ((int) Native.whiteout_textures_TgaParser_hasIssues.invoke(handle)) != 0;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override public String toString() {
        return "TgaParser@" + Long.toHexString(handle == null ? 0 : handle.address());
    }

}
