// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.textures;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.textures.internal.Native;

/**
 * Encodes a Texture into TGA format.
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * Writer allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (TgaWriter obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class TgaWriter implements AutoCloseable {
    private static final long BYTES = 16L;

    final MemorySegment handle;
    final boolean owned;

    TgaWriter(MemorySegment seg, boolean owned) {
        this.handle = (seg == null || seg.equals(MemorySegment.NULL))
            ? seg : seg.reinterpret(BYTES);
        this.owned = owned;
    }

    public TgaWriter() {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_textures_TgaWriter_new.invoke();
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("TgaWriter allocation failed");
            this.handle = __raw.reinterpret(BYTES);
            this.owned = true;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    public static TgaWriter createWriteMode(TgaWriteMode writeMode) {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_textures_TgaWriter_new_writeMode.invoke(writeMode.value);
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("TgaWriter allocation failed");
            return new TgaWriter(__raw, true);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                Native.whiteout_textures_TgaWriter_delete.invoke(handle);
            } catch (Throwable __ex) { throw new RuntimeException(__ex); }
        }
    }

    /**
     * Serialize the texture to a TGA byte buffer.
     *
     * @param texture Texture input.
     * @return a fresh byte[] copied out of native memory.
     */
    public byte[] write(Texture texture) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment __struct = (MemorySegment) Native.whiteout_textures_TgaWriter_write.invoke(arena, handle, texture == null ? MemorySegment.NULL : texture.handle);
            MemorySegment __data = __struct.get(ValueLayout.ADDRESS, 0);
            long __size = __struct.get(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS.byteSize());
            if (__data == null || __data.equals(MemorySegment.NULL)) return new byte[0];
            byte[] __out = __data.reinterpret(__size).toArray(ValueLayout.JAVA_BYTE);
            Native.whiteout_Bytes_free.invoke(__struct);
            return __out;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    /**
     * @return true if the last write produced any issues.
     */
    public boolean hasIssues() {
        try {
        return ((int) Native.whiteout_textures_TgaWriter_hasIssues.invoke(handle)) != 0;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override public String toString() {
        return "TgaWriter@" + Long.toHexString(handle == null ? 0 : handle.address());
    }

}
