// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.common;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;
import java.util.Objects;
import whiteout.common.internal.Native;

/**
 * A 3×3 row-major single-precision matrix backed by a native C struct (36 bytes of packed `float`). Use {@link #getAt(int,int)} and {@link #setAt(int,int,float)} for element access; static factories ({@link #identity()}, {@link #zero()}, …) wrap the native constructors.
 *
 * <p><b>Lifecycle.</b> Instances own a native allocation and must be
 * released with {@link #close()} (try-with-resources). Math methods
 * that return a fresh Matrix33f allocate new native memory which the
 * caller likewise owns.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. Don't share
 * the same instance across threads without external synchronization.
 */
public final class Matrix33f implements AutoCloseable {
    private static final long BYTES = 36L;

    final MemorySegment handle;
    final boolean owned;

    Matrix33f(MemorySegment seg, boolean owned) {
        this.handle = (seg == null || seg.equals(MemorySegment.NULL))
            ? seg : seg.reinterpret(BYTES);
        this.owned = owned;
    }

    public Matrix33f() {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_Matrix33f_new.invoke();
            this.handle = __raw.reinterpret(BYTES);
            this.owned = true;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try { Native.whiteout_Matrix33f_delete.invoke(handle); }
            catch (Throwable __ex) { throw new RuntimeException(__ex); }
        }
    }

    public static int dim() { return 3; }
    public float getAt(int row, int col) {
        return handle.get(ValueLayout.JAVA_FLOAT, ((long) row * 3 + col) * 4L);
    }
    public void setAt(int row, int col, float value) {
        handle.set(ValueLayout.JAVA_FLOAT, ((long) row * 3 + col) * 4L, value);
    }
    /**
     * Component-wise sum.
     * @param other Matrix33f input.
     * @return a fresh Matrix33f owning a native allocation.
     */
    public Matrix33f add(Matrix33f other) {
        try {
            MemorySegment __h = (MemorySegment) Native.whiteout_Matrix33f_add.invoke(handle, other.handle);
            return new Matrix33f(__h, true);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Component-wise difference.
     * @param other Matrix33f input.
     * @return a fresh Matrix33f owning a native allocation.
     */
    public Matrix33f sub(Matrix33f other) {
        try {
            MemorySegment __h = (MemorySegment) Native.whiteout_Matrix33f_sub.invoke(handle, other.handle);
            return new Matrix33f(__h, true);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Component-wise product (Hamilton product for Quaternion).
     * @param other Matrix33f input.
     * @return a fresh Matrix33f owning a native allocation.
     */
    public Matrix33f mul(Matrix33f other) {
        try {
            MemorySegment __h = (MemorySegment) Native.whiteout_Matrix33f_mul.invoke(handle, other.handle);
            return new Matrix33f(__h, true);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Scale every component by {@code scalar}.
     * @param scalar float input.
     * @return a fresh Matrix33f owning a native allocation.
     */
    public Matrix33f mulScalar(float scalar) {
        try {
            MemorySegment __h = (MemorySegment) Native.whiteout_Matrix33f_mul_scalar.invoke(handle, scalar);
            return new Matrix33f(__h, true);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Identity element (no rotation / identity matrix).
     * @return a fresh Matrix33f owning a native allocation.
     */
    public static Matrix33f identity() {
        try {
            MemorySegment __h = (MemorySegment) Native.whiteout_Matrix33f_identity.invoke();
            return new Matrix33f(__h, true);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Zero-filled matrix.
     * @return a fresh Matrix33f owning a native allocation.
     */
    public static Matrix33f zero() {
        try {
            MemorySegment __h = (MemorySegment) Native.whiteout_Matrix33f_zero.invoke();
            return new Matrix33f(__h, true);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    @Override
    public String toString() {
        StringBuilder __sb = new StringBuilder("Matrix33f[\n");
        for (int __r = 0; __r < 3; __r++) {
            __sb.append("  ");
            for (int __c = 0; __c < 3; __c++) {
                __sb.append(getAt(__r, __c));
                if (__c < 3 - 1) __sb.append(", ");
            }
            __sb.append("\n");
        }
        return __sb.append("]").toString();
    }

}
