// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.casc.internal;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import whiteout.common.internal.NativeCommon;

/** FFM MethodHandle registry for this module. Internal — for codegen use. */
public final class Native {
    private Native() {}

    public static final MemoryLayout BYTES_LAYOUT = NativeCommon.BYTES_LAYOUT;
    public static final MemoryLayout CSTRING_LAYOUT = NativeCommon.CSTRING_LAYOUT;
    public static final MethodHandle whiteout_Bytes_free = NativeCommon.whiteout_Bytes_free;
    public static final MethodHandle whiteout_CString_free = NativeCommon.whiteout_CString_free;

    static MethodHandle find(String name, FunctionDescriptor fd) {
        return NativeCommon.find(name, fd);
    }

    // -- CascCreateOptions --
    public static final MethodHandle whiteout_casc_CascCreateOptions_new = find(
        "whiteout_casc_CascCreateOptions_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascCreateOptions_delete = find(
        "whiteout_casc_CascCreateOptions_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascCreateOptions_get_product = find("whiteout_casc_CascCreateOptions_get_product", FunctionDescriptor.of(CSTRING_LAYOUT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascCreateOptions_set_product = find("whiteout_casc_CascCreateOptions_set_product", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascCreateOptions_get_version = find("whiteout_casc_CascCreateOptions_get_version", FunctionDescriptor.of(CSTRING_LAYOUT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascCreateOptions_set_version = find("whiteout_casc_CascCreateOptions_set_version", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascCreateOptions_get_archiveMaxSize = find("whiteout_casc_CascCreateOptions_get_archiveMaxSize", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascCreateOptions_set_archiveMaxSize = find("whiteout_casc_CascCreateOptions_set_archiveMaxSize", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_casc_CascCreateOptions_get_blteFrameSize = find("whiteout_casc_CascCreateOptions_get_blteFrameSize", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascCreateOptions_set_blteFrameSize = find("whiteout_casc_CascCreateOptions_set_blteFrameSize", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_casc_CascCreateOptions_get_rootFormat = find("whiteout_casc_CascCreateOptions_get_rootFormat", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascCreateOptions_set_rootFormat = find("whiteout_casc_CascCreateOptions_set_rootFormat", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    // -- CascWriteOptions --
    public static final MethodHandle whiteout_casc_CascWriteOptions_new = find(
        "whiteout_casc_CascWriteOptions_new", FunctionDescriptor.of(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascWriteOptions_delete = find(
        "whiteout_casc_CascWriteOptions_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascWriteOptions_get_localeFlags = find("whiteout_casc_CascWriteOptions_get_localeFlags", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascWriteOptions_set_localeFlags = find("whiteout_casc_CascWriteOptions_set_localeFlags", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_casc_CascWriteOptions_get_contentFlags = find("whiteout_casc_CascWriteOptions_get_contentFlags", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascWriteOptions_set_contentFlags = find("whiteout_casc_CascWriteOptions_set_contentFlags", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_casc_CascWriteOptions_get_compress = find("whiteout_casc_CascWriteOptions_get_compress", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascWriteOptions_set_compress = find("whiteout_casc_CascWriteOptions_set_compress", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));

    // -- CascStorage --
    public static final MethodHandle whiteout_casc_CascStorage_delete = find(
        "whiteout_casc_CascStorage_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_open = find(
        "whiteout_casc_CascStorage_open", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_open_path_localeMask_pool = find(
        "whiteout_casc_CascStorage_open_path_localeMask_pool", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_isLocal = find(
        "whiteout_casc_CascStorage_isLocal", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_isOnline = find(
        "whiteout_casc_CascStorage_isOnline", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_isWritable = find(
        "whiteout_casc_CascStorage_isWritable", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_rootFormat = find(
        "whiteout_casc_CascStorage_rootFormat", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_readFile = find(
        "whiteout_casc_CascStorage_readFile", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_readFile_cascPath_localeFlags_openFlags = find(
        "whiteout_casc_CascStorage_readFile_cascPath_localeFlags_openFlags", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_casc_CascStorage_readFile_fileId_hint = find(
        "whiteout_casc_CascStorage_readFile_fileId_hint", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_casc_CascStorage_readFile_fileId_localeFlags_openFlags_hint = find(
        "whiteout_casc_CascStorage_readFile_fileId_localeFlags_openFlags_hint", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_casc_CascStorage_fileExists = find(
        "whiteout_casc_CascStorage_fileExists", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_fileExists_fileId_hint = find(
        "whiteout_casc_CascStorage_fileExists_fileId_hint", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_casc_CascStorage_listFiles = find(
        "whiteout_casc_CascStorage_listFiles", FunctionDescriptor.of(BYTES_LAYOUT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_importKeysFromString = find(
        "whiteout_casc_CascStorage_importKeysFromString", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_importKeysFromFile = find(
        "whiteout_casc_CascStorage_importKeysFromFile", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_flushCache = find(
        "whiteout_casc_CascStorage_flushCache", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_prefetch = find(
        "whiteout_casc_CascStorage_prefetch", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorage_lastError = find(
        "whiteout_casc_CascStorage_lastError", FunctionDescriptor.of(ValueLayout.JAVA_INT));

    // -- CascStorageWritable --
    public static final MethodHandle whiteout_casc_CascStorageWritable_delete = find(
        "whiteout_casc_CascStorageWritable_delete", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorageWritable_create = find(
        "whiteout_casc_CascStorageWritable_create", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorageWritable_writeFile = find(
        "whiteout_casc_CascStorageWritable_writeFile", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorageWritable_writeFile_fileId_data_opts_hint = find(
        "whiteout_casc_CascStorageWritable_writeFile_fileId_data_opts_hint", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_casc_CascStorageWritable_deleteFile = find(
        "whiteout_casc_CascStorageWritable_deleteFile", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorageWritable_deleteFile_fileId_hint = find(
        "whiteout_casc_CascStorageWritable_deleteFile_fileId_hint", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    public static final MethodHandle whiteout_casc_CascStorageWritable_save = find(
        "whiteout_casc_CascStorageWritable_save", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    public static final MethodHandle whiteout_casc_CascStorageWritable_save_path = find(
        "whiteout_casc_CascStorageWritable_save_path", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));

}
