/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2026 Fernando Sahmkow */
/* AUTOGENERATED by tools/codegen/emit_c.py — do not edit. */
/* Regenerate via:  python -m tools.codegen.codegen m2 --backend c-header */

#ifndef WHITEOUT_M2_H
#define WHITEOUT_M2_H

#include "whiteout_c_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ── Enums ─────────────────────────────────────────────────── */

typedef enum {
    whiteout_m2_InterpolationType_None,
    whiteout_m2_InterpolationType_Linear,
    whiteout_m2_InterpolationType_Bezier,
    whiteout_m2_InterpolationType_Hermite,
} whiteout_m2_InterpolationType;

typedef enum {
    whiteout_m2_GlobalFlag_None,
    whiteout_m2_GlobalFlag_TiltX,
    whiteout_m2_GlobalFlag_TiltY,
    whiteout_m2_GlobalFlag_AddBackReferences,
    whiteout_m2_GlobalFlag_UseTextureCombinerCombos,
    whiteout_m2_GlobalFlag_IsCamera,
    whiteout_m2_GlobalFlag_Unused,
    whiteout_m2_GlobalFlag_Unk_0x80,
    whiteout_m2_GlobalFlag_LoadPhysicsData,
    whiteout_m2_GlobalFlag_NewParticleRecord,
    whiteout_m2_GlobalFlag_Unk_0x400,
    whiteout_m2_GlobalFlag_TextureTransformsUsesBoneSequences,
    whiteout_m2_GlobalFlag_Unk_0x1000,
    whiteout_m2_GlobalFlag_ChunkedAnimFiles,
    whiteout_m2_GlobalFlag_UpgradedFormat,
} whiteout_m2_GlobalFlag;

typedef enum {
    whiteout_m2_SequenceFlag_None,
    whiteout_m2_SequenceFlag_TiltIn,
    whiteout_m2_SequenceFlag_TiltOut,
    whiteout_m2_SequenceFlag_TiltFixed,
    whiteout_m2_SequenceFlag_Looping,
    whiteout_m2_SequenceFlag_IsAlias,
    whiteout_m2_SequenceFlag_AnimatedSetup,
    whiteout_m2_SequenceFlag_StoredAnimated,
    whiteout_m2_SequenceFlag_EnableComposite,
} whiteout_m2_SequenceFlag;

typedef enum {
    whiteout_m2_BoneFlag_None,
    whiteout_m2_BoneFlag_IgnoreParentTranslate,
    whiteout_m2_BoneFlag_IgnoreParentScale,
    whiteout_m2_BoneFlag_IgnoreParentRotation,
    whiteout_m2_BoneFlag_SphericalBillboard,
    whiteout_m2_BoneFlag_CylindricalBillboardX,
    whiteout_m2_BoneFlag_CylindricalBillboardY,
    whiteout_m2_BoneFlag_CylindricalBillboardZ,
    whiteout_m2_BoneFlag_Transformed,
    whiteout_m2_BoneFlag_Kinematic,
    whiteout_m2_BoneFlag_HelmetAnimScaled,
} whiteout_m2_BoneFlag;

typedef enum {
    whiteout_m2_MaterialFlag_None,
    whiteout_m2_MaterialFlag_Unlit,
    whiteout_m2_MaterialFlag_Unfogged,
    whiteout_m2_MaterialFlag_TwoSided,
    whiteout_m2_MaterialFlag_DepthTest,
    whiteout_m2_MaterialFlag_DepthWrite,
    whiteout_m2_MaterialFlag_NoAlphaComposite,
} whiteout_m2_MaterialFlag;

typedef enum {
    whiteout_m2_ParticleEmitterType_Plane,
    whiteout_m2_ParticleEmitterType_Sphere,
    whiteout_m2_ParticleEmitterType_Spline,
    whiteout_m2_ParticleEmitterType_Bone,
} whiteout_m2_ParticleEmitterType;

typedef enum {
    whiteout_m2_ParticleBlending_Opaque,
    whiteout_m2_ParticleBlending_AlphaBlend,
    whiteout_m2_ParticleBlending_Additive,
    whiteout_m2_ParticleBlending_AlphaTest,
    whiteout_m2_ParticleBlending_AdditiveAlphaTest,
} whiteout_m2_ParticleBlending;

typedef enum {
    whiteout_m2_ParticleFlag_None,
    whiteout_m2_ParticleFlag_Shaded,
    whiteout_m2_ParticleFlag_SortParticles,
    whiteout_m2_ParticleFlag_VelocityOrient,
    whiteout_m2_ParticleFlag_Unshaded,
    whiteout_m2_ParticleFlag_WorldSpace,
    whiteout_m2_ParticleFlag_InheritBoneScale,
    whiteout_m2_ParticleFlag_InheritVelocity,
    whiteout_m2_ParticleFlag_ImplosionFilter,
    whiteout_m2_ParticleFlag_HemisphereUpDirection,
    whiteout_m2_ParticleFlag_NegateSpinRandom,
    whiteout_m2_ParticleFlag_ClampTailToAge,
    whiteout_m2_ParticleFlag_InheritPosition,
    whiteout_m2_ParticleFlag_XYQuad,
    whiteout_m2_ParticleFlag_ProjectParticle,
    whiteout_m2_ParticleFlag_FollowPosition,
    whiteout_m2_ParticleFlag_Squirt,
    whiteout_m2_ParticleFlag_ChooseRandomTexture,
    whiteout_m2_ParticleFlag_HeadStyle,
    whiteout_m2_ParticleFlag_TailStyle,
    whiteout_m2_ParticleFlag_UnscaledSizeVariation,
    whiteout_m2_ParticleFlag_Unfogged,
    whiteout_m2_ParticleFlag_RandFlipbookStart,
    whiteout_m2_ParticleFlag_Unk_0x400000,
    whiteout_m2_ParticleFlag_CompressedGravity,
    whiteout_m2_ParticleFlag_BoneGeneratorBone,
    whiteout_m2_ParticleFlag_NoGlobalViewScale,
    whiteout_m2_ParticleFlag_LodIgnoreDistance,
    whiteout_m2_ParticleFlag_OffsetHeadBySpin,
    whiteout_m2_ParticleFlag_MultiTexture,
    whiteout_m2_ParticleFlag_MultitexUseModx4,
    whiteout_m2_ParticleFlag_MultitexUse3Colors,
    whiteout_m2_ParticleFlag_DynamicWind,
} whiteout_m2_ParticleFlag;

/* ── Opaque handles ───────────────────────────────────────── */

typedef struct whiteout_M2CompatQuaternion whiteout_M2CompatQuaternion;
typedef struct whiteout_M2ColorBGRA whiteout_M2ColorBGRA;
typedef struct whiteout_M2Extent whiteout_M2Extent;
typedef struct whiteout_M2AnimationTrackBase whiteout_M2AnimationTrackBase;
typedef struct whiteout_M2ParticleEmitterExtension whiteout_M2ParticleEmitterExtension;
typedef struct whiteout_M2LodProfile whiteout_M2LodProfile;
typedef struct whiteout_M2WaterfallData whiteout_M2WaterfallData;
typedef struct whiteout_M2ParticleGeosetData whiteout_M2ParticleGeosetData;
typedef struct whiteout_M2EdgeFadeData whiteout_M2EdgeFadeData;
typedef struct whiteout_M2DistanceFadeData whiteout_M2DistanceFadeData;
typedef struct whiteout_M2DetailedLightData whiteout_M2DetailedLightData;
typedef struct whiteout_M2DebugOcclusionData whiteout_M2DebugOcclusionData;
typedef struct whiteout_M2TexturedLightData whiteout_M2TexturedLightData;
typedef struct whiteout_M2PhysicsCollision whiteout_M2PhysicsCollision;
typedef struct whiteout_M2SkinSection whiteout_M2SkinSection;
typedef struct whiteout_M2Batch whiteout_M2Batch;
typedef struct whiteout_M2ShadowBatch whiteout_M2ShadowBatch;
typedef struct whiteout_M2SkinProfile whiteout_M2SkinProfile;
typedef struct whiteout_M2GlobalFlags whiteout_M2GlobalFlags;
typedef struct whiteout_M2GlobalSequence whiteout_M2GlobalSequence;
typedef struct whiteout_M2Sequence whiteout_M2Sequence;
typedef struct whiteout_M2Vertex whiteout_M2Vertex;
typedef struct whiteout_M2Bone whiteout_M2Bone;
typedef struct whiteout_M2Texture whiteout_M2Texture;
typedef struct whiteout_M2Material whiteout_M2Material;
typedef struct whiteout_M2TextureWeight whiteout_M2TextureWeight;
typedef struct whiteout_M2TextureTransform whiteout_M2TextureTransform;
typedef struct whiteout_M2ColorAnimation whiteout_M2ColorAnimation;
typedef struct whiteout_M2Light whiteout_M2Light;
typedef struct whiteout_M2CameraSpline whiteout_M2CameraSpline;
typedef struct whiteout_M2Camera whiteout_M2Camera;
typedef struct whiteout_M2Attachment whiteout_M2Attachment;
typedef struct whiteout_M2RibbonEmitter whiteout_M2RibbonEmitter;
typedef struct whiteout_M2Box whiteout_M2Box;
typedef struct whiteout_M2ParticleEmitter whiteout_M2ParticleEmitter;
typedef struct whiteout_M2Event whiteout_M2Event;
typedef struct whiteout_M2Model whiteout_M2Model;
typedef struct whiteout_M2AnimationTrackVector3f whiteout_M2AnimationTrackVector3f;
typedef struct whiteout_M2AnimationTrackM2CompatQuaternion whiteout_M2AnimationTrackM2CompatQuaternion;
typedef struct whiteout_M2AnimationTrackI16 whiteout_M2AnimationTrackI16;
typedef struct whiteout_M2AnimationTrackF32 whiteout_M2AnimationTrackF32;
typedef struct whiteout_M2AnimationTrackU8 whiteout_M2AnimationTrackU8;
typedef struct whiteout_M2AnimationTrackM2CameraSpline whiteout_M2AnimationTrackM2CameraSpline;
typedef struct whiteout_M2AnimationTrackU16 whiteout_M2AnimationTrackU16;
typedef struct whiteout_M2ParticleAnimationTrackVector3f whiteout_M2ParticleAnimationTrackVector3f;
typedef struct whiteout_M2ParticleAnimationTrackVector2f whiteout_M2ParticleAnimationTrackVector2f;

/* ── M2CompatQuaternion ─────────────────────────────────────────────── */

whiteout_M2CompatQuaternion* whiteout_m2_M2CompatQuaternion_new(void);
void whiteout_m2_M2CompatQuaternion_delete(whiteout_M2CompatQuaternion* self);


/* ── M2ColorBGRA ─────────────────────────────────────────────── */

whiteout_M2ColorBGRA* whiteout_m2_M2ColorBGRA_new(void);
void whiteout_m2_M2ColorBGRA_delete(whiteout_M2ColorBGRA* self);


/* ── M2Extent ─────────────────────────────────────────────── */

whiteout_M2Extent* whiteout_m2_M2Extent_new(void);
void whiteout_m2_M2Extent_delete(whiteout_M2Extent* self);

whiteout_Vector3f* whiteout_m2_M2Extent_get_minimum(whiteout_M2Extent* self);
void whiteout_m2_M2Extent_set_minimum(whiteout_M2Extent* self, const whiteout_Vector3f* value);
whiteout_Vector3f* whiteout_m2_M2Extent_get_maximum(whiteout_M2Extent* self);
void whiteout_m2_M2Extent_set_maximum(whiteout_M2Extent* self, const whiteout_Vector3f* value);
float whiteout_m2_M2Extent_get_sphereRadius(const whiteout_M2Extent* self);
void whiteout_m2_M2Extent_set_sphereRadius(whiteout_M2Extent* self, float value);

/* ── M2AnimationTrackBase ─────────────────────────────────────────────── */

whiteout_M2AnimationTrackBase* whiteout_m2_M2AnimationTrackBase_new(void);
void whiteout_m2_M2AnimationTrackBase_delete(whiteout_M2AnimationTrackBase* self);

int32_t whiteout_m2_M2AnimationTrackBase_get_interpolationType(const whiteout_M2AnimationTrackBase* self);
void whiteout_m2_M2AnimationTrackBase_set_interpolationType(whiteout_M2AnimationTrackBase* self, int32_t value);
uint16_t whiteout_m2_M2AnimationTrackBase_get_globalSequenceId(const whiteout_M2AnimationTrackBase* self);
void whiteout_m2_M2AnimationTrackBase_set_globalSequenceId(whiteout_M2AnimationTrackBase* self, uint16_t value);
size_t whiteout_m2_M2AnimationTrackBase_get_timestamps_count(const whiteout_M2AnimationTrackBase* self);
size_t whiteout_m2_M2AnimationTrackBase_get_timestamps_inner_count(const whiteout_M2AnimationTrackBase* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackBase_resize_timestamps(whiteout_M2AnimationTrackBase* self, size_t count);
void whiteout_m2_M2AnimationTrackBase_resize_timestamps_inner(whiteout_M2AnimationTrackBase* self, size_t outer_idx, size_t inner_count);
const uint32_t* whiteout_m2_M2AnimationTrackBase_get_timestamps_inner_data(const whiteout_M2AnimationTrackBase* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackBase_assign_timestamps_inner(whiteout_M2AnimationTrackBase* self, size_t outer_idx, const uint32_t* data, size_t count);

/* ── M2ParticleEmitterExtension ─────────────────────────────────────────────── */

whiteout_M2ParticleEmitterExtension* whiteout_m2_M2ParticleEmitterExtension_new(void);
void whiteout_m2_M2ParticleEmitterExtension_delete(whiteout_M2ParticleEmitterExtension* self);

float whiteout_m2_M2ParticleEmitterExtension_get_zSource(const whiteout_M2ParticleEmitterExtension* self);
void whiteout_m2_M2ParticleEmitterExtension_set_zSource(whiteout_M2ParticleEmitterExtension* self, float value);
float whiteout_m2_M2ParticleEmitterExtension_get_colorMult(const whiteout_M2ParticleEmitterExtension* self);
void whiteout_m2_M2ParticleEmitterExtension_set_colorMult(whiteout_M2ParticleEmitterExtension* self, float value);
float whiteout_m2_M2ParticleEmitterExtension_get_alphaMult(const whiteout_M2ParticleEmitterExtension* self);
void whiteout_m2_M2ParticleEmitterExtension_set_alphaMult(whiteout_M2ParticleEmitterExtension* self, float value);

/* ── M2LodProfile ─────────────────────────────────────────────── */

whiteout_M2LodProfile* whiteout_m2_M2LodProfile_new(void);
void whiteout_m2_M2LodProfile_delete(whiteout_M2LodProfile* self);

uint16_t whiteout_m2_M2LodProfile_get_flags(const whiteout_M2LodProfile* self);
void whiteout_m2_M2LodProfile_set_flags(whiteout_M2LodProfile* self, uint16_t value);
uint16_t whiteout_m2_M2LodProfile_get_numLodLevels(const whiteout_M2LodProfile* self);
void whiteout_m2_M2LodProfile_set_numLodLevels(whiteout_M2LodProfile* self, uint16_t value);
float whiteout_m2_M2LodProfile_get_lodDistance(const whiteout_M2LodProfile* self);
void whiteout_m2_M2LodProfile_set_lodDistance(whiteout_M2LodProfile* self, float value);
size_t whiteout_m2_M2LodProfile_particleBoneLod_size(void);
uint8_t whiteout_m2_M2LodProfile_get_particleBoneLod_at(const whiteout_M2LodProfile* self, size_t index);
void whiteout_m2_M2LodProfile_set_particleBoneLod_at(whiteout_M2LodProfile* self, size_t index, uint8_t value);
uint8_t whiteout_m2_M2LodProfile_get_reserved0(const whiteout_M2LodProfile* self);
void whiteout_m2_M2LodProfile_set_reserved0(whiteout_M2LodProfile* self, uint8_t value);
uint8_t whiteout_m2_M2LodProfile_get_lodFlags(const whiteout_M2LodProfile* self);
void whiteout_m2_M2LodProfile_set_lodFlags(whiteout_M2LodProfile* self, uint8_t value);
uint8_t whiteout_m2_M2LodProfile_get_lodBatchCount(const whiteout_M2LodProfile* self);
void whiteout_m2_M2LodProfile_set_lodBatchCount(whiteout_M2LodProfile* self, uint8_t value);
uint8_t whiteout_m2_M2LodProfile_get_reserved1(const whiteout_M2LodProfile* self);
void whiteout_m2_M2LodProfile_set_reserved1(whiteout_M2LodProfile* self, uint8_t value);

/* ── M2WaterfallData ─────────────────────────────────────────────── */

whiteout_M2WaterfallData* whiteout_m2_M2WaterfallData_new(void);
void whiteout_m2_M2WaterfallData_delete(whiteout_M2WaterfallData* self);

float whiteout_m2_M2WaterfallData_get_bumpScale(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_bumpScale(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_value0_x(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value0_x(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_value0_y(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value0_y(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_value0_z(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value0_z(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_value1_w(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value1_w(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_value0_w(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value0_w(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_value1_x(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value1_x(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_value1_y(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value1_y(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_value2_w(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value2_w(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_value3_y(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value3_y(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_value3_x(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value3_x(whiteout_M2WaterfallData* self, float value);
whiteout_Vector4f* whiteout_m2_M2WaterfallData_get_baseColor(whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_baseColor(whiteout_M2WaterfallData* self, const whiteout_Vector4f* value);
uint16_t whiteout_m2_M2WaterfallData_get_flags(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_flags(whiteout_M2WaterfallData* self, uint16_t value);
uint16_t whiteout_m2_M2WaterfallData_get_unknown0(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_unknown0(whiteout_M2WaterfallData* self, uint16_t value);
float whiteout_m2_M2WaterfallData_get_value3_w(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value3_w(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_value3_z(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value3_z(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_value4_y(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_value4_y(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_unknown1(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_unknown1(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_unknown2(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_unknown2(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_unknown3(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_unknown3(whiteout_M2WaterfallData* self, float value);
float whiteout_m2_M2WaterfallData_get_unknown4(const whiteout_M2WaterfallData* self);
void whiteout_m2_M2WaterfallData_set_unknown4(whiteout_M2WaterfallData* self, float value);

/* ── M2ParticleGeosetData ─────────────────────────────────────────────── */

whiteout_M2ParticleGeosetData* whiteout_m2_M2ParticleGeosetData_new(void);
void whiteout_m2_M2ParticleGeosetData_delete(whiteout_M2ParticleGeosetData* self);

uint16_t whiteout_m2_M2ParticleGeosetData_get_geoset(const whiteout_M2ParticleGeosetData* self);
void whiteout_m2_M2ParticleGeosetData_set_geoset(whiteout_M2ParticleGeosetData* self, uint16_t value);

/* ── M2EdgeFadeData ─────────────────────────────────────────────── */

whiteout_M2EdgeFadeData* whiteout_m2_M2EdgeFadeData_new(void);
void whiteout_m2_M2EdgeFadeData_delete(whiteout_M2EdgeFadeData* self);

size_t whiteout_m2_M2EdgeFadeData_value0_size(void);
float whiteout_m2_M2EdgeFadeData_get_value0_at(const whiteout_M2EdgeFadeData* self, size_t index);
void whiteout_m2_M2EdgeFadeData_set_value0_at(whiteout_M2EdgeFadeData* self, size_t index, float value);
float whiteout_m2_M2EdgeFadeData_get_value8(const whiteout_M2EdgeFadeData* self);
void whiteout_m2_M2EdgeFadeData_set_value8(whiteout_M2EdgeFadeData* self, float value);
size_t whiteout_m2_M2EdgeFadeData_valueC_size(void);
uint8_t whiteout_m2_M2EdgeFadeData_get_valueC_at(const whiteout_M2EdgeFadeData* self, size_t index);
void whiteout_m2_M2EdgeFadeData_set_valueC_at(whiteout_M2EdgeFadeData* self, size_t index, uint8_t value);

/* ── M2DistanceFadeData ─────────────────────────────────────────────── */

whiteout_M2DistanceFadeData* whiteout_m2_M2DistanceFadeData_new(void);
void whiteout_m2_M2DistanceFadeData_delete(whiteout_M2DistanceFadeData* self);

float whiteout_m2_M2DistanceFadeData_get_squaredFarDist(const whiteout_M2DistanceFadeData* self);
void whiteout_m2_M2DistanceFadeData_set_squaredFarDist(whiteout_M2DistanceFadeData* self, float value);
float whiteout_m2_M2DistanceFadeData_get_squaredNearDist(const whiteout_M2DistanceFadeData* self);
void whiteout_m2_M2DistanceFadeData_set_squaredNearDist(whiteout_M2DistanceFadeData* self, float value);
size_t whiteout_m2_M2DistanceFadeData_reserved_size(void);
uint32_t whiteout_m2_M2DistanceFadeData_get_reserved_at(const whiteout_M2DistanceFadeData* self, size_t index);
void whiteout_m2_M2DistanceFadeData_set_reserved_at(whiteout_M2DistanceFadeData* self, size_t index, uint32_t value);

/* ── M2DetailedLightData ─────────────────────────────────────────────── */

whiteout_M2DetailedLightData* whiteout_m2_M2DetailedLightData_new(void);
void whiteout_m2_M2DetailedLightData_delete(whiteout_M2DetailedLightData* self);

uint16_t whiteout_m2_M2DetailedLightData_get_flags(const whiteout_M2DetailedLightData* self);
void whiteout_m2_M2DetailedLightData_set_flags(whiteout_M2DetailedLightData* self, uint16_t value);
uint16_t whiteout_m2_M2DetailedLightData_get_unknown0(const whiteout_M2DetailedLightData* self);
void whiteout_m2_M2DetailedLightData_set_unknown0(whiteout_M2DetailedLightData* self, uint16_t value);
uint32_t whiteout_m2_M2DetailedLightData_get_unknown1(const whiteout_M2DetailedLightData* self);
void whiteout_m2_M2DetailedLightData_set_unknown1(whiteout_M2DetailedLightData* self, uint32_t value);

/* ── M2DebugOcclusionData ─────────────────────────────────────────────── */

whiteout_M2DebugOcclusionData* whiteout_m2_M2DebugOcclusionData_new(void);
void whiteout_m2_M2DebugOcclusionData_delete(whiteout_M2DebugOcclusionData* self);

float whiteout_m2_M2DebugOcclusionData_get_unknown1_1(const whiteout_M2DebugOcclusionData* self);
void whiteout_m2_M2DebugOcclusionData_set_unknown1_1(whiteout_M2DebugOcclusionData* self, float value);
float whiteout_m2_M2DebugOcclusionData_get_unknown1_2(const whiteout_M2DebugOcclusionData* self);
void whiteout_m2_M2DebugOcclusionData_set_unknown1_2(whiteout_M2DebugOcclusionData* self, float value);
uint32_t whiteout_m2_M2DebugOcclusionData_get_unknown1_3(const whiteout_M2DebugOcclusionData* self);
void whiteout_m2_M2DebugOcclusionData_set_unknown1_3(whiteout_M2DebugOcclusionData* self, uint32_t value);
uint32_t whiteout_m2_M2DebugOcclusionData_get_unknown1_4(const whiteout_M2DebugOcclusionData* self);
void whiteout_m2_M2DebugOcclusionData_set_unknown1_4(whiteout_M2DebugOcclusionData* self, uint32_t value);

/* ── M2TexturedLightData ─────────────────────────────────────────────── */

whiteout_M2TexturedLightData* whiteout_m2_M2TexturedLightData_new(void);
void whiteout_m2_M2TexturedLightData_delete(whiteout_M2TexturedLightData* self);

float whiteout_m2_M2TexturedLightData_get_unknown0(const whiteout_M2TexturedLightData* self);
void whiteout_m2_M2TexturedLightData_set_unknown0(whiteout_M2TexturedLightData* self, float value);
float whiteout_m2_M2TexturedLightData_get_unknown1(const whiteout_M2TexturedLightData* self);
void whiteout_m2_M2TexturedLightData_set_unknown1(whiteout_M2TexturedLightData* self, float value);
int32_t whiteout_m2_M2TexturedLightData_get_textureLookup(const whiteout_M2TexturedLightData* self);
void whiteout_m2_M2TexturedLightData_set_textureLookup(whiteout_M2TexturedLightData* self, int32_t value);
int32_t whiteout_m2_M2TexturedLightData_get_unknown2(const whiteout_M2TexturedLightData* self);
void whiteout_m2_M2TexturedLightData_set_unknown2(whiteout_M2TexturedLightData* self, int32_t value);

/* ── M2PhysicsCollision ─────────────────────────────────────────────── */

whiteout_M2PhysicsCollision* whiteout_m2_M2PhysicsCollision_new(void);
void whiteout_m2_M2PhysicsCollision_delete(whiteout_M2PhysicsCollision* self);

size_t whiteout_m2_M2PhysicsCollision_get_vertexPositions_count(const whiteout_M2PhysicsCollision* self);
void whiteout_m2_M2PhysicsCollision_resize_vertexPositions(whiteout_M2PhysicsCollision* self, size_t count);
const float* whiteout_m2_M2PhysicsCollision_get_vertexPositions_data(const whiteout_M2PhysicsCollision* self);
void whiteout_m2_M2PhysicsCollision_assign_vertexPositions(whiteout_M2PhysicsCollision* self, const float* data, size_t count);
size_t whiteout_m2_M2PhysicsCollision_get_faceNormals_count(const whiteout_M2PhysicsCollision* self);
void whiteout_m2_M2PhysicsCollision_resize_faceNormals(whiteout_M2PhysicsCollision* self, size_t count);
const float* whiteout_m2_M2PhysicsCollision_get_faceNormals_data(const whiteout_M2PhysicsCollision* self);
void whiteout_m2_M2PhysicsCollision_assign_faceNormals(whiteout_M2PhysicsCollision* self, const float* data, size_t count);
size_t whiteout_m2_M2PhysicsCollision_get_indices_count(const whiteout_M2PhysicsCollision* self);
void whiteout_m2_M2PhysicsCollision_resize_indices(whiteout_M2PhysicsCollision* self, size_t count);
const int16_t* whiteout_m2_M2PhysicsCollision_get_indices_data(const whiteout_M2PhysicsCollision* self);
void whiteout_m2_M2PhysicsCollision_assign_indices(whiteout_M2PhysicsCollision* self, const int16_t* data, size_t count);
size_t whiteout_m2_M2PhysicsCollision_get_flags_count(const whiteout_M2PhysicsCollision* self);
void whiteout_m2_M2PhysicsCollision_resize_flags(whiteout_M2PhysicsCollision* self, size_t count);
const int16_t* whiteout_m2_M2PhysicsCollision_get_flags_data(const whiteout_M2PhysicsCollision* self);
void whiteout_m2_M2PhysicsCollision_assign_flags(whiteout_M2PhysicsCollision* self, const int16_t* data, size_t count);

/* ── M2SkinSection ─────────────────────────────────────────────── */

whiteout_M2SkinSection* whiteout_m2_M2SkinSection_new(void);
void whiteout_m2_M2SkinSection_delete(whiteout_M2SkinSection* self);

uint16_t whiteout_m2_M2SkinSection_get_skinSectionId(const whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_skinSectionId(whiteout_M2SkinSection* self, uint16_t value);
uint16_t whiteout_m2_M2SkinSection_get_level(const whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_level(whiteout_M2SkinSection* self, uint16_t value);
uint16_t whiteout_m2_M2SkinSection_get_vertexStart(const whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_vertexStart(whiteout_M2SkinSection* self, uint16_t value);
uint16_t whiteout_m2_M2SkinSection_get_vertexCount(const whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_vertexCount(whiteout_M2SkinSection* self, uint16_t value);
uint16_t whiteout_m2_M2SkinSection_get_indexStart(const whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_indexStart(whiteout_M2SkinSection* self, uint16_t value);
uint16_t whiteout_m2_M2SkinSection_get_indexCount(const whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_indexCount(whiteout_M2SkinSection* self, uint16_t value);
uint16_t whiteout_m2_M2SkinSection_get_boneCount(const whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_boneCount(whiteout_M2SkinSection* self, uint16_t value);
uint16_t whiteout_m2_M2SkinSection_get_boneComboIndex(const whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_boneComboIndex(whiteout_M2SkinSection* self, uint16_t value);
uint16_t whiteout_m2_M2SkinSection_get_boneInfluences(const whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_boneInfluences(whiteout_M2SkinSection* self, uint16_t value);
uint16_t whiteout_m2_M2SkinSection_get_centerBoneIndex(const whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_centerBoneIndex(whiteout_M2SkinSection* self, uint16_t value);
whiteout_Vector3f* whiteout_m2_M2SkinSection_get_centerPosition(whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_centerPosition(whiteout_M2SkinSection* self, const whiteout_Vector3f* value);
whiteout_Vector3f* whiteout_m2_M2SkinSection_get_sortCenterPosition(whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_sortCenterPosition(whiteout_M2SkinSection* self, const whiteout_Vector3f* value);
float whiteout_m2_M2SkinSection_get_sortRadius(const whiteout_M2SkinSection* self);
void whiteout_m2_M2SkinSection_set_sortRadius(whiteout_M2SkinSection* self, float value);

/* ── M2Batch ─────────────────────────────────────────────── */

whiteout_M2Batch* whiteout_m2_M2Batch_new(void);
void whiteout_m2_M2Batch_delete(whiteout_M2Batch* self);

uint8_t whiteout_m2_M2Batch_get_flags(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_flags(whiteout_M2Batch* self, uint8_t value);
int8_t whiteout_m2_M2Batch_get_priorityPlane(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_priorityPlane(whiteout_M2Batch* self, int8_t value);
uint16_t whiteout_m2_M2Batch_get_shaderId(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_shaderId(whiteout_M2Batch* self, uint16_t value);
uint16_t whiteout_m2_M2Batch_get_skinSectionIndex(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_skinSectionIndex(whiteout_M2Batch* self, uint16_t value);
uint16_t whiteout_m2_M2Batch_get_geosetIndex(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_geosetIndex(whiteout_M2Batch* self, uint16_t value);
int16_t whiteout_m2_M2Batch_get_colorIndex(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_colorIndex(whiteout_M2Batch* self, int16_t value);
uint16_t whiteout_m2_M2Batch_get_materialIndex(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_materialIndex(whiteout_M2Batch* self, uint16_t value);
uint16_t whiteout_m2_M2Batch_get_materialLayer(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_materialLayer(whiteout_M2Batch* self, uint16_t value);
uint16_t whiteout_m2_M2Batch_get_textureCount(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_textureCount(whiteout_M2Batch* self, uint16_t value);
uint16_t whiteout_m2_M2Batch_get_textureComboIndex(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_textureComboIndex(whiteout_M2Batch* self, uint16_t value);
uint16_t whiteout_m2_M2Batch_get_textureCoordComboIndex(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_textureCoordComboIndex(whiteout_M2Batch* self, uint16_t value);
uint16_t whiteout_m2_M2Batch_get_textureWeightComboIndex(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_textureWeightComboIndex(whiteout_M2Batch* self, uint16_t value);
uint16_t whiteout_m2_M2Batch_get_textureTransformComboIndex(const whiteout_M2Batch* self);
void whiteout_m2_M2Batch_set_textureTransformComboIndex(whiteout_M2Batch* self, uint16_t value);

/* ── M2ShadowBatch ─────────────────────────────────────────────── */

whiteout_M2ShadowBatch* whiteout_m2_M2ShadowBatch_new(void);
void whiteout_m2_M2ShadowBatch_delete(whiteout_M2ShadowBatch* self);

uint8_t whiteout_m2_M2ShadowBatch_get_flags(const whiteout_M2ShadowBatch* self);
void whiteout_m2_M2ShadowBatch_set_flags(whiteout_M2ShadowBatch* self, uint8_t value);
uint8_t whiteout_m2_M2ShadowBatch_get_flags2(const whiteout_M2ShadowBatch* self);
void whiteout_m2_M2ShadowBatch_set_flags2(whiteout_M2ShadowBatch* self, uint8_t value);
uint16_t whiteout_m2_M2ShadowBatch_get_unknown0(const whiteout_M2ShadowBatch* self);
void whiteout_m2_M2ShadowBatch_set_unknown0(whiteout_M2ShadowBatch* self, uint16_t value);
uint16_t whiteout_m2_M2ShadowBatch_get_submeshId(const whiteout_M2ShadowBatch* self);
void whiteout_m2_M2ShadowBatch_set_submeshId(whiteout_M2ShadowBatch* self, uint16_t value);
uint16_t whiteout_m2_M2ShadowBatch_get_textureId(const whiteout_M2ShadowBatch* self);
void whiteout_m2_M2ShadowBatch_set_textureId(whiteout_M2ShadowBatch* self, uint16_t value);
uint16_t whiteout_m2_M2ShadowBatch_get_colorId(const whiteout_M2ShadowBatch* self);
void whiteout_m2_M2ShadowBatch_set_colorId(whiteout_M2ShadowBatch* self, uint16_t value);
uint16_t whiteout_m2_M2ShadowBatch_get_transparencyId(const whiteout_M2ShadowBatch* self);
void whiteout_m2_M2ShadowBatch_set_transparencyId(whiteout_M2ShadowBatch* self, uint16_t value);

/* ── M2SkinProfile ─────────────────────────────────────────────── */

whiteout_M2SkinProfile* whiteout_m2_M2SkinProfile_new(void);
void whiteout_m2_M2SkinProfile_delete(whiteout_M2SkinProfile* self);

size_t whiteout_m2_M2SkinProfile_get_vertices_count(const whiteout_M2SkinProfile* self);
void whiteout_m2_M2SkinProfile_resize_vertices(whiteout_M2SkinProfile* self, size_t count);
const uint16_t* whiteout_m2_M2SkinProfile_get_vertices_data(const whiteout_M2SkinProfile* self);
void whiteout_m2_M2SkinProfile_assign_vertices(whiteout_M2SkinProfile* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2SkinProfile_get_indices_count(const whiteout_M2SkinProfile* self);
void whiteout_m2_M2SkinProfile_resize_indices(whiteout_M2SkinProfile* self, size_t count);
const uint16_t* whiteout_m2_M2SkinProfile_get_indices_data(const whiteout_M2SkinProfile* self);
void whiteout_m2_M2SkinProfile_assign_indices(whiteout_M2SkinProfile* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2SkinProfile_get_submeshes_count(const whiteout_M2SkinProfile* self);
void whiteout_m2_M2SkinProfile_resize_submeshes(whiteout_M2SkinProfile* self, size_t count);
whiteout_M2SkinSection* whiteout_m2_M2SkinProfile_get_submeshes_at(whiteout_M2SkinProfile* self, size_t index);
size_t whiteout_m2_M2SkinProfile_get_batches_count(const whiteout_M2SkinProfile* self);
void whiteout_m2_M2SkinProfile_resize_batches(whiteout_M2SkinProfile* self, size_t count);
whiteout_M2Batch* whiteout_m2_M2SkinProfile_get_batches_at(whiteout_M2SkinProfile* self, size_t index);
uint32_t whiteout_m2_M2SkinProfile_get_lodVertexBase(const whiteout_M2SkinProfile* self);
void whiteout_m2_M2SkinProfile_set_lodVertexBase(whiteout_M2SkinProfile* self, uint32_t value);
size_t whiteout_m2_M2SkinProfile_get_shadowBatches_count(const whiteout_M2SkinProfile* self);
void whiteout_m2_M2SkinProfile_resize_shadowBatches(whiteout_M2SkinProfile* self, size_t count);
whiteout_M2ShadowBatch* whiteout_m2_M2SkinProfile_get_shadowBatches_at(whiteout_M2SkinProfile* self, size_t index);

/* ── M2GlobalFlags ─────────────────────────────────────────────── */

whiteout_M2GlobalFlags* whiteout_m2_M2GlobalFlags_new(void);
void whiteout_m2_M2GlobalFlags_delete(whiteout_M2GlobalFlags* self);

int32_t whiteout_m2_M2GlobalFlags_get_value(const whiteout_M2GlobalFlags* self);
void whiteout_m2_M2GlobalFlags_set_value(whiteout_M2GlobalFlags* self, int32_t value);

/* ── M2GlobalSequence ─────────────────────────────────────────────── */

whiteout_M2GlobalSequence* whiteout_m2_M2GlobalSequence_new(void);
void whiteout_m2_M2GlobalSequence_delete(whiteout_M2GlobalSequence* self);

uint32_t whiteout_m2_M2GlobalSequence_get_timestamp(const whiteout_M2GlobalSequence* self);
void whiteout_m2_M2GlobalSequence_set_timestamp(whiteout_M2GlobalSequence* self, uint32_t value);

/* ── M2Sequence ─────────────────────────────────────────────── */

whiteout_M2Sequence* whiteout_m2_M2Sequence_new(void);
void whiteout_m2_M2Sequence_delete(whiteout_M2Sequence* self);

uint16_t whiteout_m2_M2Sequence_get_id(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_id(whiteout_M2Sequence* self, uint16_t value);
uint16_t whiteout_m2_M2Sequence_get_variationIndex(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_variationIndex(whiteout_M2Sequence* self, uint16_t value);
uint32_t whiteout_m2_M2Sequence_get_duration(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_duration(whiteout_M2Sequence* self, uint32_t value);
float whiteout_m2_M2Sequence_get_movespeed(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_movespeed(whiteout_M2Sequence* self, float value);
int32_t whiteout_m2_M2Sequence_get_flags(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_flags(whiteout_M2Sequence* self, int32_t value);
int16_t whiteout_m2_M2Sequence_get_frequency(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_frequency(whiteout_M2Sequence* self, int16_t value);
uint16_t whiteout_m2_M2Sequence_get_padding(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_padding(whiteout_M2Sequence* self, uint16_t value);
uint32_t whiteout_m2_M2Sequence_get_replayMin(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_replayMin(whiteout_M2Sequence* self, uint32_t value);
uint32_t whiteout_m2_M2Sequence_get_replayMax(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_replayMax(whiteout_M2Sequence* self, uint32_t value);
uint16_t whiteout_m2_M2Sequence_get_blendTimeIn(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_blendTimeIn(whiteout_M2Sequence* self, uint16_t value);
uint16_t whiteout_m2_M2Sequence_get_blendTimeOut(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_blendTimeOut(whiteout_M2Sequence* self, uint16_t value);
whiteout_M2Extent* whiteout_m2_M2Sequence_get_bounding(whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_bounding(whiteout_M2Sequence* self, const whiteout_M2Extent* value);
int16_t whiteout_m2_M2Sequence_get_variationNext(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_variationNext(whiteout_M2Sequence* self, int16_t value);
uint16_t whiteout_m2_M2Sequence_get_aliasNext(const whiteout_M2Sequence* self);
void whiteout_m2_M2Sequence_set_aliasNext(whiteout_M2Sequence* self, uint16_t value);

/* ── M2Vertex ─────────────────────────────────────────────── */

whiteout_M2Vertex* whiteout_m2_M2Vertex_new(void);
void whiteout_m2_M2Vertex_delete(whiteout_M2Vertex* self);

whiteout_Vector3f* whiteout_m2_M2Vertex_get_position(whiteout_M2Vertex* self);
void whiteout_m2_M2Vertex_set_position(whiteout_M2Vertex* self, const whiteout_Vector3f* value);
size_t whiteout_m2_M2Vertex_boneWeights_size(void);
uint8_t whiteout_m2_M2Vertex_get_boneWeights_at(const whiteout_M2Vertex* self, size_t index);
void whiteout_m2_M2Vertex_set_boneWeights_at(whiteout_M2Vertex* self, size_t index, uint8_t value);
size_t whiteout_m2_M2Vertex_boneIndices_size(void);
uint8_t whiteout_m2_M2Vertex_get_boneIndices_at(const whiteout_M2Vertex* self, size_t index);
void whiteout_m2_M2Vertex_set_boneIndices_at(whiteout_M2Vertex* self, size_t index, uint8_t value);
whiteout_Vector3f* whiteout_m2_M2Vertex_get_normal(whiteout_M2Vertex* self);
void whiteout_m2_M2Vertex_set_normal(whiteout_M2Vertex* self, const whiteout_Vector3f* value);
size_t whiteout_m2_M2Vertex_texCoords_size(void);
whiteout_Vector2f* whiteout_m2_M2Vertex_get_texCoords_at(const whiteout_M2Vertex* self, size_t index);

/* ── M2Bone ─────────────────────────────────────────────── */

whiteout_M2Bone* whiteout_m2_M2Bone_new(void);
void whiteout_m2_M2Bone_delete(whiteout_M2Bone* self);

int32_t whiteout_m2_M2Bone_get_keyBoneId(const whiteout_M2Bone* self);
void whiteout_m2_M2Bone_set_keyBoneId(whiteout_M2Bone* self, int32_t value);
uint32_t whiteout_m2_M2Bone_get_flags(const whiteout_M2Bone* self);
void whiteout_m2_M2Bone_set_flags(whiteout_M2Bone* self, uint32_t value);
int16_t whiteout_m2_M2Bone_get_parentBoneId(const whiteout_M2Bone* self);
void whiteout_m2_M2Bone_set_parentBoneId(whiteout_M2Bone* self, int16_t value);
uint16_t whiteout_m2_M2Bone_get_submeshId(const whiteout_M2Bone* self);
void whiteout_m2_M2Bone_set_submeshId(whiteout_M2Bone* self, uint16_t value);
uint32_t whiteout_m2_M2Bone_get_boneNameCRC(const whiteout_M2Bone* self);
void whiteout_m2_M2Bone_set_boneNameCRC(whiteout_M2Bone* self, uint32_t value);
whiteout_M2AnimationTrackVector3f* whiteout_m2_M2Bone_get_translation(whiteout_M2Bone* self);
void whiteout_m2_M2Bone_set_translation(whiteout_M2Bone* self, const whiteout_M2AnimationTrackVector3f* value);
whiteout_M2AnimationTrackM2CompatQuaternion* whiteout_m2_M2Bone_get_rotation(whiteout_M2Bone* self);
void whiteout_m2_M2Bone_set_rotation(whiteout_M2Bone* self, const whiteout_M2AnimationTrackM2CompatQuaternion* value);
whiteout_M2AnimationTrackVector3f* whiteout_m2_M2Bone_get_scale(whiteout_M2Bone* self);
void whiteout_m2_M2Bone_set_scale(whiteout_M2Bone* self, const whiteout_M2AnimationTrackVector3f* value);
whiteout_Vector3f* whiteout_m2_M2Bone_get_pivot(whiteout_M2Bone* self);
void whiteout_m2_M2Bone_set_pivot(whiteout_M2Bone* self, const whiteout_Vector3f* value);

/* ── M2Texture ─────────────────────────────────────────────── */

whiteout_M2Texture* whiteout_m2_M2Texture_new(void);
void whiteout_m2_M2Texture_delete(whiteout_M2Texture* self);

uint32_t whiteout_m2_M2Texture_get_type(const whiteout_M2Texture* self);
void whiteout_m2_M2Texture_set_type(whiteout_M2Texture* self, uint32_t value);
uint32_t whiteout_m2_M2Texture_get_flags(const whiteout_M2Texture* self);
void whiteout_m2_M2Texture_set_flags(whiteout_M2Texture* self, uint32_t value);
whiteout_CString whiteout_m2_M2Texture_get_filename(const whiteout_M2Texture* self);
void whiteout_m2_M2Texture_set_filename(whiteout_M2Texture* self, const char* value);

/* ── M2Material ─────────────────────────────────────────────── */

whiteout_M2Material* whiteout_m2_M2Material_new(void);
void whiteout_m2_M2Material_delete(whiteout_M2Material* self);

uint16_t whiteout_m2_M2Material_get_flags(const whiteout_M2Material* self);
void whiteout_m2_M2Material_set_flags(whiteout_M2Material* self, uint16_t value);
uint16_t whiteout_m2_M2Material_get_blendingMode(const whiteout_M2Material* self);
void whiteout_m2_M2Material_set_blendingMode(whiteout_M2Material* self, uint16_t value);

/* ── M2TextureWeight ─────────────────────────────────────────────── */

whiteout_M2TextureWeight* whiteout_m2_M2TextureWeight_new(void);
void whiteout_m2_M2TextureWeight_delete(whiteout_M2TextureWeight* self);

whiteout_M2AnimationTrackI16* whiteout_m2_M2TextureWeight_get_weight(whiteout_M2TextureWeight* self);
void whiteout_m2_M2TextureWeight_set_weight(whiteout_M2TextureWeight* self, const whiteout_M2AnimationTrackI16* value);

/* ── M2TextureTransform ─────────────────────────────────────────────── */

whiteout_M2TextureTransform* whiteout_m2_M2TextureTransform_new(void);
void whiteout_m2_M2TextureTransform_delete(whiteout_M2TextureTransform* self);

whiteout_M2AnimationTrackVector3f* whiteout_m2_M2TextureTransform_get_translation(whiteout_M2TextureTransform* self);
void whiteout_m2_M2TextureTransform_set_translation(whiteout_M2TextureTransform* self, const whiteout_M2AnimationTrackVector3f* value);
whiteout_M2AnimationTrackM2CompatQuaternion* whiteout_m2_M2TextureTransform_get_rotation(whiteout_M2TextureTransform* self);
void whiteout_m2_M2TextureTransform_set_rotation(whiteout_M2TextureTransform* self, const whiteout_M2AnimationTrackM2CompatQuaternion* value);
whiteout_M2AnimationTrackVector3f* whiteout_m2_M2TextureTransform_get_scaling(whiteout_M2TextureTransform* self);
void whiteout_m2_M2TextureTransform_set_scaling(whiteout_M2TextureTransform* self, const whiteout_M2AnimationTrackVector3f* value);

/* ── M2ColorAnimation ─────────────────────────────────────────────── */

whiteout_M2ColorAnimation* whiteout_m2_M2ColorAnimation_new(void);
void whiteout_m2_M2ColorAnimation_delete(whiteout_M2ColorAnimation* self);

whiteout_M2AnimationTrackVector3f* whiteout_m2_M2ColorAnimation_get_color(whiteout_M2ColorAnimation* self);
void whiteout_m2_M2ColorAnimation_set_color(whiteout_M2ColorAnimation* self, const whiteout_M2AnimationTrackVector3f* value);
whiteout_M2AnimationTrackI16* whiteout_m2_M2ColorAnimation_get_alpha(whiteout_M2ColorAnimation* self);
void whiteout_m2_M2ColorAnimation_set_alpha(whiteout_M2ColorAnimation* self, const whiteout_M2AnimationTrackI16* value);

/* ── M2Light ─────────────────────────────────────────────── */

whiteout_M2Light* whiteout_m2_M2Light_new(void);
void whiteout_m2_M2Light_delete(whiteout_M2Light* self);

uint16_t whiteout_m2_M2Light_get_type(const whiteout_M2Light* self);
void whiteout_m2_M2Light_set_type(whiteout_M2Light* self, uint16_t value);
int16_t whiteout_m2_M2Light_get_boneId(const whiteout_M2Light* self);
void whiteout_m2_M2Light_set_boneId(whiteout_M2Light* self, int16_t value);
whiteout_Vector3f* whiteout_m2_M2Light_get_position(whiteout_M2Light* self);
void whiteout_m2_M2Light_set_position(whiteout_M2Light* self, const whiteout_Vector3f* value);
whiteout_M2AnimationTrackVector3f* whiteout_m2_M2Light_get_ambientColor(whiteout_M2Light* self);
void whiteout_m2_M2Light_set_ambientColor(whiteout_M2Light* self, const whiteout_M2AnimationTrackVector3f* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2Light_get_ambientIntensity(whiteout_M2Light* self);
void whiteout_m2_M2Light_set_ambientIntensity(whiteout_M2Light* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackVector3f* whiteout_m2_M2Light_get_diffuseColor(whiteout_M2Light* self);
void whiteout_m2_M2Light_set_diffuseColor(whiteout_M2Light* self, const whiteout_M2AnimationTrackVector3f* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2Light_get_diffuseIntensity(whiteout_M2Light* self);
void whiteout_m2_M2Light_set_diffuseIntensity(whiteout_M2Light* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2Light_get_attenuationStart(whiteout_M2Light* self);
void whiteout_m2_M2Light_set_attenuationStart(whiteout_M2Light* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2Light_get_attenuationEnd(whiteout_M2Light* self);
void whiteout_m2_M2Light_set_attenuationEnd(whiteout_M2Light* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackU8* whiteout_m2_M2Light_get_visibility(whiteout_M2Light* self);
void whiteout_m2_M2Light_set_visibility(whiteout_M2Light* self, const whiteout_M2AnimationTrackU8* value);

/* ── M2CameraSpline ─────────────────────────────────────────────── */

whiteout_M2CameraSpline* whiteout_m2_M2CameraSpline_new(void);
void whiteout_m2_M2CameraSpline_delete(whiteout_M2CameraSpline* self);

whiteout_Vector3f* whiteout_m2_M2CameraSpline_get_value(whiteout_M2CameraSpline* self);
void whiteout_m2_M2CameraSpline_set_value(whiteout_M2CameraSpline* self, const whiteout_Vector3f* value);
whiteout_Vector3f* whiteout_m2_M2CameraSpline_get_inTangent(whiteout_M2CameraSpline* self);
void whiteout_m2_M2CameraSpline_set_inTangent(whiteout_M2CameraSpline* self, const whiteout_Vector3f* value);
whiteout_Vector3f* whiteout_m2_M2CameraSpline_get_outTangent(whiteout_M2CameraSpline* self);
void whiteout_m2_M2CameraSpline_set_outTangent(whiteout_M2CameraSpline* self, const whiteout_Vector3f* value);

/* ── M2Camera ─────────────────────────────────────────────── */

whiteout_M2Camera* whiteout_m2_M2Camera_new(void);
void whiteout_m2_M2Camera_delete(whiteout_M2Camera* self);

uint32_t whiteout_m2_M2Camera_get_type(const whiteout_M2Camera* self);
void whiteout_m2_M2Camera_set_type(whiteout_M2Camera* self, uint32_t value);
float whiteout_m2_M2Camera_get_fieldOfView(const whiteout_M2Camera* self);
void whiteout_m2_M2Camera_set_fieldOfView(whiteout_M2Camera* self, float value);
float whiteout_m2_M2Camera_get_farClip(const whiteout_M2Camera* self);
void whiteout_m2_M2Camera_set_farClip(whiteout_M2Camera* self, float value);
float whiteout_m2_M2Camera_get_nearClip(const whiteout_M2Camera* self);
void whiteout_m2_M2Camera_set_nearClip(whiteout_M2Camera* self, float value);
whiteout_M2AnimationTrackM2CameraSpline* whiteout_m2_M2Camera_get_positions(whiteout_M2Camera* self);
void whiteout_m2_M2Camera_set_positions(whiteout_M2Camera* self, const whiteout_M2AnimationTrackM2CameraSpline* value);
whiteout_Vector3f* whiteout_m2_M2Camera_get_positionBase(whiteout_M2Camera* self);
void whiteout_m2_M2Camera_set_positionBase(whiteout_M2Camera* self, const whiteout_Vector3f* value);
whiteout_M2AnimationTrackM2CameraSpline* whiteout_m2_M2Camera_get_targetPositions(whiteout_M2Camera* self);
void whiteout_m2_M2Camera_set_targetPositions(whiteout_M2Camera* self, const whiteout_M2AnimationTrackM2CameraSpline* value);
whiteout_Vector3f* whiteout_m2_M2Camera_get_targetPositionBase(whiteout_M2Camera* self);
void whiteout_m2_M2Camera_set_targetPositionBase(whiteout_M2Camera* self, const whiteout_Vector3f* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2Camera_get_roll(whiteout_M2Camera* self);
void whiteout_m2_M2Camera_set_roll(whiteout_M2Camera* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2Camera_get_fieldOfViewTrack(whiteout_M2Camera* self);
void whiteout_m2_M2Camera_set_fieldOfViewTrack(whiteout_M2Camera* self, const whiteout_M2AnimationTrackF32* value);

/* ── M2Attachment ─────────────────────────────────────────────── */

whiteout_M2Attachment* whiteout_m2_M2Attachment_new(void);
void whiteout_m2_M2Attachment_delete(whiteout_M2Attachment* self);

uint32_t whiteout_m2_M2Attachment_get_id(const whiteout_M2Attachment* self);
void whiteout_m2_M2Attachment_set_id(whiteout_M2Attachment* self, uint32_t value);
uint16_t whiteout_m2_M2Attachment_get_boneId(const whiteout_M2Attachment* self);
void whiteout_m2_M2Attachment_set_boneId(whiteout_M2Attachment* self, uint16_t value);
uint16_t whiteout_m2_M2Attachment_get_unknown(const whiteout_M2Attachment* self);
void whiteout_m2_M2Attachment_set_unknown(whiteout_M2Attachment* self, uint16_t value);
whiteout_Vector3f* whiteout_m2_M2Attachment_get_position(whiteout_M2Attachment* self);
void whiteout_m2_M2Attachment_set_position(whiteout_M2Attachment* self, const whiteout_Vector3f* value);
whiteout_M2AnimationTrackU8* whiteout_m2_M2Attachment_get_animate(whiteout_M2Attachment* self);
void whiteout_m2_M2Attachment_set_animate(whiteout_M2Attachment* self, const whiteout_M2AnimationTrackU8* value);

/* ── M2RibbonEmitter ─────────────────────────────────────────────── */

whiteout_M2RibbonEmitter* whiteout_m2_M2RibbonEmitter_new(void);
void whiteout_m2_M2RibbonEmitter_delete(whiteout_M2RibbonEmitter* self);

uint32_t whiteout_m2_M2RibbonEmitter_get_ribbonId(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_ribbonId(whiteout_M2RibbonEmitter* self, uint32_t value);
uint32_t whiteout_m2_M2RibbonEmitter_get_boneId(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_boneId(whiteout_M2RibbonEmitter* self, uint32_t value);
whiteout_Vector3f* whiteout_m2_M2RibbonEmitter_get_position(whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_position(whiteout_M2RibbonEmitter* self, const whiteout_Vector3f* value);
size_t whiteout_m2_M2RibbonEmitter_get_textureIndices_count(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_resize_textureIndices(whiteout_M2RibbonEmitter* self, size_t count);
const uint16_t* whiteout_m2_M2RibbonEmitter_get_textureIndices_data(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_assign_textureIndices(whiteout_M2RibbonEmitter* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2RibbonEmitter_get_materialIndices_count(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_resize_materialIndices(whiteout_M2RibbonEmitter* self, size_t count);
const uint16_t* whiteout_m2_M2RibbonEmitter_get_materialIndices_data(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_assign_materialIndices(whiteout_M2RibbonEmitter* self, const uint16_t* data, size_t count);
whiteout_M2AnimationTrackVector3f* whiteout_m2_M2RibbonEmitter_get_colorTrack(whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_colorTrack(whiteout_M2RibbonEmitter* self, const whiteout_M2AnimationTrackVector3f* value);
whiteout_M2AnimationTrackI16* whiteout_m2_M2RibbonEmitter_get_alphaTrack(whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_alphaTrack(whiteout_M2RibbonEmitter* self, const whiteout_M2AnimationTrackI16* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2RibbonEmitter_get_heightAbove(whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_heightAbove(whiteout_M2RibbonEmitter* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2RibbonEmitter_get_heightBelow(whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_heightBelow(whiteout_M2RibbonEmitter* self, const whiteout_M2AnimationTrackF32* value);
float whiteout_m2_M2RibbonEmitter_get_edgesPerSecond(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_edgesPerSecond(whiteout_M2RibbonEmitter* self, float value);
float whiteout_m2_M2RibbonEmitter_get_edgeLifetime(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_edgeLifetime(whiteout_M2RibbonEmitter* self, float value);
float whiteout_m2_M2RibbonEmitter_get_gravity(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_gravity(whiteout_M2RibbonEmitter* self, float value);
uint16_t whiteout_m2_M2RibbonEmitter_get_textureRows(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_textureRows(whiteout_M2RibbonEmitter* self, uint16_t value);
uint16_t whiteout_m2_M2RibbonEmitter_get_textureCols(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_textureCols(whiteout_M2RibbonEmitter* self, uint16_t value);
whiteout_M2AnimationTrackU16* whiteout_m2_M2RibbonEmitter_get_texSlot(whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_texSlot(whiteout_M2RibbonEmitter* self, const whiteout_M2AnimationTrackU16* value);
whiteout_M2AnimationTrackU8* whiteout_m2_M2RibbonEmitter_get_visibility(whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_visibility(whiteout_M2RibbonEmitter* self, const whiteout_M2AnimationTrackU8* value);
int16_t whiteout_m2_M2RibbonEmitter_get_priorityPlane(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_priorityPlane(whiteout_M2RibbonEmitter* self, int16_t value);
int8_t whiteout_m2_M2RibbonEmitter_get_ribbonColorIndex(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_ribbonColorIndex(whiteout_M2RibbonEmitter* self, int8_t value);
int8_t whiteout_m2_M2RibbonEmitter_get_textureTransformIndex(const whiteout_M2RibbonEmitter* self);
void whiteout_m2_M2RibbonEmitter_set_textureTransformIndex(whiteout_M2RibbonEmitter* self, int8_t value);

/* ── M2Box ─────────────────────────────────────────────── */

whiteout_M2Box* whiteout_m2_M2Box_new(void);
void whiteout_m2_M2Box_delete(whiteout_M2Box* self);

whiteout_Vector3f* whiteout_m2_M2Box_get_minimum(whiteout_M2Box* self);
void whiteout_m2_M2Box_set_minimum(whiteout_M2Box* self, const whiteout_Vector3f* value);
whiteout_Vector3f* whiteout_m2_M2Box_get_maximum(whiteout_M2Box* self);
void whiteout_m2_M2Box_set_maximum(whiteout_M2Box* self, const whiteout_Vector3f* value);

/* ── M2ParticleEmitter ─────────────────────────────────────────────── */

whiteout_M2ParticleEmitter* whiteout_m2_M2ParticleEmitter_new(void);
void whiteout_m2_M2ParticleEmitter_delete(whiteout_M2ParticleEmitter* self);

uint32_t whiteout_m2_M2ParticleEmitter_get_particleId(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_particleId(whiteout_M2ParticleEmitter* self, uint32_t value);
int32_t whiteout_m2_M2ParticleEmitter_get_flags(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_flags(whiteout_M2ParticleEmitter* self, int32_t value);
whiteout_Vector3f* whiteout_m2_M2ParticleEmitter_get_position(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_position(whiteout_M2ParticleEmitter* self, const whiteout_Vector3f* value);
uint16_t whiteout_m2_M2ParticleEmitter_get_boneId(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_boneId(whiteout_M2ParticleEmitter* self, uint16_t value);
whiteout_CString whiteout_m2_M2ParticleEmitter_get_particleModelFilename(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_particleModelFilename(whiteout_M2ParticleEmitter* self, const char* value);
whiteout_CString whiteout_m2_M2ParticleEmitter_get_childEmittersModelFilename(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_childEmittersModelFilename(whiteout_M2ParticleEmitter* self, const char* value);
int32_t whiteout_m2_M2ParticleEmitter_get_blendingType(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_blendingType(whiteout_M2ParticleEmitter* self, int32_t value);
int32_t whiteout_m2_M2ParticleEmitter_get_emitterType(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_emitterType(whiteout_M2ParticleEmitter* self, int32_t value);
uint16_t whiteout_m2_M2ParticleEmitter_get_particleColorIndex(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_particleColorIndex(whiteout_M2ParticleEmitter* self, uint16_t value);
int16_t whiteout_m2_M2ParticleEmitter_get_textureTilerotation(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_textureTilerotation(whiteout_M2ParticleEmitter* self, int16_t value);
uint16_t whiteout_m2_M2ParticleEmitter_get_rows(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_rows(whiteout_M2ParticleEmitter* self, uint16_t value);
uint16_t whiteout_m2_M2ParticleEmitter_get_columns(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_columns(whiteout_M2ParticleEmitter* self, uint16_t value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2ParticleEmitter_get_emissionSpeed(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_emissionSpeed(whiteout_M2ParticleEmitter* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2ParticleEmitter_get_speedVariation(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_speedVariation(whiteout_M2ParticleEmitter* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2ParticleEmitter_get_verticalRange(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_verticalRange(whiteout_M2ParticleEmitter* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2ParticleEmitter_get_horizontalRange(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_horizontalRange(whiteout_M2ParticleEmitter* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2ParticleEmitter_get_gravity(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_gravity(whiteout_M2ParticleEmitter* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2ParticleEmitter_get_lifespan(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_lifespan(whiteout_M2ParticleEmitter* self, const whiteout_M2AnimationTrackF32* value);
float whiteout_m2_M2ParticleEmitter_get_lifespanVariation(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_lifespanVariation(whiteout_M2ParticleEmitter* self, float value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2ParticleEmitter_get_emissionRate(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_emissionRate(whiteout_M2ParticleEmitter* self, const whiteout_M2AnimationTrackF32* value);
float whiteout_m2_M2ParticleEmitter_get_emissionRateVariation(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_emissionRateVariation(whiteout_M2ParticleEmitter* self, float value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2ParticleEmitter_get_emissionAreaWidth(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_emissionAreaWidth(whiteout_M2ParticleEmitter* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2ParticleEmitter_get_emissionAreaLength(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_emissionAreaLength(whiteout_M2ParticleEmitter* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2AnimationTrackF32* whiteout_m2_M2ParticleEmitter_get_zSource(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_zSource(whiteout_M2ParticleEmitter* self, const whiteout_M2AnimationTrackF32* value);
whiteout_M2ParticleAnimationTrackVector3f* whiteout_m2_M2ParticleEmitter_get_colorTrack(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_colorTrack(whiteout_M2ParticleEmitter* self, const whiteout_M2ParticleAnimationTrackVector3f* value);
whiteout_M2ParticleAnimationTrackVector2f* whiteout_m2_M2ParticleEmitter_get_scaleTrack(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_scaleTrack(whiteout_M2ParticleEmitter* self, const whiteout_M2ParticleAnimationTrackVector2f* value);
whiteout_Vector2f* whiteout_m2_M2ParticleEmitter_get_scaleVary(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_scaleVary(whiteout_M2ParticleEmitter* self, const whiteout_Vector2f* value);
float whiteout_m2_M2ParticleEmitter_get_tailLength(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_tailLength(whiteout_M2ParticleEmitter* self, float value);
float whiteout_m2_M2ParticleEmitter_get_twinkleSpeed(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_twinkleSpeed(whiteout_M2ParticleEmitter* self, float value);
float whiteout_m2_M2ParticleEmitter_get_twinklePercent(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_twinklePercent(whiteout_M2ParticleEmitter* self, float value);
whiteout_Vector2f* whiteout_m2_M2ParticleEmitter_get_twinkleScale(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_twinkleScale(whiteout_M2ParticleEmitter* self, const whiteout_Vector2f* value);
float whiteout_m2_M2ParticleEmitter_get_inheritVelocityScale(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_inheritVelocityScale(whiteout_M2ParticleEmitter* self, float value);
float whiteout_m2_M2ParticleEmitter_get_drag(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_drag(whiteout_M2ParticleEmitter* self, float value);
float whiteout_m2_M2ParticleEmitter_get_baseSpin(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_baseSpin(whiteout_M2ParticleEmitter* self, float value);
float whiteout_m2_M2ParticleEmitter_get_baseSpinVariation(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_baseSpinVariation(whiteout_M2ParticleEmitter* self, float value);
float whiteout_m2_M2ParticleEmitter_get_spinSpeed(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_spinSpeed(whiteout_M2ParticleEmitter* self, float value);
float whiteout_m2_M2ParticleEmitter_get_spinSpeedVariation(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_spinSpeedVariation(whiteout_M2ParticleEmitter* self, float value);
whiteout_M2Box* whiteout_m2_M2ParticleEmitter_get_tumble(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_tumble(whiteout_M2ParticleEmitter* self, const whiteout_M2Box* value);
whiteout_Vector3f* whiteout_m2_M2ParticleEmitter_get_windVector(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_windVector(whiteout_M2ParticleEmitter* self, const whiteout_Vector3f* value);
float whiteout_m2_M2ParticleEmitter_get_windTime(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_windTime(whiteout_M2ParticleEmitter* self, float value);
float whiteout_m2_M2ParticleEmitter_get_followSpeed1(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_followSpeed1(whiteout_M2ParticleEmitter* self, float value);
float whiteout_m2_M2ParticleEmitter_get_followScale1(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_followScale1(whiteout_M2ParticleEmitter* self, float value);
float whiteout_m2_M2ParticleEmitter_get_followSpeed2(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_followSpeed2(whiteout_M2ParticleEmitter* self, float value);
float whiteout_m2_M2ParticleEmitter_get_followScale2(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_followScale2(whiteout_M2ParticleEmitter* self, float value);
size_t whiteout_m2_M2ParticleEmitter_get_splinePoints_count(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_resize_splinePoints(whiteout_M2ParticleEmitter* self, size_t count);
const float* whiteout_m2_M2ParticleEmitter_get_splinePoints_data(const whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_assign_splinePoints(whiteout_M2ParticleEmitter* self, const float* data, size_t count);
whiteout_M2AnimationTrackU8* whiteout_m2_M2ParticleEmitter_get_enabledIn(whiteout_M2ParticleEmitter* self);
void whiteout_m2_M2ParticleEmitter_set_enabledIn(whiteout_M2ParticleEmitter* self, const whiteout_M2AnimationTrackU8* value);

/* ── M2Event ─────────────────────────────────────────────── */

whiteout_M2Event* whiteout_m2_M2Event_new(void);
void whiteout_m2_M2Event_delete(whiteout_M2Event* self);

uint32_t whiteout_m2_M2Event_get_identifier(const whiteout_M2Event* self);
void whiteout_m2_M2Event_set_identifier(whiteout_M2Event* self, uint32_t value);
uint32_t whiteout_m2_M2Event_get_data(const whiteout_M2Event* self);
void whiteout_m2_M2Event_set_data(whiteout_M2Event* self, uint32_t value);
uint32_t whiteout_m2_M2Event_get_boneId(const whiteout_M2Event* self);
void whiteout_m2_M2Event_set_boneId(whiteout_M2Event* self, uint32_t value);
whiteout_Vector3f* whiteout_m2_M2Event_get_position(whiteout_M2Event* self);
void whiteout_m2_M2Event_set_position(whiteout_M2Event* self, const whiteout_Vector3f* value);
whiteout_M2AnimationTrackBase* whiteout_m2_M2Event_get_enabled(whiteout_M2Event* self);
void whiteout_m2_M2Event_set_enabled(whiteout_M2Event* self, const whiteout_M2AnimationTrackBase* value);

/* ── M2Model ─────────────────────────────────────────────── */

whiteout_M2Model* whiteout_m2_M2Model_new(void);
void whiteout_m2_M2Model_delete(whiteout_M2Model* self);

whiteout_CString whiteout_m2_M2Model_get_modelName(const whiteout_M2Model* self);
void whiteout_m2_M2Model_set_modelName(whiteout_M2Model* self, const char* value);
whiteout_M2GlobalFlags* whiteout_m2_M2Model_get_globalFlags(whiteout_M2Model* self);
void whiteout_m2_M2Model_set_globalFlags(whiteout_M2Model* self, const whiteout_M2GlobalFlags* value);
size_t whiteout_m2_M2Model_get_globalLoops_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_globalLoops(whiteout_M2Model* self, size_t count);
whiteout_M2GlobalSequence* whiteout_m2_M2Model_get_globalLoops_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_sequences_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_sequences(whiteout_M2Model* self, size_t count);
whiteout_M2Sequence* whiteout_m2_M2Model_get_sequences_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_sequenceIdxHashById_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_sequenceIdxHashById(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_sequenceIdxHashById_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_sequenceIdxHashById(whiteout_M2Model* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2Model_get_bones_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_bones(whiteout_M2Model* self, size_t count);
whiteout_M2Bone* whiteout_m2_M2Model_get_bones_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_keyBoneIds_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_keyBoneIds(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_keyBoneIds_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_keyBoneIds(whiteout_M2Model* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2Model_get_vertices_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_vertices(whiteout_M2Model* self, size_t count);
whiteout_M2Vertex* whiteout_m2_M2Model_get_vertices_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_skinProfiles_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_skinProfiles(whiteout_M2Model* self, size_t count);
whiteout_M2SkinProfile* whiteout_m2_M2Model_get_skinProfiles_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_lodProfiles_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_lodProfiles(whiteout_M2Model* self, size_t count);
whiteout_M2SkinProfile* whiteout_m2_M2Model_get_lodProfiles_at(whiteout_M2Model* self, size_t index);
uint32_t whiteout_m2_M2Model_get_numSkinProfiles(const whiteout_M2Model* self);
void whiteout_m2_M2Model_set_numSkinProfiles(whiteout_M2Model* self, uint32_t value);
size_t whiteout_m2_M2Model_get_colors_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_colors(whiteout_M2Model* self, size_t count);
whiteout_M2ColorAnimation* whiteout_m2_M2Model_get_colors_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_textures_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_textures(whiteout_M2Model* self, size_t count);
whiteout_M2Texture* whiteout_m2_M2Model_get_textures_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_textureWeights_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_textureWeights(whiteout_M2Model* self, size_t count);
whiteout_M2TextureWeight* whiteout_m2_M2Model_get_textureWeights_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_textureTransforms_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_textureTransforms(whiteout_M2Model* self, size_t count);
whiteout_M2TextureTransform* whiteout_m2_M2Model_get_textureTransforms_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_textureIndicesById_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_textureIndicesById(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_textureIndicesById_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_textureIndicesById(whiteout_M2Model* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2Model_get_materials_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_materials(whiteout_M2Model* self, size_t count);
whiteout_M2Material* whiteout_m2_M2Model_get_materials_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_boneCombos_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_boneCombos(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_boneCombos_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_boneCombos(whiteout_M2Model* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2Model_get_textureCombos_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_textureCombos(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_textureCombos_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_textureCombos(whiteout_M2Model* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2Model_get_textureCoordCombos_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_textureCoordCombos(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_textureCoordCombos_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_textureCoordCombos(whiteout_M2Model* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2Model_get_textureWeightCombos_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_textureWeightCombos(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_textureWeightCombos_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_textureWeightCombos(whiteout_M2Model* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2Model_get_textureTransformCombos_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_textureTransformCombos(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_textureTransformCombos_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_textureTransformCombos(whiteout_M2Model* self, const uint16_t* data, size_t count);
whiteout_M2Extent* whiteout_m2_M2Model_get_bounding(whiteout_M2Model* self);
void whiteout_m2_M2Model_set_bounding(whiteout_M2Model* self, const whiteout_M2Extent* value);
whiteout_M2Extent* whiteout_m2_M2Model_get_collision(whiteout_M2Model* self);
void whiteout_m2_M2Model_set_collision(whiteout_M2Model* self, const whiteout_M2Extent* value);
size_t whiteout_m2_M2Model_get_collisionTriangleIndices_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_collisionTriangleIndices(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_collisionTriangleIndices_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_collisionTriangleIndices(whiteout_M2Model* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2Model_get_collisionVertices_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_collisionVertices(whiteout_M2Model* self, size_t count);
const float* whiteout_m2_M2Model_get_collisionVertices_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_collisionVertices(whiteout_M2Model* self, const float* data, size_t count);
size_t whiteout_m2_M2Model_get_collisionFaceNormals_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_collisionFaceNormals(whiteout_M2Model* self, size_t count);
const float* whiteout_m2_M2Model_get_collisionFaceNormals_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_collisionFaceNormals(whiteout_M2Model* self, const float* data, size_t count);
size_t whiteout_m2_M2Model_get_attachments_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_attachments(whiteout_M2Model* self, size_t count);
whiteout_M2Attachment* whiteout_m2_M2Model_get_attachments_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_attachmentIndicesById_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_attachmentIndicesById(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_attachmentIndicesById_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_attachmentIndicesById(whiteout_M2Model* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2Model_get_events_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_events(whiteout_M2Model* self, size_t count);
whiteout_M2Event* whiteout_m2_M2Model_get_events_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_lights_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_lights(whiteout_M2Model* self, size_t count);
whiteout_M2Light* whiteout_m2_M2Model_get_lights_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_cameras_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_cameras(whiteout_M2Model* self, size_t count);
whiteout_M2Camera* whiteout_m2_M2Model_get_cameras_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_cameraIndicesById_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_cameraIndicesById(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_cameraIndicesById_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_cameraIndicesById(whiteout_M2Model* self, const uint16_t* data, size_t count);
size_t whiteout_m2_M2Model_get_ribbonEmitters_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_ribbonEmitters(whiteout_M2Model* self, size_t count);
whiteout_M2RibbonEmitter* whiteout_m2_M2Model_get_ribbonEmitters_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_particleEmitters_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_particleEmitters(whiteout_M2Model* self, size_t count);
whiteout_M2ParticleEmitter* whiteout_m2_M2Model_get_particleEmitters_at(whiteout_M2Model* self, size_t index);
size_t whiteout_m2_M2Model_get_textureCombinerCombos_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_textureCombinerCombos(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_textureCombinerCombos_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_textureCombinerCombos(whiteout_M2Model* self, const uint16_t* data, size_t count);
/* TXID */
size_t whiteout_m2_M2Model_get_texture_ids_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_texture_ids(whiteout_M2Model* self, size_t count);
const uint32_t* whiteout_m2_M2Model_get_texture_ids_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_texture_ids(whiteout_M2Model* self, const uint32_t* data, size_t count);
/* PABC */
size_t whiteout_m2_M2Model_get_parentSequenceReplacements_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_parentSequenceReplacements(whiteout_M2Model* self, size_t count);
const uint16_t* whiteout_m2_M2Model_get_parentSequenceReplacements_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_parentSequenceReplacements(whiteout_M2Model* self, const uint16_t* data, size_t count);
/* PADC */
size_t whiteout_m2_M2Model_get_parentTextureWeights_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_parentTextureWeights(whiteout_M2Model* self, size_t count);
whiteout_M2TextureWeight* whiteout_m2_M2Model_get_parentTextureWeights_at(whiteout_M2Model* self, size_t index);
/* PSBC */
size_t whiteout_m2_M2Model_get_parentSequenceBounds_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_parentSequenceBounds(whiteout_M2Model* self, size_t count);
whiteout_M2Extent* whiteout_m2_M2Model_get_parentSequenceBounds_at(whiteout_M2Model* self, size_t index);
/* PEDC */
size_t whiteout_m2_M2Model_get_parentEventData_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_parentEventData(whiteout_M2Model* self, size_t count);
whiteout_M2AnimationTrackBase* whiteout_m2_M2Model_get_parentEventData_at(whiteout_M2Model* self, size_t index);
/* RPID */
size_t whiteout_m2_M2Model_get_recursiveParticleModelIds_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_recursiveParticleModelIds(whiteout_M2Model* self, size_t count);
const uint32_t* whiteout_m2_M2Model_get_recursiveParticleModelIds_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_recursiveParticleModelIds(whiteout_M2Model* self, const uint32_t* data, size_t count);
/* GPID */
size_t whiteout_m2_M2Model_get_geometryParticleModelIds_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_geometryParticleModelIds(whiteout_M2Model* self, size_t count);
const uint32_t* whiteout_m2_M2Model_get_geometryParticleModelIds_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_geometryParticleModelIds(whiteout_M2Model* self, const uint32_t* data, size_t count);
/* PGD1 */
size_t whiteout_m2_M2Model_get_particleGeosets_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_particleGeosets(whiteout_M2Model* self, size_t count);
whiteout_M2ParticleGeosetData* whiteout_m2_M2Model_get_particleGeosets_at(whiteout_M2Model* self, size_t index);
/* PFDC */
size_t whiteout_m2_M2Model_get_physicsFileData_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_physicsFileData(whiteout_M2Model* self, size_t count);
const uint8_t* whiteout_m2_M2Model_get_physicsFileData_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_physicsFileData(whiteout_M2Model* self, const uint8_t* data, size_t count);
/* EDGF */
size_t whiteout_m2_M2Model_get_edgeFadeEntries_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_edgeFadeEntries(whiteout_M2Model* self, size_t count);
whiteout_M2EdgeFadeData* whiteout_m2_M2Model_get_edgeFadeEntries_at(whiteout_M2Model* self, size_t index);
/* NERF */
size_t whiteout_m2_M2Model_get_nerfEntries_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_nerfEntries(whiteout_M2Model* self, size_t count);
whiteout_M2DistanceFadeData* whiteout_m2_M2Model_get_nerfEntries_at(whiteout_M2Model* self, size_t index);
/* DETL */
size_t whiteout_m2_M2Model_get_detailedLightEntries_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_detailedLightEntries(whiteout_M2Model* self, size_t count);
whiteout_M2DetailedLightData* whiteout_m2_M2Model_get_detailedLightEntries_at(whiteout_M2Model* self, size_t index);
/* DBOC */
size_t whiteout_m2_M2Model_get_debugOcclusionEntries_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_debugOcclusionEntries(whiteout_M2Model* self, size_t count);
whiteout_M2DebugOcclusionData* whiteout_m2_M2Model_get_debugOcclusionEntries_at(whiteout_M2Model* self, size_t index);
/* AFRA */
size_t whiteout_m2_M2Model_get_animFrameData_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_animFrameData(whiteout_M2Model* self, size_t count);
const uint8_t* whiteout_m2_M2Model_get_animFrameData_data(const whiteout_M2Model* self);
void whiteout_m2_M2Model_assign_animFrameData(whiteout_M2Model* self, const uint8_t* data, size_t count);
/* TEXL */
size_t whiteout_m2_M2Model_get_texturedLightEntries_count(const whiteout_M2Model* self);
void whiteout_m2_M2Model_resize_texturedLightEntries(whiteout_M2Model* self, size_t count);
whiteout_M2TexturedLightData* whiteout_m2_M2Model_get_texturedLightEntries_at(whiteout_M2Model* self, size_t index);

/* ── M2AnimationTrackVector3f ─────────────────────────────────────────────── */

whiteout_M2AnimationTrackVector3f* whiteout_m2_M2AnimationTrackVector3f_new(void);
void whiteout_m2_M2AnimationTrackVector3f_delete(whiteout_M2AnimationTrackVector3f* self);

int32_t whiteout_m2_M2AnimationTrackVector3f_get_interpolationType(const whiteout_M2AnimationTrackVector3f* self);
void whiteout_m2_M2AnimationTrackVector3f_set_interpolationType(whiteout_M2AnimationTrackVector3f* self, int32_t value);
uint16_t whiteout_m2_M2AnimationTrackVector3f_get_globalSequenceId(const whiteout_M2AnimationTrackVector3f* self);
void whiteout_m2_M2AnimationTrackVector3f_set_globalSequenceId(whiteout_M2AnimationTrackVector3f* self, uint16_t value);
size_t whiteout_m2_M2AnimationTrackVector3f_get_timestamps_count(const whiteout_M2AnimationTrackVector3f* self);
size_t whiteout_m2_M2AnimationTrackVector3f_get_timestamps_inner_count(const whiteout_M2AnimationTrackVector3f* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackVector3f_resize_timestamps(whiteout_M2AnimationTrackVector3f* self, size_t count);
void whiteout_m2_M2AnimationTrackVector3f_resize_timestamps_inner(whiteout_M2AnimationTrackVector3f* self, size_t outer_idx, size_t inner_count);
const uint32_t* whiteout_m2_M2AnimationTrackVector3f_get_timestamps_inner_data(const whiteout_M2AnimationTrackVector3f* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackVector3f_assign_timestamps_inner(whiteout_M2AnimationTrackVector3f* self, size_t outer_idx, const uint32_t* data, size_t count);
size_t whiteout_m2_M2AnimationTrackVector3f_get_values_count(const whiteout_M2AnimationTrackVector3f* self);
size_t whiteout_m2_M2AnimationTrackVector3f_get_values_inner_count(const whiteout_M2AnimationTrackVector3f* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackVector3f_resize_values(whiteout_M2AnimationTrackVector3f* self, size_t count);
void whiteout_m2_M2AnimationTrackVector3f_resize_values_inner(whiteout_M2AnimationTrackVector3f* self, size_t outer_idx, size_t inner_count);
const float* whiteout_m2_M2AnimationTrackVector3f_get_values_inner_data(const whiteout_M2AnimationTrackVector3f* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackVector3f_assign_values_inner(whiteout_M2AnimationTrackVector3f* self, size_t outer_idx, const float* data, size_t count);

/* ── M2AnimationTrackM2CompatQuaternion ─────────────────────────────────────────────── */

whiteout_M2AnimationTrackM2CompatQuaternion* whiteout_m2_M2AnimationTrackM2CompatQuaternion_new(void);
void whiteout_m2_M2AnimationTrackM2CompatQuaternion_delete(whiteout_M2AnimationTrackM2CompatQuaternion* self);

int32_t whiteout_m2_M2AnimationTrackM2CompatQuaternion_get_interpolationType(const whiteout_M2AnimationTrackM2CompatQuaternion* self);
void whiteout_m2_M2AnimationTrackM2CompatQuaternion_set_interpolationType(whiteout_M2AnimationTrackM2CompatQuaternion* self, int32_t value);
uint16_t whiteout_m2_M2AnimationTrackM2CompatQuaternion_get_globalSequenceId(const whiteout_M2AnimationTrackM2CompatQuaternion* self);
void whiteout_m2_M2AnimationTrackM2CompatQuaternion_set_globalSequenceId(whiteout_M2AnimationTrackM2CompatQuaternion* self, uint16_t value);
size_t whiteout_m2_M2AnimationTrackM2CompatQuaternion_get_timestamps_count(const whiteout_M2AnimationTrackM2CompatQuaternion* self);
size_t whiteout_m2_M2AnimationTrackM2CompatQuaternion_get_timestamps_inner_count(const whiteout_M2AnimationTrackM2CompatQuaternion* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackM2CompatQuaternion_resize_timestamps(whiteout_M2AnimationTrackM2CompatQuaternion* self, size_t count);
void whiteout_m2_M2AnimationTrackM2CompatQuaternion_resize_timestamps_inner(whiteout_M2AnimationTrackM2CompatQuaternion* self, size_t outer_idx, size_t inner_count);
const uint32_t* whiteout_m2_M2AnimationTrackM2CompatQuaternion_get_timestamps_inner_data(const whiteout_M2AnimationTrackM2CompatQuaternion* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackM2CompatQuaternion_assign_timestamps_inner(whiteout_M2AnimationTrackM2CompatQuaternion* self, size_t outer_idx, const uint32_t* data, size_t count);
size_t whiteout_m2_M2AnimationTrackM2CompatQuaternion_get_values_count(const whiteout_M2AnimationTrackM2CompatQuaternion* self);
size_t whiteout_m2_M2AnimationTrackM2CompatQuaternion_get_values_inner_count(const whiteout_M2AnimationTrackM2CompatQuaternion* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackM2CompatQuaternion_resize_values(whiteout_M2AnimationTrackM2CompatQuaternion* self, size_t count);
void whiteout_m2_M2AnimationTrackM2CompatQuaternion_resize_values_inner(whiteout_M2AnimationTrackM2CompatQuaternion* self, size_t outer_idx, size_t inner_count);
whiteout_M2CompatQuaternion* whiteout_m2_M2AnimationTrackM2CompatQuaternion_get_values_at(whiteout_M2AnimationTrackM2CompatQuaternion* self, size_t outer_idx, size_t inner_idx);

/* ── M2AnimationTrackI16 ─────────────────────────────────────────────── */

whiteout_M2AnimationTrackI16* whiteout_m2_M2AnimationTrackI16_new(void);
void whiteout_m2_M2AnimationTrackI16_delete(whiteout_M2AnimationTrackI16* self);

int32_t whiteout_m2_M2AnimationTrackI16_get_interpolationType(const whiteout_M2AnimationTrackI16* self);
void whiteout_m2_M2AnimationTrackI16_set_interpolationType(whiteout_M2AnimationTrackI16* self, int32_t value);
uint16_t whiteout_m2_M2AnimationTrackI16_get_globalSequenceId(const whiteout_M2AnimationTrackI16* self);
void whiteout_m2_M2AnimationTrackI16_set_globalSequenceId(whiteout_M2AnimationTrackI16* self, uint16_t value);
size_t whiteout_m2_M2AnimationTrackI16_get_timestamps_count(const whiteout_M2AnimationTrackI16* self);
size_t whiteout_m2_M2AnimationTrackI16_get_timestamps_inner_count(const whiteout_M2AnimationTrackI16* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackI16_resize_timestamps(whiteout_M2AnimationTrackI16* self, size_t count);
void whiteout_m2_M2AnimationTrackI16_resize_timestamps_inner(whiteout_M2AnimationTrackI16* self, size_t outer_idx, size_t inner_count);
const uint32_t* whiteout_m2_M2AnimationTrackI16_get_timestamps_inner_data(const whiteout_M2AnimationTrackI16* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackI16_assign_timestamps_inner(whiteout_M2AnimationTrackI16* self, size_t outer_idx, const uint32_t* data, size_t count);
size_t whiteout_m2_M2AnimationTrackI16_get_values_count(const whiteout_M2AnimationTrackI16* self);
size_t whiteout_m2_M2AnimationTrackI16_get_values_inner_count(const whiteout_M2AnimationTrackI16* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackI16_resize_values(whiteout_M2AnimationTrackI16* self, size_t count);
void whiteout_m2_M2AnimationTrackI16_resize_values_inner(whiteout_M2AnimationTrackI16* self, size_t outer_idx, size_t inner_count);
const int16_t* whiteout_m2_M2AnimationTrackI16_get_values_inner_data(const whiteout_M2AnimationTrackI16* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackI16_assign_values_inner(whiteout_M2AnimationTrackI16* self, size_t outer_idx, const int16_t* data, size_t count);

/* ── M2AnimationTrackF32 ─────────────────────────────────────────────── */

whiteout_M2AnimationTrackF32* whiteout_m2_M2AnimationTrackF32_new(void);
void whiteout_m2_M2AnimationTrackF32_delete(whiteout_M2AnimationTrackF32* self);

int32_t whiteout_m2_M2AnimationTrackF32_get_interpolationType(const whiteout_M2AnimationTrackF32* self);
void whiteout_m2_M2AnimationTrackF32_set_interpolationType(whiteout_M2AnimationTrackF32* self, int32_t value);
uint16_t whiteout_m2_M2AnimationTrackF32_get_globalSequenceId(const whiteout_M2AnimationTrackF32* self);
void whiteout_m2_M2AnimationTrackF32_set_globalSequenceId(whiteout_M2AnimationTrackF32* self, uint16_t value);
size_t whiteout_m2_M2AnimationTrackF32_get_timestamps_count(const whiteout_M2AnimationTrackF32* self);
size_t whiteout_m2_M2AnimationTrackF32_get_timestamps_inner_count(const whiteout_M2AnimationTrackF32* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackF32_resize_timestamps(whiteout_M2AnimationTrackF32* self, size_t count);
void whiteout_m2_M2AnimationTrackF32_resize_timestamps_inner(whiteout_M2AnimationTrackF32* self, size_t outer_idx, size_t inner_count);
const uint32_t* whiteout_m2_M2AnimationTrackF32_get_timestamps_inner_data(const whiteout_M2AnimationTrackF32* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackF32_assign_timestamps_inner(whiteout_M2AnimationTrackF32* self, size_t outer_idx, const uint32_t* data, size_t count);
size_t whiteout_m2_M2AnimationTrackF32_get_values_count(const whiteout_M2AnimationTrackF32* self);
size_t whiteout_m2_M2AnimationTrackF32_get_values_inner_count(const whiteout_M2AnimationTrackF32* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackF32_resize_values(whiteout_M2AnimationTrackF32* self, size_t count);
void whiteout_m2_M2AnimationTrackF32_resize_values_inner(whiteout_M2AnimationTrackF32* self, size_t outer_idx, size_t inner_count);
const float* whiteout_m2_M2AnimationTrackF32_get_values_inner_data(const whiteout_M2AnimationTrackF32* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackF32_assign_values_inner(whiteout_M2AnimationTrackF32* self, size_t outer_idx, const float* data, size_t count);

/* ── M2AnimationTrackU8 ─────────────────────────────────────────────── */

whiteout_M2AnimationTrackU8* whiteout_m2_M2AnimationTrackU8_new(void);
void whiteout_m2_M2AnimationTrackU8_delete(whiteout_M2AnimationTrackU8* self);

int32_t whiteout_m2_M2AnimationTrackU8_get_interpolationType(const whiteout_M2AnimationTrackU8* self);
void whiteout_m2_M2AnimationTrackU8_set_interpolationType(whiteout_M2AnimationTrackU8* self, int32_t value);
uint16_t whiteout_m2_M2AnimationTrackU8_get_globalSequenceId(const whiteout_M2AnimationTrackU8* self);
void whiteout_m2_M2AnimationTrackU8_set_globalSequenceId(whiteout_M2AnimationTrackU8* self, uint16_t value);
size_t whiteout_m2_M2AnimationTrackU8_get_timestamps_count(const whiteout_M2AnimationTrackU8* self);
size_t whiteout_m2_M2AnimationTrackU8_get_timestamps_inner_count(const whiteout_M2AnimationTrackU8* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackU8_resize_timestamps(whiteout_M2AnimationTrackU8* self, size_t count);
void whiteout_m2_M2AnimationTrackU8_resize_timestamps_inner(whiteout_M2AnimationTrackU8* self, size_t outer_idx, size_t inner_count);
const uint32_t* whiteout_m2_M2AnimationTrackU8_get_timestamps_inner_data(const whiteout_M2AnimationTrackU8* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackU8_assign_timestamps_inner(whiteout_M2AnimationTrackU8* self, size_t outer_idx, const uint32_t* data, size_t count);
size_t whiteout_m2_M2AnimationTrackU8_get_values_count(const whiteout_M2AnimationTrackU8* self);
size_t whiteout_m2_M2AnimationTrackU8_get_values_inner_count(const whiteout_M2AnimationTrackU8* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackU8_resize_values(whiteout_M2AnimationTrackU8* self, size_t count);
void whiteout_m2_M2AnimationTrackU8_resize_values_inner(whiteout_M2AnimationTrackU8* self, size_t outer_idx, size_t inner_count);
const uint8_t* whiteout_m2_M2AnimationTrackU8_get_values_inner_data(const whiteout_M2AnimationTrackU8* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackU8_assign_values_inner(whiteout_M2AnimationTrackU8* self, size_t outer_idx, const uint8_t* data, size_t count);

/* ── M2AnimationTrackM2CameraSpline ─────────────────────────────────────────────── */

whiteout_M2AnimationTrackM2CameraSpline* whiteout_m2_M2AnimationTrackM2CameraSpline_new(void);
void whiteout_m2_M2AnimationTrackM2CameraSpline_delete(whiteout_M2AnimationTrackM2CameraSpline* self);

int32_t whiteout_m2_M2AnimationTrackM2CameraSpline_get_interpolationType(const whiteout_M2AnimationTrackM2CameraSpline* self);
void whiteout_m2_M2AnimationTrackM2CameraSpline_set_interpolationType(whiteout_M2AnimationTrackM2CameraSpline* self, int32_t value);
uint16_t whiteout_m2_M2AnimationTrackM2CameraSpline_get_globalSequenceId(const whiteout_M2AnimationTrackM2CameraSpline* self);
void whiteout_m2_M2AnimationTrackM2CameraSpline_set_globalSequenceId(whiteout_M2AnimationTrackM2CameraSpline* self, uint16_t value);
size_t whiteout_m2_M2AnimationTrackM2CameraSpline_get_timestamps_count(const whiteout_M2AnimationTrackM2CameraSpline* self);
size_t whiteout_m2_M2AnimationTrackM2CameraSpline_get_timestamps_inner_count(const whiteout_M2AnimationTrackM2CameraSpline* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackM2CameraSpline_resize_timestamps(whiteout_M2AnimationTrackM2CameraSpline* self, size_t count);
void whiteout_m2_M2AnimationTrackM2CameraSpline_resize_timestamps_inner(whiteout_M2AnimationTrackM2CameraSpline* self, size_t outer_idx, size_t inner_count);
const uint32_t* whiteout_m2_M2AnimationTrackM2CameraSpline_get_timestamps_inner_data(const whiteout_M2AnimationTrackM2CameraSpline* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackM2CameraSpline_assign_timestamps_inner(whiteout_M2AnimationTrackM2CameraSpline* self, size_t outer_idx, const uint32_t* data, size_t count);
size_t whiteout_m2_M2AnimationTrackM2CameraSpline_get_values_count(const whiteout_M2AnimationTrackM2CameraSpline* self);
size_t whiteout_m2_M2AnimationTrackM2CameraSpline_get_values_inner_count(const whiteout_M2AnimationTrackM2CameraSpline* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackM2CameraSpline_resize_values(whiteout_M2AnimationTrackM2CameraSpline* self, size_t count);
void whiteout_m2_M2AnimationTrackM2CameraSpline_resize_values_inner(whiteout_M2AnimationTrackM2CameraSpline* self, size_t outer_idx, size_t inner_count);
whiteout_M2CameraSpline* whiteout_m2_M2AnimationTrackM2CameraSpline_get_values_at(whiteout_M2AnimationTrackM2CameraSpline* self, size_t outer_idx, size_t inner_idx);

/* ── M2AnimationTrackU16 ─────────────────────────────────────────────── */

whiteout_M2AnimationTrackU16* whiteout_m2_M2AnimationTrackU16_new(void);
void whiteout_m2_M2AnimationTrackU16_delete(whiteout_M2AnimationTrackU16* self);

int32_t whiteout_m2_M2AnimationTrackU16_get_interpolationType(const whiteout_M2AnimationTrackU16* self);
void whiteout_m2_M2AnimationTrackU16_set_interpolationType(whiteout_M2AnimationTrackU16* self, int32_t value);
uint16_t whiteout_m2_M2AnimationTrackU16_get_globalSequenceId(const whiteout_M2AnimationTrackU16* self);
void whiteout_m2_M2AnimationTrackU16_set_globalSequenceId(whiteout_M2AnimationTrackU16* self, uint16_t value);
size_t whiteout_m2_M2AnimationTrackU16_get_timestamps_count(const whiteout_M2AnimationTrackU16* self);
size_t whiteout_m2_M2AnimationTrackU16_get_timestamps_inner_count(const whiteout_M2AnimationTrackU16* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackU16_resize_timestamps(whiteout_M2AnimationTrackU16* self, size_t count);
void whiteout_m2_M2AnimationTrackU16_resize_timestamps_inner(whiteout_M2AnimationTrackU16* self, size_t outer_idx, size_t inner_count);
const uint32_t* whiteout_m2_M2AnimationTrackU16_get_timestamps_inner_data(const whiteout_M2AnimationTrackU16* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackU16_assign_timestamps_inner(whiteout_M2AnimationTrackU16* self, size_t outer_idx, const uint32_t* data, size_t count);
size_t whiteout_m2_M2AnimationTrackU16_get_values_count(const whiteout_M2AnimationTrackU16* self);
size_t whiteout_m2_M2AnimationTrackU16_get_values_inner_count(const whiteout_M2AnimationTrackU16* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackU16_resize_values(whiteout_M2AnimationTrackU16* self, size_t count);
void whiteout_m2_M2AnimationTrackU16_resize_values_inner(whiteout_M2AnimationTrackU16* self, size_t outer_idx, size_t inner_count);
const uint16_t* whiteout_m2_M2AnimationTrackU16_get_values_inner_data(const whiteout_M2AnimationTrackU16* self, size_t outer_idx);
void whiteout_m2_M2AnimationTrackU16_assign_values_inner(whiteout_M2AnimationTrackU16* self, size_t outer_idx, const uint16_t* data, size_t count);

/* ── M2ParticleAnimationTrackVector3f ─────────────────────────────────────────────── */

whiteout_M2ParticleAnimationTrackVector3f* whiteout_m2_M2ParticleAnimationTrackVector3f_new(void);
void whiteout_m2_M2ParticleAnimationTrackVector3f_delete(whiteout_M2ParticleAnimationTrackVector3f* self);

size_t whiteout_m2_M2ParticleAnimationTrackVector3f_get_values_count(const whiteout_M2ParticleAnimationTrackVector3f* self);
void whiteout_m2_M2ParticleAnimationTrackVector3f_resize_values(whiteout_M2ParticleAnimationTrackVector3f* self, size_t count);
const float* whiteout_m2_M2ParticleAnimationTrackVector3f_get_values_data(const whiteout_M2ParticleAnimationTrackVector3f* self);
void whiteout_m2_M2ParticleAnimationTrackVector3f_assign_values(whiteout_M2ParticleAnimationTrackVector3f* self, const float* data, size_t count);

/* ── M2ParticleAnimationTrackVector2f ─────────────────────────────────────────────── */

whiteout_M2ParticleAnimationTrackVector2f* whiteout_m2_M2ParticleAnimationTrackVector2f_new(void);
void whiteout_m2_M2ParticleAnimationTrackVector2f_delete(whiteout_M2ParticleAnimationTrackVector2f* self);

size_t whiteout_m2_M2ParticleAnimationTrackVector2f_get_values_count(const whiteout_M2ParticleAnimationTrackVector2f* self);
void whiteout_m2_M2ParticleAnimationTrackVector2f_resize_values(whiteout_M2ParticleAnimationTrackVector2f* self, size_t count);
const float* whiteout_m2_M2ParticleAnimationTrackVector2f_get_values_data(const whiteout_M2ParticleAnimationTrackVector2f* self);
void whiteout_m2_M2ParticleAnimationTrackVector2f_assign_values(whiteout_M2ParticleAnimationTrackVector2f* self, const float* data, size_t count);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* WHITEOUT_M2_H */
