// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_dts.py — do not edit by hand.
// Regenerate via:  python -m tools.codegen.codegen mdx --backend dts

import type {
    EmbindObject, EmbindVector, EmbindBufferVector, EnumValue, EnumMember, Vector2f, Vector3f, Vector4f, Quaternion,
} from "./_shared";

// ── Sentinel constants ─────────────────────────────────────────────
export const NoGlobalSequence: number;
export const NoParent: number;
export const MultipleGeosets: number;

// ── Enums ──────────────────────────────────────────────────────────
export const InterpolationType: {
    readonly None: EnumValue;
    readonly Linear: EnumValue;
    readonly Hermite: EnumValue;
    readonly Bezier: EnumValue;
};

export const SequenceFlag: {
    readonly None: EnumValue;
    readonly NonLooping: EnumValue;
};

export const TextureFlag: {
    readonly None: EnumValue;
    readonly WrapWidth: EnumValue;
    readonly WrapHeight: EnumValue;
};

export const NodeType: {
    readonly Bone: EnumValue;
    readonly Light: EnumValue;
    readonly Helper: EnumValue;
    readonly Attachment: EnumValue;
    readonly ParticleEmitter: EnumValue;
    readonly ParticleEmitter2: EnumValue;
    readonly RibbonEmitter: EnumValue;
    readonly EventObject: EnumValue;
    readonly Camera: EnumValue;
    readonly CollisionShape: EnumValue;
    readonly FaceEffect: EnumValue;
    readonly CornEmitter: EnumValue;
};

export const NodeFlag: {
    readonly None: EnumValue;
    readonly DontInheritTranslation: EnumValue;
    readonly DontInheritScaling: EnumValue;
    readonly DontInheritRotation: EnumValue;
    readonly Billboarded: EnumValue;
    readonly BillboardedLockX: EnumValue;
    readonly BillboardedLockY: EnumValue;
    readonly BillboardedLockZ: EnumValue;
    readonly CameraAnchored: EnumValue;
    readonly Bone: EnumValue;
    readonly Light: EnumValue;
    readonly EventObject: EnumValue;
    readonly Attachment: EnumValue;
    readonly ParticleEmitter: EnumValue;
    readonly CollisionShape: EnumValue;
    readonly RibbonEmitter: EnumValue;
    readonly Unshaded: EnumValue;
    readonly EmitterUsesMdl: EnumValue;
    readonly SortPrimitives: EnumValue;
    readonly SortPrimsFarZ: EnumValue;
    readonly EmitterUsesTga: EnumValue;
    readonly LineEmitter: EnumValue;
    readonly PopcornUnfogged: EnumValue;
    readonly Unfogged: EnumValue;
    readonly PopcornScaling: EnumValue;
    readonly ModelSpace: EnumValue;
    readonly XYQuad: EnumValue;
};

export const LayerFilterMode: {
    readonly None: EnumValue;
    readonly Transparent: EnumValue;
    readonly Blend: EnumValue;
    readonly Additive: EnumValue;
    readonly AddAlpha: EnumValue;
    readonly Modulate: EnumValue;
    readonly Modulate2x: EnumValue;
    readonly Count: EnumValue;
};

export const LayerShaderType: {
    readonly SD: EnumValue;
    readonly HD: EnumValue;
    readonly SDOnHD: EnumValue;
    readonly Terrain: EnumValue;
    readonly Water: EnumValue;
    readonly Fog: EnumValue;
    readonly Foliage: EnumValue;
    readonly FoliagePush: EnumValue;
    readonly Sprite: EnumValue;
    readonly DebugTexture: EnumValue;
    readonly DepthOfField: EnumValue;
    readonly BloomCombine: EnumValue;
    readonly BloomExtract: EnumValue;
    readonly GaussianBlur: EnumValue;
    readonly Tonemap: EnumValue;
    readonly Movie: EnumValue;
    readonly FFXCMAAEdge0: EnumValue;
    readonly FFXCMAAEdge1: EnumValue;
    readonly FFXCMAAEdgeCombine: EnumValue;
    readonly FFXCMAAProcessAndApply: EnumValue;
    readonly PopcornFX: EnumValue;
    readonly ConeIndicator: EnumValue;
    readonly CliffBlightMiscTerrain: EnumValue;
    readonly Distortion: EnumValue;
    readonly Crystal: EnumValue;
    readonly Imgui: EnumValue;
};

export const LayerShadingFlag: {
    readonly None: EnumValue;
    readonly Unshaded: EnumValue;
    readonly SphereEnvMap: EnumValue;
    readonly WrapWidth: EnumValue;
    readonly WrapHeight: EnumValue;
    readonly TwoSided: EnumValue;
    readonly Unfogged: EnumValue;
    readonly NoDepthTest: EnumValue;
    readonly NoDepthSet: EnumValue;
    readonly Unlit: EnumValue;
};

export const LayerSlotType: {
    readonly DiffuseMap: EnumValue;
    readonly NormalMap: EnumValue;
    readonly ORMMap: EnumValue;
    readonly EmissiveMap: EnumValue;
    readonly TeamColor: EnumValue;
    readonly EnvironmentMap: EnumValue;
    readonly Unknown: EnumValue;
};

export const MaterialFlag: {
    readonly None: EnumValue;
    readonly ConstantColor: EnumValue;
    readonly TwoSided: EnumValue;
    readonly Unfogged: EnumValue;
    readonly SortPrimsNearZ: EnumValue;
    readonly SortPrimsFarZ: EnumValue;
    readonly SortPrimitives: EnumValue;
    readonly FullResolution: EnumValue;
};

export const GeosetAnimationFlag: {
    readonly None: EnumValue;
    readonly DropShadow: EnumValue;
    readonly Color: EnumValue;
};

export const LightType: {
    readonly Omni: EnumValue;
    readonly Directional: EnumValue;
    readonly Ambient: EnumValue;
};

export const CollisionShapeShapeType: {
    readonly Box: EnumValue;
    readonly Plane: EnumValue;
    readonly Sphere: EnumValue;
    readonly Cylinder: EnumValue;
};

// ── Value-object types (plain JS objects) ──────────────────────────
export interface Extent {
    boundsRadius: number;
    minimum: Vector3f;
    maximum: Vector3f;
}

// ── Animation tracks ───────────────────────────────────────────────
export class TrackF32 extends EmbindObject {
    constructor();
    isUsed: boolean;
    interpolationType: EnumMember<typeof InterpolationType>;
    globalSequenceId: number;
    keyCount: number;
    timestamps: EmbindBufferVector<number, Uint32Array>;
    keys: EmbindBufferVector<number, Float32Array>;
}

export class TrackU32 extends EmbindObject {
    constructor();
    isUsed: boolean;
    interpolationType: EnumMember<typeof InterpolationType>;
    globalSequenceId: number;
    keyCount: number;
    timestamps: EmbindBufferVector<number, Uint32Array>;
    keys: EmbindBufferVector<number, Uint32Array>;
}

export class TrackQuaternion extends EmbindObject {
    constructor();
    isUsed: boolean;
    interpolationType: EnumMember<typeof InterpolationType>;
    globalSequenceId: number;
    keyCount: number;
    timestamps: EmbindBufferVector<number, Uint32Array>;
    keys: EmbindBufferVector<Quaternion, Float32Array>;
}

export class TrackVector3f extends EmbindObject {
    constructor();
    isUsed: boolean;
    interpolationType: EnumMember<typeof InterpolationType>;
    globalSequenceId: number;
    keyCount: number;
    timestamps: EmbindBufferVector<number, Uint32Array>;
    keys: EmbindBufferVector<Vector3f, Float32Array>;
}

// ── Classes ────────────────────────────────────────────────────────
export class Model extends EmbindObject {
    constructor();
    version: number;
    modelName: string;
    animationFileName: string;
    modelExtent: Extent;
    blendTime: number;
    globalSequences: EmbindBufferVector<number, Uint32Array>;
    sequences: EmbindVector<Sequence>;
    textures: EmbindVector<Texture>;
    sounds: EmbindVector<Sound>;
    soundEmitters: EmbindVector<SoundEmitter>;
    materials: EmbindVector<Material>;
    textureAnimations: EmbindVector<TextureAnimation>;
    geosets: EmbindVector<Geoset>;
    geosetAnimations: EmbindVector<GeosetAnimation>;
    bones: EmbindVector<Bone>;
    helpers: EmbindVector<Helper>;
    attachments: EmbindVector<Attachment>;
    pivotPoints: EmbindBufferVector<Vector3f, Float32Array>;
    lights: EmbindVector<Light>;
    particleEmitters: EmbindVector<ParticleEmitter>;
    particleEmitters2: EmbindVector<ParticleEmitter2>;
    ribbonEmitters: EmbindVector<RibbonEmitter>;
    cornEmitters: EmbindVector<CornEmitter>;
    eventObjects: EmbindVector<EventObject>;
    cameras: EmbindVector<Camera>;
    collisionShapes: EmbindVector<CollisionShape>;
    faceEffects: EmbindVector<FaceEffect>;
}

export class Sequence extends EmbindObject {
    constructor();
    name: string;
    intervalStart: number;
    intervalEnd: number;
    moveSpeed: number;
    flags: EnumMember<typeof SequenceFlag>;
    rarity: number;
    syncPoint: number;
    extent: Extent;
}

export class Texture extends EmbindObject {
    constructor();
    replaceableId: number;
    fileName: string;
    flags: EnumMember<typeof TextureFlag>;
}

export class Sound extends EmbindObject {
    constructor();
    soundFile: string;
    maximumDistance: number;
    minimumDistance: number;
    soundChannel: number;
}

export class Node extends EmbindObject {
    constructor();
    name: string;
    objectId: number;
    parentId: number;
    flags: EnumMember<typeof NodeFlag>;
    type: EnumMember<typeof NodeType>;
    nodeFamilyId: number;
    translationTracks: TrackVector3f;
    rotationTracks: TrackQuaternion;
    scalingTracks: TrackVector3f;
}

export class SoundEmitter extends EmbindObject {
    constructor();
    node: Node;
    soundTrack: TrackU32;
}

export class Layer extends EmbindObject {
    constructor();
    filterMode: EnumMember<typeof LayerFilterMode>;
    shadingFlags: EnumMember<typeof LayerShadingFlag>;
    textureId: number;
    textureAnimationId: number;
    coordId: number;
    alpha: number;
    emissiveGain: number;
    fresnelColor: Vector3f;
    fresnelOpacity: number;
    fresnelTeamColor: number;
    shader: EnumMember<typeof LayerShaderType>;
    isHd: boolean;
    subTextures: EmbindVector<LayerSubTexture>;
    textureIdTracks: TrackU32;
    alphaTracks: TrackF32;
    emissiveGainTracks: TrackF32;
    fresnelColorTracks: TrackVector3f;
    fresnelAlphaTracks: TrackF32;
    fresnelTeamColorTracks: TrackF32;
}

export class LayerSubTexture extends EmbindObject {
    constructor();
    textureId: number;
    slot: EnumMember<typeof LayerSlotType>;
    tracks: TrackU32;
}

export class Material extends EmbindObject {
    constructor();
    priorityPlane: number;
    flags: EnumMember<typeof MaterialFlag>;
    shader: string;
    layers: EmbindVector<Layer>;
}

export class TextureAnimation extends EmbindObject {
    constructor();
    translationTracks: TrackVector3f;
    rotationTracks: TrackQuaternion;
    scalingTracks: TrackVector3f;
}

export class Geoset extends EmbindObject {
    constructor();
    vertexPositions: EmbindBufferVector<Vector3f, Float32Array>;
    vertexNormals: EmbindBufferVector<Vector3f, Float32Array>;
    faceTypeGroups: EmbindBufferVector<number, Uint32Array>;
    faceGroups: EmbindBufferVector<number, Uint32Array>;
    faces: EmbindBufferVector<number, Uint16Array>;
    vertexGroups: EmbindBufferVector<number, Uint8Array>;
    vertexGroupsView(): Uint8Array;
    matrixGroups: EmbindBufferVector<number, Uint32Array>;
    matrixIndices: EmbindBufferVector<number, Uint32Array>;
    materialId: number;
    selectionGroup: number;
    selectionFlags: number;
    lod: number;
    lodName: string;
    extent: Extent;
    sequenceExtents: EmbindVector<Extent>;
    tangents: EmbindBufferVector<Vector4f, Float32Array>;
    skinData: EmbindBufferVector<number, Uint8Array>;
    skinDataView(): Uint8Array;
    textureCoordinateSets: EmbindVector<EmbindVector<Vector2f>>;
}

export class GeosetAnimation extends EmbindObject {
    constructor();
    alpha: number;
    flags: EnumMember<typeof GeosetAnimationFlag>;
    color: Vector3f;
    geosetId: number;
    alphaTracks: TrackF32;
    colorTracks: TrackVector3f;
}

export class Bone extends EmbindObject {
    constructor();
    node: Node;
    geosetId: number;
    geosetAnimationId: number;
}

export class Light extends EmbindObject {
    constructor();
    node: Node;
    type: EnumMember<typeof LightType>;
    attenuationStart: number;
    attenuationEnd: number;
    color: Vector3f;
    intensity: number;
    ambientColor: Vector3f;
    ambientIntensity: number;
    shadowIntensity: number;
    attenuationStartTracks: TrackF32;
    attenuationEndTracks: TrackF32;
    colorTracks: TrackVector3f;
    intensityTracks: TrackF32;
    ambientIntensityTracks: TrackF32;
    ambientColorTracks: TrackVector3f;
    visibilityTracks: TrackF32;
    shadowIntensityTracks: TrackF32;
}

export class Helper extends EmbindObject {
    constructor();
    node: Node;
}

export class Attachment extends EmbindObject {
    constructor();
    node: Node;
    path: string;
    attachmentId: number;
    visibilityTracks: TrackF32;
}

export class ParticleEmitter extends EmbindObject {
    constructor();
    node: Node;
    emissionRate: number;
    gravity: number;
    longitude: number;
    latitude: number;
    spawnModelFileName: string;
    lifespan: number;
    initialVelocity: number;
    emissionRateTracks: TrackF32;
    gravityTracks: TrackF32;
    longitudeTracks: TrackF32;
    latitudeTracks: TrackF32;
    lifespanTracks: TrackF32;
    speedTracks: TrackF32;
    visibilityTracks: TrackF32;
}

export class ParticleEmitter2 extends EmbindObject {
    constructor();
    node: Node;
    speed: number;
    variation: number;
    latitude: number;
    gravity: number;
    lifespan: number;
    emissionRate: number;
    length: number;
    width: number;
    filterMode: number;
    rows: number;
    columns: number;
    headOrTail: number;
    tailLength: number;
    time: number;
    textureId: number;
    squirt: number;
    priorityPlane: number;
    replaceableId: number;
    speedTracks: TrackF32;
    variationTracks: TrackF32;
    latitudeTracks: TrackF32;
    gravityTracks: TrackF32;
    emissionRateTracks: TrackF32;
    lengthTracks: TrackF32;
    widthTracks: TrackF32;
    visibilityTracks: TrackF32;
    getSegmentColor(): EmbindVector<Vector3f>;
    setSegmentColor(values: EmbindVector<Vector3f>): void;
    getSegmentAlpha(): EmbindVector<number>;
    setSegmentAlpha(values: EmbindVector<number>): void;
    getSegmentScaling(): EmbindVector<number>;
    setSegmentScaling(values: EmbindVector<number>): void;
    getHeadInterval(): EmbindVector<number>;
    setHeadInterval(values: EmbindVector<number>): void;
    getHeadDecayInterval(): EmbindVector<number>;
    setHeadDecayInterval(values: EmbindVector<number>): void;
    getTailInterval(): EmbindVector<number>;
    setTailInterval(values: EmbindVector<number>): void;
    getTailDecayInterval(): EmbindVector<number>;
    setTailDecayInterval(values: EmbindVector<number>): void;
}

export class RibbonEmitter extends EmbindObject {
    constructor();
    node: Node;
    heightAbove: number;
    heightBelow: number;
    alpha: number;
    color: Vector3f;
    lifespan: number;
    textureSlot: number;
    emissionRate: number;
    rows: number;
    columns: number;
    materialId: number;
    gravity: number;
    heightAboveTracks: TrackF32;
    heightBelowTracks: TrackF32;
    alphaTracks: TrackF32;
    colorTracks: TrackVector3f;
    textureSlotTracks: TrackU32;
    visibilityTracks: TrackF32;
}

export class EventObject extends EmbindObject {
    constructor();
    node: Node;
    globalSequenceId: number;
    eventTrackTimes: EmbindBufferVector<number, Uint32Array>;
}

export class Camera extends EmbindObject {
    constructor();
    name: string;
    position: Vector3f;
    fieldOfView: number;
    farClippingPlane: number;
    nearClippingPlane: number;
    targetPosition: Vector3f;
    positionTracks: TrackVector3f;
    targetRotationTracks: TrackF32;
    targetPositionTracks: TrackVector3f;
}

export class CollisionShape extends EmbindObject {
    constructor();
    node: Node;
    type: EnumMember<typeof CollisionShapeShapeType>;
    vertices: EmbindBufferVector<Vector3f, Float32Array>;
    radius: number;
}

export class FaceEffect extends EmbindObject {
    constructor();
    name: string;
    path: string;
}

export class CornEmitter extends EmbindObject {
    constructor();
    node: Node;
    lifeSpan: number;
    emissionRate: number;
    speed: number;
    color: Vector3f;
    alpha: number;
    replaceableId: number;
    path: string;
    animVisibilityGuide: string;
    lifeSpanTracks: TrackF32;
    emissionRateTracks: TrackF32;
    speedTracks: TrackF32;
    colorTracks: TrackVector3f;
    alphaTracks: TrackF32;
    visibilityTracks: TrackF32;
}

