// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.m3;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.common.internal.NativeCommon;
import whiteout.m3.internal.Native;

/**
 * DMSE — Convex hull half-edge (v0, 4 bytes)
 * 
 * Entries come in consecutive twin pairs: an even entry's twin is the next one (`twinOffset` +1), an odd entry's the previous (-1).
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * ConvexHullHalfEdge allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (ConvexHullHalfEdge obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class ConvexHullHalfEdge implements AutoCloseable {
    private static final long BYTES = 8L;

    final MemorySegment handle;
    final boolean owned;

    ConvexHullHalfEdge(MemorySegment seg, boolean owned) {
        this.handle = (seg == null || seg.equals(MemorySegment.NULL))
            ? seg : seg.reinterpret(BYTES);
        this.owned = owned;
    }

    public ConvexHullHalfEdge() {
        MemorySegment __raw = (MemorySegment) NativeCommon.invokeNative(Native.whiteout_m3_M3ConvexHullHalfEdge_new);
        if (__raw == null || __raw.equals(MemorySegment.NULL))
            throw new RuntimeException("ConvexHullHalfEdge allocation failed");
        this.handle = __raw.reinterpret(BYTES);
        this.owned = true;
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            NativeCommon.invokeNative(Native.whiteout_m3_M3ConvexHullHalfEdge_delete, handle);
        }
    }

    /**
     * +1 on the even entry of a pair, -1 on the odd one
     * @return the twinOffset field of this M3ConvexHullHalfEdge.
     */
    public byte getTwinOffset() {
        return handle.get(ValueLayout.JAVA_BYTE, 0L);
    }
    public void setTwinOffset(byte value) {
        handle.set(ValueLayout.JAVA_BYTE, 0L, value);
    }
    /**
     * Vertex the half-edge leaves
     * @return the originVertex field of this M3ConvexHullHalfEdge.
     */
    public byte getOriginVertex() {
        return handle.get(ValueLayout.JAVA_BYTE, 1L);
    }
    public void setOriginVertex(byte value) {
        handle.set(ValueLayout.JAVA_BYTE, 1L, value);
    }
    /**
     * Face the half-edge borders
     * @return the face field of this M3ConvexHullHalfEdge.
     */
    public byte getFace() {
        return handle.get(ValueLayout.JAVA_BYTE, 2L);
    }
    public void setFace(byte value) {
        handle.set(ValueLayout.JAVA_BYTE, 2L, value);
    }
    /**
     * Next half-edge around the same face
     * @return the nextInFace field of this M3ConvexHullHalfEdge.
     */
    public byte getNextInFace() {
        return handle.get(ValueLayout.JAVA_BYTE, 3L);
    }
    public void setNextInFace(byte value) {
        handle.set(ValueLayout.JAVA_BYTE, 3L, value);
    }
    @Override public String toString() {
        return "ConvexHullHalfEdge(" + "twinOffset=" + getTwinOffset() + ", " + "originVertex=" + getOriginVertex() + ", " + "face=" + getFace() + ", " + "nextInFace=" + getNextInFace() + ")";
    }

}
