// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.m3;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.m3.internal.Native;

/**
 * IKCC — CCD IK solver (v0, 24 bytes)
 * 
 * Cyclic Coordinate Descent IK solver with base/target bones and vertical search range.
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * IKCCD allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (IKCCD obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class IKCCD implements AutoCloseable {
    private static final long BYTES = 40L;

    final MemorySegment handle;
    final boolean owned;

    IKCCD(MemorySegment seg, boolean owned) {
        this.handle = (seg == null || seg.equals(MemorySegment.NULL))
            ? seg : seg.reinterpret(BYTES);
        this.owned = owned;
    }

    public IKCCD() {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_m3_M3IKCCD_new.invoke();
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("IKCCD allocation failed");
            this.handle = __raw.reinterpret(BYTES);
            this.owned = true;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                Native.whiteout_m3_M3IKCCD_delete.invoke(handle);
            } catch (Throwable __ex) { throw new RuntimeException(__ex); }
        }
    }

    /**
     * Dependent bone indices (U16_)
     * @return the dependents field of this M3IKCCD.
     */
    public int getDependentsCount() {
        try { return (int) (long) Native.whiteout_m3_M3IKCCD_get_dependents_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public short[] getDependents() {
        try {
            long __count = (long) Native.whiteout_m3_M3IKCCD_get_dependents_count.invoke(handle);
            MemorySegment __ptr = (MemorySegment) Native.whiteout_m3_M3IKCCD_get_dependents_data.invoke(handle);
            if (__count == 0 || __ptr == null || __ptr.equals(MemorySegment.NULL)) return new short[0];
            long __scalars = __count * 1L;
            return __ptr.reinterpret(__scalars * 2L).toArray(ValueLayout.JAVA_SHORT);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setDependents(short[] values) {
        try (Arena arena = Arena.ofConfined()) {
            long __count = (long) values.length / 1;
            MemorySegment __seg = arena.allocate((long) values.length * 2L);
            if (values.length > 0) MemorySegment.copy(values, 0, __seg, ValueLayout.JAVA_SHORT, 0, values.length);
            Native.whiteout_m3_M3IKCCD_assign_dependents.invoke(handle, __seg, __count);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeDependents(int count) {
        try { Native.whiteout_m3_M3IKCCD_resize_dependents.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /**
     * Base bone index
     * @return the boneBase field of this M3IKCCD.
     */
    public short getBoneBase() {
        return handle.get(ValueLayout.JAVA_SHORT, 24L);
    }
    public void setBoneBase(short value) {
        handle.set(ValueLayout.JAVA_SHORT, 24L, value);
    }
    /**
     * Target bone index
     * @return the boneTarget field of this M3IKCCD.
     */
    public short getBoneTarget() {
        return handle.get(ValueLayout.JAVA_SHORT, 26L);
    }
    public void setBoneTarget(short value) {
        handle.set(ValueLayout.JAVA_SHORT, 26L, value);
    }
    /**
     * Search range upward
     * @return the searchUp field of this M3IKCCD.
     */
    public float getSearchUp() {
        return handle.get(ValueLayout.JAVA_FLOAT, 28L);
    }
    public void setSearchUp(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 28L, value);
    }
    /**
     * Search range downward
     * @return the searchDown field of this M3IKCCD.
     */
    public float getSearchDown() {
        return handle.get(ValueLayout.JAVA_FLOAT, 32L);
    }
    public void setSearchDown(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 32L, value);
    }
    @Override public String toString() {
        return "IKCCD(" + "boneBase=" + getBoneBase() + ", " + "boneTarget=" + getBoneTarget() + ", " + "searchUp=" + getSearchUp() + ", " + "searchDown=" + getSearchDown() + ")";
    }

}
