// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py â€” do not edit.
package whiteout.m3;

/**
 * Particle rotation flags (PAR_.rotationFlags, v18+)
 */
public enum ParticleRotationFlag {
    None(0),
    /** Relative rotation */
    Relative(1),
    /** Always set */
    AlwaysSet(2);

    public final int value;
    ParticleRotationFlag(int v) { this.value = v; }
    public static ParticleRotationFlag fromInt(int v) {
        for (var e : values()) if (e.value == v) return e;
        throw new IllegalArgumentException("unknown ParticleRotationFlag: " + v);
    }
}
