// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py â€” do not edit.
package whiteout.m3;

/**
 * Particle emitter main flags (PAR_.flags)
 */
public enum ParticleFlag {
    None(0),
    /** Sort by distance */
    Sort(1),
    /** Collide with terrain */
    CollideTerrain(2),
    /** Collide with objects */
    CollideObjects(4),
    /** Emit on collision */
    CollideEmit(8),
    /** Emit from shape cutout */
    EmitShapeCutout(16),
    /** Inherit emission parameters */
    InheritEmitParams(32),
    /** Inherit parent velocity */
    InheritParentVelocity(64),
    /** Sort by height */
    SortHeight(128),
    /** Reverse sort order */
    SortReverse(256),
    /** Legacy rotation smoothing */
    OldRotationSmooth(512),
    /** Legacy rotation bezier */
    OldRotationBezier(1024),
    /** Legacy size smoothing */
    OldSizeSmooth(2048),
    /** Legacy size bezier */
    OldSizeBezier(4096),
    /** Legacy color smoothing */
    OldColorSmooth(8192),
    /** Legacy color bezier */
    OldColorBezier(16384),
    /** Lit particles */
    LitParts(32768),
    /** Random flipbook start */
    RandomFlipbookStart(65536),
    /** Multiply gravity by mass */
    MultiplyGravityByMass(131072),
    /** Clamp tail length */
    ClampTailLength(262144),
    /** Spawn trailing particles */
    SpawnTrailingParticles(524288),
    /** Fix tail length on creation */
    FixTailLengthOnCreation(1048576),
    /** Use vertex alpha */
    UseVertexAlpha(2097152),
    /** Use model particles */
    ModelParticles(4194304),
    /** Swap Y/Z on model particles */
    SwapYZOnModelParticles(8388608),
    /** Scale time by parent */
    ScaleTimeByParent(16777216),
    /** Use local time */
    UseLocalTime(33554432),
    /** Simulate on initialization */
    SimulateInit(67108864),
    /** Copy emitter */
    Copy(134217728);

    public final int value;
    ParticleFlag(int v) { this.value = v; }
    public static ParticleFlag fromInt(int v) {
        for (var e : values()) if (e.value == v) return e;
        return null;
    }
    /** Decompose a packed int into its set of ParticleFlag bits. */
    public static java.util.EnumSet<ParticleFlag> unpack(int packed) {
        java.util.EnumSet<ParticleFlag> out = java.util.EnumSet.noneOf(ParticleFlag.class);
        for (var e : values()) {
            if (e.value != 0 && (packed & e.value) == e.value) out.add(e);
        }
        return out;
    }
    /** OR every flag in {@code flags} together into a packed int. */
    public static int pack(java.util.Set<ParticleFlag> flags) {
        int v = 0;
        for (ParticleFlag f : flags) v |= f.value;
        return v;
    }
}
