// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.m3;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.common.internal.NativeCommon;
import whiteout.m3.internal.Native;

/**
 * PHYJ — Physics joint (v0, 180 bytes)
 * 
 * Joins the first body on each of two bones. Angles are radians. `enableLimits` and `enableFriction` are bytes to the client; the upper three bytes are never read.
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * PhysicsJoint allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (PhysicsJoint obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class PhysicsJoint implements AutoCloseable {
    private static final long BYTES = 184L;

    final MemorySegment handle;
    final boolean owned;

    PhysicsJoint(MemorySegment seg, boolean owned) {
        this.handle = (seg == null || seg.equals(MemorySegment.NULL))
            ? seg : seg.reinterpret(BYTES);
        this.owned = owned;
    }

    public PhysicsJoint() {
        MemorySegment __raw = (MemorySegment) NativeCommon.invokeNative(Native.whiteout_m3_M3PhysicsJoint_new);
        if (__raw == null || __raw.equals(MemorySegment.NULL))
            throw new RuntimeException("PhysicsJoint allocation failed");
        this.handle = __raw.reinterpret(BYTES);
        this.owned = true;
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            NativeCommon.invokeNative(Native.whiteout_m3_M3PhysicsJoint_delete, handle);
        }
    }

    /**
     * 0 spherical, 1 revolute, 2 cone-twist, 3 weld
     * @return the jointType field of this M3PhysicsJoint.
     */
    public int getJointType() {
        return handle.get(ValueLayout.JAVA_INT, 0L);
    }
    public void setJointType(int value) {
        handle.set(ValueLayout.JAVA_INT, 0L, value);
    }
    /**
     * First bone index
     * @return the boneIndex1 field of this M3PhysicsJoint.
     */
    public int getBoneIndex1() {
        return handle.get(ValueLayout.JAVA_INT, 4L);
    }
    public void setBoneIndex1(int value) {
        handle.set(ValueLayout.JAVA_INT, 4L, value);
    }
    /**
     * Second bone index
     * @return the boneIndex2 field of this M3PhysicsJoint.
     */
    public int getBoneIndex2() {
        return handle.get(ValueLayout.JAVA_INT, 8L);
    }
    public void setBoneIndex2(int value) {
        handle.set(ValueLayout.JAVA_INT, 8L, value);
    }
    /**
     * Enable angular limits (low byte)
     * @return the enableLimits field of this M3PhysicsJoint.
     */
    public int getEnableLimits() {
        return handle.get(ValueLayout.JAVA_INT, 140L);
    }
    public void setEnableLimits(int value) {
        handle.set(ValueLayout.JAVA_INT, 140L, value);
    }
    /**
     * Minimum limit angle
     * @return the limitMin field of this M3PhysicsJoint.
     */
    public float getLimitMin() {
        return handle.get(ValueLayout.JAVA_FLOAT, 144L);
    }
    public void setLimitMin(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 144L, value);
    }
    /**
     * Maximum limit angle
     * @return the limitMax field of this M3PhysicsJoint.
     */
    public float getLimitMax() {
        return handle.get(ValueLayout.JAVA_FLOAT, 148L);
    }
    public void setLimitMax(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 148L, value);
    }
    /**
     * Cone constraint angle
     * @return the coneAngle field of this M3PhysicsJoint.
     */
    public float getConeAngle() {
        return handle.get(ValueLayout.JAVA_FLOAT, 152L);
    }
    public void setConeAngle(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 152L, value);
    }
    /**
     * Enable joint friction (low byte)
     * @return the enableFriction field of this M3PhysicsJoint.
     */
    public int getEnableFriction() {
        return handle.get(ValueLayout.JAVA_INT, 156L);
    }
    public void setEnableFriction(int value) {
        handle.set(ValueLayout.JAVA_INT, 156L, value);
    }
    /**
     * Multiplier on an estimated gravity-holding torque
     * @return the friction field of this M3PhysicsJoint.
     */
    public float getFriction() {
        return handle.get(ValueLayout.JAVA_FLOAT, 160L);
    }
    public void setFriction(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 160L, value);
    }
    /**
     * Weld spring damping ratio
     * @return the dampingRatio field of this M3PhysicsJoint.
     */
    public float getDampingRatio() {
        return handle.get(ValueLayout.JAVA_FLOAT, 164L);
    }
    public void setDampingRatio(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 164L, value);
    }
    /**
     * Weld spring frequency
     * @return the angularFrequency field of this M3PhysicsJoint.
     */
    public float getAngularFrequency() {
        return handle.get(ValueLayout.JAVA_FLOAT, 168L);
    }
    public void setAngularFrequency(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 168L, value);
    }
    /**
     * Never read
     * @return the breakThreshold field of this M3PhysicsJoint.
     */
    public float getBreakThreshold() {
        return handle.get(ValueLayout.JAVA_FLOAT, 172L);
    }
    public void setBreakThreshold(float value) {
        handle.set(ValueLayout.JAVA_FLOAT, 172L, value);
    }
    /**
     * Collide connected
     * @return the enableShape field of this M3PhysicsJoint.
     */
    public byte getEnableShape() {
        return handle.get(ValueLayout.JAVA_BYTE, 176L);
    }
    public void setEnableShape(byte value) {
        handle.set(ValueLayout.JAVA_BYTE, 176L, value);
    }
    @Override public String toString() {
        return "PhysicsJoint(" + "jointType=" + getJointType() + ", " + "boneIndex1=" + getBoneIndex1() + ", " + "boneIndex2=" + getBoneIndex2() + ", " + "enableLimits=" + getEnableLimits() + ", " + "limitMin=" + getLimitMin() + ", " + "limitMax=" + getLimitMax() + ", " + "coneAngle=" + getConeAngle() + ", " + "enableFriction=" + getEnableFriction() + ", " + "friction=" + getFriction() + ", " + "dampingRatio=" + getDampingRatio() + ", " + "angularFrequency=" + getAngularFrequency() + ", " + "breakThreshold=" + getBreakThreshold() + ", " + "enableShape=" + getEnableShape() + ")";
    }

}
