// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.m2;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.m2.internal.Native;

/**
 * Java binding for the native AnimationTrack<whiteout::Vector3f> type.
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * AnimationTrack<whiteout::Vector3f> allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (AnimationTrackVector3f obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class AnimationTrackVector3f implements AutoCloseable {
    final MemorySegment handle;
    final boolean owned;

    AnimationTrackVector3f(MemorySegment seg, boolean owned) {
        this.handle = seg;
        this.owned = owned;
    }

    public AnimationTrackVector3f() {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_m2_M2AnimationTrackVector3f_new.invoke();
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("AnimationTrackVector3f allocation failed");
            this.handle = __raw;
            this.owned = true;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                Native.whiteout_m2_M2AnimationTrackVector3f_delete.invoke(handle);
            } catch (Throwable __ex) { throw new RuntimeException(__ex); }
        }
    }

    /** @return the interpolationType field of this M2AnimationTrackVector3f. */
    public InterpolationType getInterpolationType() {
        try { return InterpolationType.fromInt((int) Native.whiteout_m2_M2AnimationTrackVector3f_get_interpolationType.invoke(handle)); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setInterpolationType(InterpolationType value) {
        try { Native.whiteout_m2_M2AnimationTrackVector3f_set_interpolationType.invoke(handle, value.value); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /** @return the globalSequenceId field of this M2AnimationTrackVector3f. */
    public short getGlobalSequenceId() {
        try { return (short) Native.whiteout_m2_M2AnimationTrackVector3f_get_globalSequenceId.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setGlobalSequenceId(short value) {
        try { Native.whiteout_m2_M2AnimationTrackVector3f_set_globalSequenceId.invoke(handle, value); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /** @return the timestamps field of this M2AnimationTrackVector3f. */
    public int getTimestampsCount() {
        try { return (int) (long) Native.whiteout_m2_M2AnimationTrackVector3f_get_timestamps_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public int getTimestampsInnerCount(int outerIdx) {
        try { return (int) (long) Native.whiteout_m2_M2AnimationTrackVector3f_get_timestamps_inner_count.invoke(handle, (long) outerIdx); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeTimestamps(int count) {
        try { Native.whiteout_m2_M2AnimationTrackVector3f_resize_timestamps.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeTimestampsInner(int outerIdx, int innerCount) {
        try { Native.whiteout_m2_M2AnimationTrackVector3f_resize_timestamps_inner.invoke(handle, (long) outerIdx, (long) innerCount); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public int[] getTimestampsAt(int outerIdx) {
        try {
            long __count = (long) Native.whiteout_m2_M2AnimationTrackVector3f_get_timestamps_inner_count.invoke(handle, (long) outerIdx);
            MemorySegment __ptr = (MemorySegment) Native.whiteout_m2_M2AnimationTrackVector3f_get_timestamps_inner_data.invoke(handle, (long) outerIdx);
            if (__count == 0 || __ptr == null || __ptr.equals(MemorySegment.NULL)) return new int[0];
            long __scalars = __count * 1L;
            return __ptr.reinterpret(__scalars * 4L).toArray(ValueLayout.JAVA_INT);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setTimestampsAt(int outerIdx, int[] values) {
        try (Arena arena = Arena.ofConfined()) {
            long __count = (long) values.length / 1;
            MemorySegment __seg = arena.allocate((long) values.length * 4L);
            if (values.length > 0) MemorySegment.copy(values, 0, __seg, ValueLayout.JAVA_INT, 0, values.length);
            Native.whiteout_m2_M2AnimationTrackVector3f_assign_timestamps_inner.invoke(handle, (long) outerIdx, __seg, __count);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<int[]> getTimestamps() {
        int __outer = getTimestampsCount();
        java.util.ArrayList<int[]> __out = new java.util.ArrayList<>(__outer);
        for (int __i = 0; __i < __outer; __i++) __out.add(getTimestampsAt(__i));
        return __out;
    }
    public void setTimestamps(java.util.List<int[]> values) {
        resizeTimestamps(values.size());
        for (int __i = 0; __i < values.size(); __i++) setTimestampsAt(__i, values.get(__i));
    }
    /** @return the values field of this M2AnimationTrackVector3f. */
    public int getValuesCount() {
        try { return (int) (long) Native.whiteout_m2_M2AnimationTrackVector3f_get_values_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public int getValuesInnerCount(int outerIdx) {
        try { return (int) (long) Native.whiteout_m2_M2AnimationTrackVector3f_get_values_inner_count.invoke(handle, (long) outerIdx); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeValues(int count) {
        try { Native.whiteout_m2_M2AnimationTrackVector3f_resize_values.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeValuesInner(int outerIdx, int innerCount) {
        try { Native.whiteout_m2_M2AnimationTrackVector3f_resize_values_inner.invoke(handle, (long) outerIdx, (long) innerCount); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public float[] getValuesAt(int outerIdx) {
        try {
            long __count = (long) Native.whiteout_m2_M2AnimationTrackVector3f_get_values_inner_count.invoke(handle, (long) outerIdx);
            MemorySegment __ptr = (MemorySegment) Native.whiteout_m2_M2AnimationTrackVector3f_get_values_inner_data.invoke(handle, (long) outerIdx);
            if (__count == 0 || __ptr == null || __ptr.equals(MemorySegment.NULL)) return new float[0];
            long __scalars = __count * 3L;
            return __ptr.reinterpret(__scalars * 4L).toArray(ValueLayout.JAVA_FLOAT);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setValuesAt(int outerIdx, float[] values) {
        try (Arena arena = Arena.ofConfined()) {
            long __count = (long) values.length / 3;
            MemorySegment __seg = arena.allocate((long) values.length * 4L);
            if (values.length > 0) MemorySegment.copy(values, 0, __seg, ValueLayout.JAVA_FLOAT, 0, values.length);
            Native.whiteout_m2_M2AnimationTrackVector3f_assign_values_inner.invoke(handle, (long) outerIdx, __seg, __count);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<float[]> getValues() {
        int __outer = getValuesCount();
        java.util.ArrayList<float[]> __out = new java.util.ArrayList<>(__outer);
        for (int __i = 0; __i < __outer; __i++) __out.add(getValuesAt(__i));
        return __out;
    }
    public void setValues(java.util.List<float[]> values) {
        resizeValues(values.size());
        for (int __i = 0; __i < values.size(); __i++) setValuesAt(__i, values.get(__i));
    }
    @Override public String toString() {
        return "AnimationTrackVector3f(" + "interpolationType=" + getInterpolationType() + ", " + "globalSequenceId=" + getGlobalSequenceId() + ")";
    }

}
