// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py â€” do not edit.
package whiteout.m2;

/**
 * What a model's `PHYT` makes of it (`PHYS_FORMAT.md` §3.10).
 * 
 * A file with no PHYT reads as 0.
 */
public enum PhysicsObjectKind {
    /** Ragdoll whose kinematic bodies follow the model, not their bones: items worn on a character. 0 and 1 take the same branch in the client. */
    AttachedRagdoll(0),
    /** Ragdoll whose kinematic bodies follow the model, not their bones: items worn on a character. 0 and 1 take the same branch in the client. */
    AttachedRagdollAlt(1),
    /** Vegetation phantom built from the model's bounds and pushed by units. Needs a PHYV, and builds no bodies. */
    VegetationPhantom(2),
    /** Ragdoll in the shared physics world. */
    Ragdoll(3),
    /** Ragdoll in a physics world of its own, solved with twelve position iterations rather than two. */
    PrivateWorldRagdoll(4);

    public final int value;
    PhysicsObjectKind(int v) { this.value = v; }
    public static PhysicsObjectKind fromInt(int v) {
        for (var e : values()) if (e.value == v) return e;
        throw new IllegalArgumentException("unknown PhysicsObjectKind: " + v);
    }
}
