// SPDX-License-Identifier: BSD-3-Clause
// AUTOGENERATED by tools/codegen/emit_java.py - do not edit.
package whiteout.m2;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;
import java.nio.charset.StandardCharsets;
import whiteout.common.*;
import whiteout.common.internal.Handles;
import whiteout.m2.internal.Native;

/**
 * Java binding for the native SkinProfile type.
 *
 * <p><b>Lifecycle.</b> Instances hold a handle to a native
 * SkinProfile allocation. Always release them with
 * {@link #close()} — try-with-resources is the natural shape:
 * <pre>{@code
 * try (SkinProfile obj = ...) {
 *     // ... use obj ...
 * }
 * }</pre>
 * Borrowed views returned by field getters (e.g. nested struct slices)
 * share the parent's memory and must not outlive it.
 *
 * <p><b>Thread-safety.</b> Instances are not thread-safe. The underlying
 * C++ types make no synchronization guarantees, so callers must coordinate
 * external access if a handle is shared across threads.
 */
public final class SkinProfile implements AutoCloseable {
    private static final long BYTES = 152L;

    final MemorySegment handle;
    final boolean owned;

    SkinProfile(MemorySegment seg, boolean owned) {
        this.handle = (seg == null || seg.equals(MemorySegment.NULL))
            ? seg : seg.reinterpret(BYTES);
        this.owned = owned;
    }

    public SkinProfile() {
        try {
            MemorySegment __raw = (MemorySegment) Native.whiteout_m2_M2SkinProfile_new.invoke();
            if (__raw == null || __raw.equals(MemorySegment.NULL))
                throw new RuntimeException("SkinProfile allocation failed");
            this.handle = __raw.reinterpret(BYTES);
            this.owned = true;
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }

    @Override
    public void close() {
        if (!owned) return;
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                Native.whiteout_m2_M2SkinProfile_delete.invoke(handle);
            } catch (Throwable __ex) { throw new RuntimeException(__ex); }
        }
    }

    /** @return the vertices field of this M2SkinProfile. */
    public int getVerticesCount() {
        try { return (int) (long) Native.whiteout_m2_M2SkinProfile_get_vertices_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public short[] getVertices() {
        try {
            long __count = (long) Native.whiteout_m2_M2SkinProfile_get_vertices_count.invoke(handle);
            MemorySegment __ptr = (MemorySegment) Native.whiteout_m2_M2SkinProfile_get_vertices_data.invoke(handle);
            if (__count == 0 || __ptr == null || __ptr.equals(MemorySegment.NULL)) return new short[0];
            long __scalars = __count * 1L;
            return __ptr.reinterpret(__scalars * 2L).toArray(ValueLayout.JAVA_SHORT);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setVertices(short[] values) {
        try (Arena arena = Arena.ofConfined()) {
            long __count = (long) values.length / 1;
            MemorySegment __seg = arena.allocate((long) values.length * 2L);
            if (values.length > 0) MemorySegment.copy(values, 0, __seg, ValueLayout.JAVA_SHORT, 0, values.length);
            Native.whiteout_m2_M2SkinProfile_assign_vertices.invoke(handle, __seg, __count);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeVertices(int count) {
        try { Native.whiteout_m2_M2SkinProfile_resize_vertices.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /** @return the indices field of this M2SkinProfile. */
    public int getIndicesCount() {
        try { return (int) (long) Native.whiteout_m2_M2SkinProfile_get_indices_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public short[] getIndices() {
        try {
            long __count = (long) Native.whiteout_m2_M2SkinProfile_get_indices_count.invoke(handle);
            MemorySegment __ptr = (MemorySegment) Native.whiteout_m2_M2SkinProfile_get_indices_data.invoke(handle);
            if (__count == 0 || __ptr == null || __ptr.equals(MemorySegment.NULL)) return new short[0];
            long __scalars = __count * 1L;
            return __ptr.reinterpret(__scalars * 2L).toArray(ValueLayout.JAVA_SHORT);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void setIndices(short[] values) {
        try (Arena arena = Arena.ofConfined()) {
            long __count = (long) values.length / 1;
            MemorySegment __seg = arena.allocate((long) values.length * 2L);
            if (values.length > 0) MemorySegment.copy(values, 0, __seg, ValueLayout.JAVA_SHORT, 0, values.length);
            Native.whiteout_m2_M2SkinProfile_assign_indices.invoke(handle, __seg, __count);
        } catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeIndices(int count) {
        try { Native.whiteout_m2_M2SkinProfile_resize_indices.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    /** @return the submeshes field of this M2SkinProfile. */
    public int getSubmeshesCount() {
        try { return (int) (long) Native.whiteout_m2_M2SkinProfile_get_submeshes_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public SkinSection getSubmeshesAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_m2_M2SkinProfile_get_submeshes_at.invoke(handle, (long) index);
            return new SkinSection(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeSubmeshes(int count) {
        try { Native.whiteout_m2_M2SkinProfile_resize_submeshes.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<SkinSection> submeshesView() {
        return new java.util.AbstractList<SkinSection>() {
            @Override public int size() { return getSubmeshesCount(); }
            @Override public SkinSection get(int index) { return getSubmeshesAt(index); }
        };
    }
    /** @return the batches field of this M2SkinProfile. */
    public int getBatchesCount() {
        try { return (int) (long) Native.whiteout_m2_M2SkinProfile_get_batches_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public Batch getBatchesAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_m2_M2SkinProfile_get_batches_at.invoke(handle, (long) index);
            return new Batch(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeBatches(int count) {
        try { Native.whiteout_m2_M2SkinProfile_resize_batches.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<Batch> batchesView() {
        return new java.util.AbstractList<Batch>() {
            @Override public int size() { return getBatchesCount(); }
            @Override public Batch get(int index) { return getBatchesAt(index); }
        };
    }
    /** @return the lodVertexBase field of this M2SkinProfile. */
    public int getLodVertexBase() {
        return handle.get(ValueLayout.JAVA_INT, 120L);
    }
    public void setLodVertexBase(int value) {
        handle.set(ValueLayout.JAVA_INT, 120L, value);
    }
    /** @return the shadowBatches field of this M2SkinProfile. */
    public int getShadowBatchesCount() {
        try { return (int) (long) Native.whiteout_m2_M2SkinProfile_get_shadowBatches_count.invoke(handle); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public ShadowBatch getShadowBatchesAt(int index) {
        try { MemorySegment __h = (MemorySegment) Native.whiteout_m2_M2SkinProfile_get_shadowBatches_at.invoke(handle, (long) index);
            return new ShadowBatch(__h, false); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public void resizeShadowBatches(int count) {
        try { Native.whiteout_m2_M2SkinProfile_resize_shadowBatches.invoke(handle, (long) count); }
        catch (Throwable __ex) { throw new RuntimeException(__ex); }
    }
    public java.util.List<ShadowBatch> shadowBatchesView() {
        return new java.util.AbstractList<ShadowBatch>() {
            @Override public int size() { return getShadowBatchesCount(); }
            @Override public ShadowBatch get(int index) { return getShadowBatchesAt(index); }
        };
    }
    @Override public String toString() {
        return "SkinProfile(" + "lodVertexBase=" + getLodVertexBase() + ")";
    }

}
