// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026 Fernando Sahmkow
// AUTOGENERATED by tools/codegen/emit_csharp.py — DO NOT EDIT.

using System.Runtime.InteropServices;
using Whiteout.Common;
using Whiteout.M3.Internal;

namespace Whiteout.M3;

/// <summary>PHSH — Physics shape (v3, 300 bytes; v0 96, v1 132 and v2 292 read)</summary>
public sealed class PhysicsShape : WhiteoutHandle
{
    public PhysicsShape() : base(NativeMethods.whiteout_m3_M3PhysicsShape_new()) { }

    internal PhysicsShape(IntPtr handle, bool owned = true) : base(handle, owned) { }

    protected override bool ReleaseHandle()
    {
        NativeMethods.whiteout_m3_M3PhysicsShape_delete(handle);
        return true;
    }

    /// <summary>Shape type (box/sphere/capsule/cylinder/hull/mesh)</summary>
    public PhysicsShapeType ShapeType
    {
        get => (PhysicsShapeType)NativeMethods.whiteout_m3_M3PhysicsShape_get_shapeType(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_shapeType(DangerousGet(), (int)value);
    }


    /// <summary>Uncooked points (VEC3, +68), matrix not yet applied</summary>
    public unsafe ReadOnlySpan<Vector3f> SourcePoints
    {
        get
        {
            var __count = checked((int)NativeMethods.whiteout_m3_M3PhysicsShape_get_sourcePoints_count(DangerousGet()));
            var __ptr = NativeMethods.whiteout_m3_M3PhysicsShape_get_sourcePoints_data(DangerousGet());
            return new ReadOnlySpan<Vector3f>((void*)__ptr, __count);
        }
    }


    /// <summary>Box half-extents; sphere radius; capsule/cylinder radius, length</summary>
    public unsafe Vector3f ShapeDimensions
    {
        get
        {
            var __ptr = NativeMethods.whiteout_m3_M3PhysicsShape_get_shapeDimensions(DangerousGet());
            return System.Runtime.CompilerServices.Unsafe.Read<Vector3f>((void*)__ptr);
        }
        set
        {
            var __ptr = Whiteout.Common.NativeMath.whiteout_Vector3f_new();
            try
            {
                System.Runtime.CompilerServices.Unsafe.Write((void*)__ptr, value);
                NativeMethods.whiteout_m3_M3PhysicsShape_set_shapeDimensions(DangerousGet(), __ptr);
            }
            finally
            {
                Whiteout.Common.NativeMath.whiteout_Vector3f_delete(__ptr);
            }
        }
    }


    /// <summary>Vertex positions (VEC3)</summary>
    public unsafe ReadOnlySpan<Vector3f> HullVertices
    {
        get
        {
            var __count = checked((int)NativeMethods.whiteout_m3_M3PhysicsShape_get_hullVertices_count(DangerousGet()));
            var __ptr = NativeMethods.whiteout_m3_M3PhysicsShape_get_hullVertices_data(DangerousGet());
            return new ReadOnlySpan<Vector3f>((void*)__ptr, __count);
        }
    }


    /// <summary>Face planes (n, d), n unit length (VEC4)</summary>
    public unsafe ReadOnlySpan<Vector4f> HullPlanes
    {
        get
        {
            var __count = checked((int)NativeMethods.whiteout_m3_M3PhysicsShape_get_hullPlanes_count(DangerousGet()));
            var __ptr = NativeMethods.whiteout_m3_M3PhysicsShape_get_hullPlanes_data(DangerousGet());
            return new ReadOnlySpan<Vector4f>((void*)__ptr, __count);
        }
    }


    /// <summary>Half-edge table (DMSE), twin pairs</summary>
    public IReadOnlyList<ConvexHullHalfEdge> HullHalfEdges =>
        new NativeListView<ConvexHullHalfEdge>(
            DangerousGet(),
            NativeMethods.whiteout_m3_M3PhysicsShape_get_hullHalfEdges_count,
            (h, i) => new ConvexHullHalfEdge(NativeMethods.whiteout_m3_M3PhysicsShape_get_hullHalfEdges_at(h, i), owned: false));


    /// <summary>Volume centroid</summary>
    public unsafe Vector3f HullCentroid
    {
        get
        {
            var __ptr = NativeMethods.whiteout_m3_M3PhysicsShape_get_hullCentroid(DangerousGet());
            return System.Runtime.CompilerServices.Unsafe.Read<Vector3f>((void*)__ptr);
        }
        set
        {
            var __ptr = Whiteout.Common.NativeMath.whiteout_Vector3f_new();
            try
            {
                System.Runtime.CompilerServices.Unsafe.Write((void*)__ptr, value);
                NativeMethods.whiteout_m3_M3PhysicsShape_set_hullCentroid(DangerousGet(), __ptr);
            }
            finally
            {
                Whiteout.Common.NativeMath.whiteout_Vector3f_delete(__ptr);
            }
        }
    }


    /// <summary>Vertices the client reads</summary>
    public uint HullVertexCount
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_hullVertexCount(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_hullVertexCount(DangerousGet(), value);
    }


    /// <summary>Faces the client reads</summary>
    public uint HullFaceCount
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_hullFaceCount(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_hullFaceCount(DangerousGet(), value);
    }


    /// <summary>Half-edges the client reads</summary>
    public uint HullHalfEdgeCount
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_hullHalfEdgeCount(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_hullHalfEdgeCount(DangerousGet(), value);
    }


    /// <summary>Enclosed volume</summary>
    public float HullVolume
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_hullVolume(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_hullVolume(DangerousGet(), value);
    }


    /// <summary>Surface area</summary>
    public float HullSurfaceArea
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_hullSurfaceArea(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_hullSurfaceArea(DangerousGet(), value);
    }


    /// <summary>BVH tree nodes (DMMN), never read</summary>
    public IReadOnlyList<PhysicsMeshBvhNode> MeshBvhNodes =>
        new NativeListView<PhysicsMeshBvhNode>(
            DangerousGet(),
            NativeMethods.whiteout_m3_M3PhysicsShape_get_meshBvhNodes_count,
            (h, i) => new PhysicsMeshBvhNode(NativeMethods.whiteout_m3_M3PhysicsShape_get_meshBvhNodes_at(h, i), owned: false));


    /// <summary>Vertex positions, w=0 (VEC4)</summary>
    public unsafe ReadOnlySpan<Vector4f> MeshVertexPositions
    {
        get
        {
            var __count = checked((int)NativeMethods.whiteout_m3_M3PhysicsShape_get_meshVertexPositions_count(DangerousGet()));
            var __ptr = NativeMethods.whiteout_m3_M3PhysicsShape_get_meshVertexPositions_data(DangerousGet());
            return new ReadOnlySpan<Vector4f>((void*)__ptr, __count);
        }
    }


    /// <summary>Tree centre, as the client's builder computes it</summary>
    public unsafe Vector3f MeshBoundsCenter
    {
        get
        {
            var __ptr = NativeMethods.whiteout_m3_M3PhysicsShape_get_meshBoundsCenter(DangerousGet());
            return System.Runtime.CompilerServices.Unsafe.Read<Vector3f>((void*)__ptr);
        }
        set
        {
            var __ptr = Whiteout.Common.NativeMath.whiteout_Vector3f_new();
            try
            {
                System.Runtime.CompilerServices.Unsafe.Write((void*)__ptr, value);
                NativeMethods.whiteout_m3_M3PhysicsShape_set_meshBoundsCenter(DangerousGet(), __ptr);
            }
            finally
            {
                Whiteout.Common.NativeMath.whiteout_Vector3f_delete(__ptr);
            }
        }
    }


    /// <summary>Tree half-extent, likewise</summary>
    public unsafe Vector3f MeshBoundsExtent
    {
        get
        {
            var __ptr = NativeMethods.whiteout_m3_M3PhysicsShape_get_meshBoundsExtent(DangerousGet());
            return System.Runtime.CompilerServices.Unsafe.Read<Vector3f>((void*)__ptr);
        }
        set
        {
            var __ptr = Whiteout.Common.NativeMath.whiteout_Vector3f_new();
            try
            {
                System.Runtime.CompilerServices.Unsafe.Write((void*)__ptr, value);
                NativeMethods.whiteout_m3_M3PhysicsShape_set_meshBoundsExtent(DangerousGet(), __ptr);
            }
            finally
            {
                Whiteout.Common.NativeMath.whiteout_Vector3f_delete(__ptr);
            }
        }
    }


    /// <summary>Per-axis quantization step (= extent / 32767)</summary>
    public unsafe Vector3f MeshTolerance
    {
        get
        {
            var __ptr = NativeMethods.whiteout_m3_M3PhysicsShape_get_meshTolerance(DangerousGet());
            return System.Runtime.CompilerServices.Unsafe.Read<Vector3f>((void*)__ptr);
        }
        set
        {
            var __ptr = Whiteout.Common.NativeMath.whiteout_Vector3f_new();
            try
            {
                System.Runtime.CompilerServices.Unsafe.Write((void*)__ptr, value);
                NativeMethods.whiteout_m3_M3PhysicsShape_set_meshTolerance(DangerousGet(), __ptr);
            }
            finally
            {
                Whiteout.Common.NativeMath.whiteout_Vector3f_delete(__ptr);
            }
        }
    }


    /// <summary>DMMN count</summary>
    public uint MeshNormalCount
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_meshNormalCount(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_meshNormalCount(DangerousGet(), value);
    }


    /// <summary>Number of mesh vertices</summary>
    public uint MeshVertexCount
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_meshVertexCount(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_meshVertexCount(DangerousGet(), value);
    }


    /// <summary>MT16 face count (0 when MT32); the client reads this, not the Ref</summary>
    public uint MeshFaceIndex16Count
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_meshFaceIndex16Count(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_meshFaceIndex16Count(DangerousGet(), value);
    }


    /// <summary>MT32 face count (0 when MT16)</summary>
    public uint MeshFaceIndex32Count
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_meshFaceIndex32Count(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_meshFaceIndex32Count(DangerousGet(), value);
    }


    /// <summary>Never read</summary>
    public uint MeshUnknown1
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_meshUnknown1(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_meshUnknown1(DangerousGet(), value);
    }


    /// <summary>Never read</summary>
    public uint MeshReserved
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_meshReserved(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_meshReserved(DangerousGet(), value);
    }


    /// <summary>Tree height, as the client's builder computes it</summary>
    public uint MeshTreeDepth
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_meshTreeDepth(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_meshTreeDepth(DangerousGet(), value);
    }


    /// <summary>Never read</summary>
    public float MeshCollisionMargin
    {
        get => NativeMethods.whiteout_m3_M3PhysicsShape_get_meshCollisionMargin(DangerousGet());
        set => NativeMethods.whiteout_m3_M3PhysicsShape_set_meshCollisionMargin(DangerousGet(), value);
    }

}
